Repository chartjs/Chart.js, pull requests merged in 2018-06, with the labels that each got.

#5528 Change readme and docs on bundled version
  README.md
  docs/getting-started/installation.md
Labels: type: documentation

#5521 Handle '\n' as newline in tooltips
  src/core/core.tooltip.js
  test/specs/core.tooltip.tests.js
Labels: type: bug

#5571 Direct questions and support to StackOverflow
  .github/ISSUE_TEMPLATE.md
Labels: type: infrastructure

#5279 Added 'angle' option to Polar Charts
  src/controllers/controller.polarArea.js
  test/fixtures/controller.polarArea/angle-array.json
  test/fixtures/controller.polarArea/angle-array.png
  test/fixtures/controller.polarArea/angle-undefined.json
  test/fixtures/controller.polarArea/angle-undefined.png
  test/specs/controller.polarArea.tests.js
Labels: type: enhancement

#5592 Call update() and render() with a config object
  src/core/core.controller.js
Labels: type: enhancement

#5570 Restore original styles when removing hover
  karma.conf.js
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.line.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/core/core.datasetController.js
  test/specs/controller.bar.tests.js
  test/specs/controller.doughnut.tests.js
  test/specs/controller.line.tests.js
  test/specs/controller.polarArea.tests.js
  test/specs/controller.radar.tests.js
Labels: type: bug

#5595 chore: use comment for pullrequest template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: infrastructure

#5597 Enhance the rounded rectangle implementation
  src/helpers/helpers.canvas.js
  test/jasmine.context.js
  test/specs/element.point.tests.js
  test/specs/helpers.canvas.tests.js
Labels: type: enhancement
