Repository chartjs/Chart.js, pull requests merged in 2018-09, with the labels that each got.

#5724 Adding watch task for docs
  docs/developers/contributing.md
  gulpfile.js
Labels: type: infrastructure

#5719 Adding Accessibility page
  docs/SUMMARY.md
  docs/general/accessibility.md
Labels: type: documentation

#5723 Fix bug when data is all small numbers
  src/core/core.ticks.js
  src/scales/scale.linearbase.js
  test/specs/scale.linear.tests.js
Labels: type: bug

#5734 Added Wicked-Charts to the Popular Extensions Page
  docs/notes/extensions.md
Labels: type: documentation
