Repository chartjs/Chart.js, pull requests merged in 2018-11, with the labels that each got.

#5609 Fix offsetGridLine behavior with a single data point
  src/core/core.scale.js
  test/specs/core.scale.tests.js
Labels: type: bug

#5796 Consistent use of punctuation and quick review in docs
  docs/README.md
  docs/axes/README.md
  docs/axes/cartesian/README.md
  docs/axes/cartesian/time.md
  docs/axes/labelling.md
  docs/axes/radial/linear.md
  docs/axes/styling.md
  docs/charts/README.md
  docs/charts/area.md
  docs/charts/bar.md
  docs/charts/bubble.md
  docs/charts/doughnut.md
  docs/charts/line.md
  docs/charts/polar.md
  docs/charts/radar.md
  docs/configuration/README.md
  docs/configuration/animations.md
  docs/configuration/elements.md
  docs/configuration/legend.md
  docs/configuration/title.md
  docs/configuration/tooltip.md
  docs/developers/api.md
  docs/developers/charts.md
  docs/general/colors.md
  docs/general/interactions/README.md
  docs/general/interactions/events.md
  docs/general/interactions/modes.md
Labels: type: documentation

#5816 Fix legend item layout issue
  src/plugins/plugin.legend.js
  test/specs/plugin.legend.tests.js
Labels: type: bug

#5827 Change the .editorconfig file to include final newlines
  .editorconfig
Labels: type: infrastructure

#5786 Support decimal stepSize
  src/core/core.helpers.js
  src/scales/scale.linearbase.js
  test/specs/core.helpers.tests.js
  test/specs/scale.linear.tests.js
Labels: type: bug

#5780 Make bar styling options scriptable
  docs/charts/bar.md
  gulpfile.js
  samples/samples.js
  samples/scriptable/bar.html
  samples/utils.js
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  test/fixtures/controller.bar/backgroundColor/indexable.js
  test/fixtures/controller.bar/backgroundColor/indexable.png
  test/fixtures/controller.bar/backgroundColor/scriptable.js
  test/fixtures/controller.bar/backgroundColor/scriptable.png
  test/fixtures/controller.bar/backgroundColor/value.js
  test/fixtures/controller.bar/backgroundColor/value.png
  test/fixtures/controller.bar/borderColor/indexable.js
  test/fixtures/controller.bar/borderColor/indexable.png
  test/fixtures/controller.bar/borderColor/scriptable.js
  test/fixtures/controller.bar/borderColor/scriptable.png
  test/fixtures/controller.bar/borderColor/value.js
  test/fixtures/controller.bar/borderColor/value.png
  test/fixtures/controller.bar/borderSkipped/indexable.js
  test/fixtures/controller.bar/borderSkipped/indexable.png
  test/fixtures/controller.bar/borderSkipped/scriptable.js
  test/fixtures/controller.bar/borderSkipped/scriptable.png
  test/fixtures/controller.bar/borderSkipped/value.js
  test/fixtures/controller.bar/borderSkipped/value.png
  test/fixtures/controller.bar/borderWidth/indexable.js
  test/fixtures/controller.bar/borderWidth/indexable.png
  test/fixtures/controller.bar/borderWidth/scriptable.js
  test/fixtures/controller.bar/borderWidth/scriptable.png
  test/fixtures/controller.bar/borderWidth/value.js
  test/fixtures/controller.bar/borderWidth/value.png
Labels: type: enhancement

#5833 Check pixel values within the logarithmic scale unit test using the pixel proximity matcher
  test/specs/scale.logarithmic.tests.js
Labels: type: infrastructure

#5776 Make legend layouting respect padding at the start of columns
  test/specs/plugin.legend.tests.js
Labels: type: bug

#5831 Correct spelling mistake.
  docs/general/fonts.md
Labels: type: documentation

#5840 Upgrade dev dependencies to reduce vulnerabilities
  gulpfile.js
  package.json
  src/platforms/platform.dom.js
  test/specs/core.controller.tests.js
  test/specs/core.plugin.tests.js
Labels: type: infrastructure

#5828 Is node shadow root check improved
  src/core/core.helpers.js
Labels: type: bug

#5751 Handle axis lineWidth as an array
  src/core/core.scale.js
Labels: type: bug

#5842 Use short labels for the legend tests so as not to be affected by the font width
  test/specs/plugin.legend.tests.js
Labels: type: infrastructure

#5846 Correct calculation of padding in percent
  src/core/core.helpers.js
  test/specs/core.helpers.tests.js
Labels: type: bug

#5850 Add support for gridLines/angleLines borderDash for polarArea/radar charts
  docs/axes/radial/linear.md
  docs/axes/styling.md
  src/core/core.scale.js
  src/scales/scale.radialLinear.js
  test/fixtures/scale.radialLinear/border-dash.json
  test/fixtures/scale.radialLinear/border-dash.png
  test/fixtures/scale.radialLinear/circular-border-dash.json
  test/fixtures/scale.radialLinear/circular-border-dash.png
  test/fixtures/scale.radialLinear/indexable-gridlines.json
  test/fixtures/scale.radialLinear/indexable-gridlines.png
  test/specs/scale.radialLinear.tests.js
Labels: type: enhancement

#5855 Moved drawing of radial lines before drawing the tick labels
  src/scales/scale.radialLinear.js
Labels: type: bug

#5865 Support CanvasGradient for hover colors
  src/core/core.helpers.js
  test/specs/core.helpers.tests.js
Labels: type: bug

#5858 Adjust the size of rectRounded/rectRot points to fit the circle with pointRadius
  src/helpers/helpers.canvas.js
  test/fixtures/controller.bubble/point-style.png
  test/fixtures/controller.line/point-style.png
  test/fixtures/controller.radar/point-style.png
  test/fixtures/element.point/point-style-rect-rot.png
  test/fixtures/element.point/point-style-rect-rounded.png
  test/fixtures/element.point/rotation.js
  test/fixtures/element.point/rotation.png
  test/fixtures/helpers.canvas/rounded-rect.js
  test/fixtures/helpers.canvas/rounded-rect.png
  test/specs/element.point.tests.js
  test/specs/helpers.canvas.tests.js
Labels: type: bug

#5854 Supply docs for barThickness
  docs/charts/bar.md
Labels: type: documentation

#5848 Fix the issue that the topmost tick label and the bottom of the chart area are cut off with a radial scale
  src/scales/scale.radialLinear.js
  test/fixtures/controller.radar/point-style.png
  test/fixtures/plugin.filler/fill-radar-boundary-origin-spline.png
  test/fixtures/plugin.filler/fill-radar-boundary-origin.png
  test/specs/controller.doughnut.tests.js
  test/specs/controller.polarArea.tests.js
  test/specs/controller.radar.tests.js
  test/specs/scale.radialLinear.tests.js
Labels: type: bug

#5868 Deprecate Chart.{Type} classes
  src/chart.js
  src/charts/Chart.Bar.js
  src/charts/Chart.Bubble.js
  src/charts/Chart.Doughnut.js
  src/charts/Chart.Line.js
  src/charts/Chart.PolarArea.js
  src/charts/Chart.Radar.js
  src/charts/Chart.Scatter.js
  test/specs/global.deprecations.tests.js
Labels: type: chore

#5869 Tooltip support for CanvasPattern and CanvasGradient
  src/core/core.tooltip.js
  test/fixtures/core.tooltip/opacity.js
  test/fixtures/core.tooltip/opacity.png
  test/specs/core.tooltip.tests.js
Labels: type: bug

#5872 Fix test failures on Windows
  test/specs/controller.radar.tests.js
Labels: type: chore

#5871 Make Chart.controllers.* importable
  src/chart.js
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.horizontalBar.js
  src/controllers/controller.line.js
  src/controllers/controller.pie.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/controllers/controller.scatter.js
  src/controllers/index.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  test/specs/controller.bar.tests.js
  test/specs/controller.bubble.tests.js
  test/specs/controller.doughnut.tests.js
  test/specs/controller.line.tests.js
  test/specs/controller.polarArea.tests.js
  test/specs/controller.radar.tests.js
  test/specs/controller.scatter.test.js
Labels: type: chore
