Repository chartjs/Chart.js, pull requests merged in 2018-08, with the labels that each got.

#5661 Enhancement - Add Colour To Financial Time Series Sample
  samples/scales/time/financial.html
Labels: type: documentation

#5663 Fix For Adding And Removing Datasets For Bar Samples
  samples/charts/bar/horizontal.html
  samples/charts/bar/vertical.html
Labels: type: bug, type: documentation

#5575 Event handling to use target instead currentTarget
  src/core/core.helpers.js
Labels: type: enhancement
