Repository chartjs/Chart.js, pull requests merged in 2018-10, with the labels that each got.

#5756 Add aspectRatio property to responsive doc
  docs/general/responsive.md
Labels: type: documentation

#5769 Add 'parser' instead of deprecated 'format'
  samples/scales/time/line.html
Labels: type: documentation

#5750 Ensure that when the time axis accesses `data.labels` it actually exists
  src/scales/scale.time.js
Labels: type: bug

#5741 Introduce the 'minBarLength' dataset property for bar scales (X or Y)
  docs/charts/bar.md
  src/controllers/controller.bar.js
  test/specs/scale.linear.tests.js
Labels: status: awaiting review

#5624 Radar code cleanup
  src/controllers/controller.radar.js
Labels: type: enhancement

#5790 Add error margin for detecting if a point or line is in the chartArea
  src/core/core.scale.js
  src/elements/element.point.js
Labels: type: bug
