Repository chartjs/Chart.js, pull requests merged in 2018-12, with the labels that each got.

#5875 Remove gulp-connect and add jsdelivr/unpkg paths
  .travis.yml
  gulpfile.js
  package.json
Labels: type: infrastructure

#5877 Replace repeated function call with compact function, generateData
  samples/charts/scatter/basic.html
Labels: type: documentation

#5876 Fix descriptions in bar chart doc
  docs/charts/bar.md
Labels: type: documentation

#5884 Remove gaps on the left and right when the axis offset is set to true
  src/core/core.scale.js
  test/specs/scale.category.tests.js
Labels: type: bug

#5880 Fix the rounding issue of floating point numbers in category scale
  src/core/core.helpers.js
  src/core/core.scale.js
  src/core/core.tooltip.js
  src/scales/scale.category.js
  src/scales/scale.radialLinear.js
  test/fixtures/controller.line/point-style.png
  test/fixtures/controller.radar/point-style.png
  test/fixtures/core.scale/tick-drawing.png
  test/fixtures/core.tooltip/opacity.png
  test/fixtures/scale.radialLinear/border-dash.png
  test/fixtures/scale.radialLinear/indexable-gridlines.png
  test/specs/core.scale.tests.js
  test/specs/core.tooltip.tests.js
  test/specs/global.deprecations.tests.js
  test/specs/scale.category.tests.js
  test/specs/scale.radialLinear.tests.js
Labels: type: bug

#5891 Remove autoSkip logic to always display last tick
  src/core/core.scale.js
  test/specs/core.scale.tests.js
Labels: type: bug

#5909 Remove `innerHTML` usage from our DOM platform
  src/platforms/platform.dom.js
Labels: type: bug

#5904 Migrate from Browserify to rollup
  docs/developers/contributing.md
  gulpfile.js
  karma.conf.js
  package.json
  rollup.config.js
  src/core/core.animation.js
  src/core/core.datasetController.js
  src/core/core.tooltip.js
  src/helpers/helpers.canvas.js
  src/scales/scale.time.js
Labels: type: bug, type: enhancement, type: infrastructure

#5885 Add support for hiding axis when a dataset visibility is toggled
  docs/axes/README.md
  src/core/core.scale.js
  test/specs/core.scale.tests.js
Labels: type: enhancement

#5841 Draw inner border for arc elements
  docs/charts/doughnut.md
  docs/charts/polar.md
  src/controllers/controller.doughnut.js
  src/controllers/controller.polarArea.js
  src/elements/element.arc.js
  test/context.js
  test/fixtures/controller.doughnut/doughnut-border-align-center.json
  test/fixtures/controller.doughnut/doughnut-border-align-center.png
  test/fixtures/controller.doughnut/doughnut-border-align-inner.json
  test/fixtures/controller.doughnut/doughnut-border-align-inner.png
  test/fixtures/controller.doughnut/pie-border-align-center.json
  test/fixtures/controller.doughnut/pie-border-align-center.png
  test/fixtures/controller.doughnut/pie-border-align-inner.json
  test/fixtures/controller.doughnut/pie-border-align-inner.png
  test/fixtures/controller.polarArea/border-align-center.json
  test/fixtures/controller.polarArea/border-align-center.png
  test/fixtures/controller.polarArea/border-align-inner.json
  test/fixtures/controller.polarArea/border-align-inner.png
  test/specs/controller.doughnut.tests.js
  test/specs/core.tooltip.tests.js
  test/specs/element.arc.tests.js
Labels: type: enhancement

#5908 adds midpoint interpolation to stepped plots
  docs/charts/line.md
  samples/charts/line/stepped.html
  src/helpers/helpers.canvas.js
  test/specs/element.line.tests.js
Labels: type: enhancement

#5905 add support for typed arrays
  src/helpers/helpers.core.js
  test/.eslintrc.yml
  test/specs/helpers.core.tests.js
Labels: type: enhancement

#5914 Add scale.pointLabels.lineHeight and scale.ticks.lineHeight options
  docs/axes/radial/linear.md
  docs/axes/styling.md
  src/core/core.defaults.js
  src/core/core.js
  src/core/core.scale.js
  src/elements/element.line.js
  src/elements/element.point.js
  src/elements/element.rectangle.js
  src/helpers/helpers.options.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.title.js
  src/scales/scale.radialLinear.js
  test/fixtures/controller.radar/point-style.png
  test/fixtures/plugin.filler/fill-radar-boundary-origin-spline.png
  test/fixtures/plugin.filler/fill-radar-boundary-origin.png
  test/specs/controller.radar.tests.js
  test/specs/core.controller.tests.js
  test/specs/core.scale.tests.js
  test/specs/helpers.options.tests.js
  test/specs/plugin.legend.tests.js
  test/specs/plugin.title.tests.js
  test/specs/scale.category.tests.js
  test/specs/scale.linear.tests.js
  test/specs/scale.radialLinear.tests.js
Labels: type: bug

#5927 Add `reverse` support to time scale
  src/scales/scale.time.js
  test/specs/scale.time.tests.js
Labels: type: enhancement

#5922 autoSkip: properly calculate space needed by tick label
  src/core/core.scale.js
  test/specs/core.scale.tests.js
Labels: type: bug

#5936 Fix "RangeError: Maximum call stack size exceeded" exception when labels are big (>125000) - #5935
  src/scales/scale.time.js
Labels: type: bug
