Repository chartjs/Chart.js, pull requests merged in 2018-02, with the labels that each got.

#5248 Fixes Label Array Tick alignment and Centering
  src/core/core.scale.js
Labels: type: bug

#5240 Support multiple font colors for radial chart labels
  docs/axes/radial/linear.md
  src/scales/scale.radialLinear.js
Labels: type: enhancement

#5256 Improve title of generated documentation
  book.json
Labels: type: documentation

#5274 Improve README.md
  README.md
  docs/getting-started/installation.md
Labels: type: documentation

#5275 Bugfix: Improve polyfill function of log10 to return whole powers of 10
  src/core/core.helpers.js
  test/specs/core.helpers.tests.js
Labels: type: bug
