Repository chartjs/Chart.js, pull requests merged in 2018-03, with the labels that each got.

#5307 Bump version to 2.7.2
  package.json
Labels: type: infrastructure

#5309 Add a link to chartjs-plugin-streaming to extensions.md
  docs/notes/extensions.md
Labels: type: documentation

#5326 Show how to use circumfere and rotation options
  samples/charts/doughnut.html
Labels: type: documentation

#5324 Enable running on node
  src/core/core.helpers.js
Labels: type: enhancement

#5328 Fix Time Point Data Sample Add Data Button
  samples/scales/time/line-point-data.html
Labels: type: documentation

#5348 Typo
  docs/configuration/legend.md
Labels: type: documentation
