Repository chartjs/Chart.js, pull requests merged in 2019-11, with the labels that each got.

#6665 Fix polar area sample
  samples/charts/polar-area.html
Labels: type: documentation

#6666 Add radial and linear gradient sample files
  samples/advanced/line-gradient.html
  samples/advanced/radial-gradient.html
  samples/samples.js
Labels: type: documentation

#6676 Comment explaining hover animation
  src/core/core.element.js
Labels: type: documentation

#6576 Early data parsing, stacking by value and support object data
  docs/developers/axes.md
  docs/getting-started/v3-migration.md
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.line.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/core/core.datasetController.js
  src/core/core.scale.js
  src/core/core.tooltip.js
  src/scales/scale.category.js
  src/scales/scale.linear.js
  src/scales/scale.linearbase.js
  src/scales/scale.logarithmic.js
  src/scales/scale.radialLinear.js
  src/scales/scale.time.js
  test/fixtures/controller.bar/data/object.js
  test/fixtures/controller.bar/data/object.png
  test/fixtures/controller.bar/floatBar/float-bar-stacked-horizontal.png
  test/fixtures/controller.bar/floatBar/float-bar-stacked.png
  test/fixtures/controller.bubble/radius-data.js
  test/fixtures/controller.bubble/radius-data.png
  test/specs/scale.category.tests.js
  test/specs/scale.linear.tests.js
  test/specs/scale.logarithmic.tests.js
  test/specs/scale.radialLinear.tests.js
  test/specs/scale.time.tests.js
Labels: breaking change, type: infrastructure

#6692 Remove tension option backwards compatibility
  docs/getting-started/v3-migration.md
  src/controllers/controller.line.js
Labels: breaking change

#6694 Remove unused Element methods
  docs/getting-started/v3-migration.md
  src/elements/element.arc.js
  src/elements/element.point.js
  src/elements/element.rectangle.js
  test/specs/element.arc.tests.js
  test/specs/element.point.tests.js
  test/specs/element.rectangle.tests.js
Labels: breaking change

#6691 Remove unused model properties
  docs/getting-started/v3-migration.md
  src/controllers/controller.bar.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.polarArea.js
  test/specs/controller.bar.tests.js
  test/specs/controller.doughnut.tests.js
  test/specs/controller.polarArea.tests.js
Labels: breaking change

#6697 Remove zeroLineIndex functionality
  docs/axes/styling.md
  docs/getting-started/v3-migration.md
  src/core/core.scale.js
  src/scales/scale.linearbase.js
  test/fixtures/core.scale/tick-drawing.json
  test/specs/scale.category.tests.js
  test/specs/scale.linear.tests.js
  test/specs/scale.logarithmic.tests.js
  test/specs/scale.radialLinear.tests.js
  test/specs/scale.time.tests.js
Labels: breaking change

#5824 Generate jsdocs
  docs/SUMMARY.md
  docs/developers/plugins.md
  gulpfile.js
  package.json
Labels: status: awaiting review, type: documentation, type: infrastructure

#6713 Context compatibility with dataLabels
  docs/getting-started/v3-migration.md
  src/core/core.datasetController.js
Labels: breaking change

#6699 Fix undefined variable
  src/core/core.scale.js
Labels: type: bug

#6698 [2.9] Fix undefined variable
  src/core/core.scale.js
Labels: type: bug

#6721 Remove unused method. Prefix private ones with underscore
  docs/getting-started/v3-migration.md
  src/scales/scale.time.js
Labels: breaking change

#6727 Remove helpers.previousItem/nextItem
  docs/getting-started/v3-migration.md
  src/controllers/controller.line.js
  src/controllers/controller.radar.js
  src/core/core.helpers.js
  src/elements/element.line.js
  test/specs/core.helpers.tests.js
Labels: breaking change

#6734 Remove unused helpers.canvas.roundedRect
  docs/getting-started/v3-migration.md
  src/helpers/helpers.canvas.js
  test/fixtures/helpers.canvas/rounded-rect.js
  test/fixtures/helpers.canvas/rounded-rect.png
  test/specs/helpers.canvas.tests.js
Labels: breaking change

#6745 Remove moment from dependencies
  docs/axes/cartesian/time.md
  docs/getting-started/integration.md
  docs/getting-started/v3-migration.md
  package-lock.json
  package.json
Labels: breaking change

#6722 Change updateElement to updateElements
  docs/getting-started/v3-migration.md
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.line.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/core/core.datasetController.js
Labels: breaking change

#6777 Remove Element.initialize
  docs/getting-started/v3-migration.md
  src/core/core.controller.js
  src/core/core.element.js
  src/core/core.tooltip.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.title.js
Labels: breaking change

#6785 Add min/max to performance documentation
  docs/general/performance.md
Labels: type: documentation
