Repository chartjs/Chart.js, pull requests merged in 2019-07, with the labels that each got.

#6343 Handle reverse support in core.scale
  src/controllers/controller.bar.js
  src/core/core.controller.js
  src/core/core.helpers.js
  src/core/core.scale.js
  src/helpers/helpers.math.js
  src/scales/scale.category.js
  src/scales/scale.linear.js
  src/scales/scale.linearbase.js
  src/scales/scale.logarithmic.js
  src/scales/scale.time.js
  test/specs/core.helpers.tests.js
  test/specs/core.scale.tests.js
  test/specs/helpers.math.tests.js
  test/specs/scale.linear.tests.js
  test/specs/scale.logarithmic.tests.js
  test/specs/scale.time.tests.js
Labels: type: enhancement

#6354 Perf improvement for ticks.source:'labels'
  src/scales/scale.time.js
Labels: time scale

#6326 Draw the rightmost grid line when offsetGridLines is true
  src/core/core.scale.js
  src/scales/scale.radialLinear.js
  test/specs/core.scale.tests.js
  test/specs/scale.category.tests.js
  test/specs/scale.linear.tests.js
  test/specs/scale.logarithmic.tests.js
  test/specs/scale.radialLinear.tests.js
  test/specs/scale.time.tests.js
Labels: type: enhancement

#6393 Add radar chart config options
  docs/charts/radar.md
  src/controllers/controller.radar.js
Labels: type: documentation
