Repository chartjs/Chart.js, pull requests merged in 2019-04, with the labels that each got.

#6169 Remove datapoint with duplicate timestamp in order to fix sample
  samples/scales/time/financial.html
Labels: type: bug

#6097 Specify time scale options in standard manner
  docs/axes/cartesian/README.md
  docs/axes/cartesian/linear.md
  docs/axes/cartesian/logarithmic.md
  docs/axes/cartesian/time.md
  src/scales/scale.time.js
  test/specs/scale.time.tests.js
Labels: type: chore

#6102 Fix ticks.minor and ticks.major configuration issues
  docs/axes/labelling.md
  src/core/core.scale.js
  src/scales/scale.time.js
  test/specs/global.deprecations.tests.js
  test/specs/scale.time.tests.js
Labels: type: bug

#6177 Normalize angle for index in radialLinear scale
  src/scales/scale.radialLinear.js
  test/context.js
  test/specs/core.tooltip.tests.js
  test/specs/plugin.title.tests.js
  test/specs/scale.radialLinear.tests.js
Labels: type: bug

#6132 Added cubicInterpolationMode and changed fill enum
  docs/charts/line.md
  docs/configuration/elements.md
Labels: type: documentation

#6186 Update doughnut documentation
  docs/charts/doughnut.md
Labels: type: documentation

#6209 Fix missing tooltip value in radar charts
  src/controllers/controller.radar.js
  test/specs/controller.radar.tests.js
Labels: type: bug

#6208 Fill before drawing lines
  src/plugins/plugin.filler.js
  test/fixtures/plugin.filler/fill-line-dataset-border.json
  test/fixtures/plugin.filler/fill-line-dataset-border.png
Labels: type: bug

#6182 Use the appropriate time format for auto tick generation
  src/scales/scale.time.js
  test/specs/scale.time.tests.js
Labels: type: bug

#5961 Fix tick label rotation and layout issues
  src/core/core.scale.js
  test/specs/core.scale.tests.js
Labels: type: bug

#6215 Fix arc border with circumference over 2*PI
  src/elements/element.arc.js
  test/fixtures/controller.doughnut/doughnut-circumference-over-2pi.json
  test/fixtures/controller.doughnut/doughnut-circumference-over-2pi.png
  test/specs/element.arc.tests.js
Labels: type: bug
