Repository chartjs/Chart.js, pull requests merged in 2019-05, with the labels that each got.

#6224 Fix arc size calculation when circumference is under 2PI
  src/controllers/controller.doughnut.js
  test/fixtures/controller.doughnut/doughnut-circumference.json
  test/fixtures/controller.doughnut/doughnut-circumference.png
  test/fixtures/controller.doughnut/pie-circumference.json
  test/fixtures/controller.doughnut/pie-circumference.png
Labels: type: bug

#6238 Fix tooltip title in radar charts
  src/controllers/controller.radar.js
  test/specs/controller.radar.tests.js
Labels: type: bug

#6245 Remove the old slack token used for notifications.
  .travis.yml
Labels: type: infrastructure

#6246 Avoid deprecation warnings in tests
  src/scales/scale.time.js
  test/fixtures/controller.bar/bar-thickness-absolute.json
  test/fixtures/controller.bar/bar-thickness-flex-offset.json
  test/fixtures/controller.bar/bar-thickness-flex-single-reverse.json
  test/fixtures/controller.bar/bar-thickness-flex-single.json
  test/fixtures/controller.bar/bar-thickness-flex.json
  test/fixtures/controller.bar/bar-thickness-max.json
  test/fixtures/controller.bar/bar-thickness-min-interval.json
  test/fixtures/controller.bar/bar-thickness-multiple.json
  test/fixtures/controller.bar/bar-thickness-no-overlap.json
  test/fixtures/controller.bar/bar-thickness-offset.json
  test/fixtures/controller.bar/bar-thickness-reverse.json
  test/fixtures/controller.bar/bar-thickness-single-xy.json
  test/fixtures/controller.bar/bar-thickness-single.json
  test/fixtures/controller.bar/bar-thickness-stacked.json
  test/specs/core.controller.tests.js
  test/specs/scale.time.tests.js
Labels: type: chore

#5999 Implement per-dataset type (default and per-chart) options
  docs/configuration/README.md
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.line.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/controllers/controller.scatter.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.defaults.js
  test/specs/controller.line.tests.js
  test/specs/controller.radar.tests.js
  test/specs/controller.scatter.test.js
  test/specs/core.controller.tests.js
Labels: type: enhancement

#6250 Cache scales
  src/controllers/controller.line.js
Labels: type: chore

#5621 Make legend appearance consistent with chart elements
  docs/configuration/legend.md
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.line.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/core/core.datasetController.js
  src/core/core.element.js
  src/elements/element.arc.js
  src/elements/element.line.js
  src/elements/element.point.js
  src/elements/element.rectangle.js
  src/plugins/plugin.legend.js
  test/specs/plugin.legend.tests.js
Labels: type: enhancement

#6115 Fix overlapping auto-generated ticks on time scale
  src/scales/scale.time.js
  test/specs/scale.time.tests.js
Labels: time scale, type: bug

#6241 Implement layers (z-index) for layout items
  docs/axes/styling.md
  src/core/core.controller.js
  src/core/core.layouts.js
  src/core/core.scale.js
  src/scales/scale.radialLinear.js
  test/fixtures/scale.radialLinear/gridlines-no-z.json
  test/fixtures/scale.radialLinear/gridlines-no-z.png
  test/fixtures/scale.radialLinear/gridlines-z.json
  test/fixtures/scale.radialLinear/gridlines-z.png
  test/specs/core.scale.tests.js
Labels: type: enhancement

#6259 Fix determineUnitForFormatting floating point error
  src/adapters/adapter.moment.js
  src/scales/scale.time.js
  test/specs/scale.time.tests.js
Labels: time scale, type: bug

#6258 Vertical time scale generates too few ticks
  src/scales/scale.time.js
Labels: time scale, type: bug

#6264 Apply offset regardless of min/max setting
  src/scales/scale.time.js
  test/specs/scale.time.tests.js
Labels: time scale, type: bug

#6265 Use tick.major rather than recomputing
  src/scales/scale.time.js
Labels: time scale, type: bug

#6244 Fix data in financial sample
  samples/scales/time/financial.html
Labels: type: documentation

#6279 Treat 0 as a valid point label
  src/scales/scale.radialLinear.js
  test/specs/scale.radialLinear.tests.js
Labels: type: bug

#6280 Fix point label counting in radialLinear scale
  src/scales/scale.radialLinear.js
  test/fixtures/scale.radialLinear/anglelines-disable.json
  test/fixtures/scale.radialLinear/anglelines-disable.png
  test/fixtures/scale.radialLinear/gridlines-disable.json
  test/fixtures/scale.radialLinear/gridlines-disable.png
Labels: type: bug

#6269 Apply lineJoin style at the first point in radar charts
  src/elements/element.line.js
  test/specs/element.line.tests.js
Labels: type: bug

#6285 Keep lines on the left and right edges from being cut
  src/controllers/controller.line.js
  test/fixtures/controller.line/borderJoinStyle/scriptable.png
  test/fixtures/controller.line/borderJoinStyle/value.png
  test/fixtures/controller.line/cubicInterpolationMode/scriptable.png
  test/fixtures/controller.line/cubicInterpolationMode/value.png
Labels: type: bug

#6056 Add support for floating bar chart ([start, end])
  docs/charts/bar.md
  src/controllers/controller.bar.js
  src/core/core.scale.js
  src/scales/scale.linear.js
  src/scales/scale.logarithmic.js
  test/fixtures/controller.bar/floatBar/float-bar-horizontal.json
  test/fixtures/controller.bar/floatBar/float-bar-horizontal.png
  test/fixtures/controller.bar/floatBar/float-bar-stacked-horizontal.json
  test/fixtures/controller.bar/floatBar/float-bar-stacked-horizontal.png
  test/fixtures/controller.bar/floatBar/float-bar-stacked.json
  test/fixtures/controller.bar/floatBar/float-bar-stacked.png
  test/fixtures/controller.bar/floatBar/float-bar.json
  test/fixtures/controller.bar/floatBar/float-bar.png
Labels: type: enhancement

#6282 Treat null as NaN in radialLinear scale
  src/scales/scale.radialLinear.js
  test/fixtures/controller.radar/backgroundColor/indexable.png
  test/fixtures/controller.radar/backgroundColor/scriptable.png
  test/fixtures/controller.radar/backgroundColor/value.png
  test/fixtures/controller.radar/borderColor/indexable.png
  test/fixtures/controller.radar/borderColor/scriptable.png
  test/fixtures/controller.radar/borderColor/value.png
  test/fixtures/controller.radar/borderWidth/indexable.png
  test/fixtures/controller.radar/borderWidth/scriptable.png
  test/fixtures/controller.radar/borderWidth/value.png
  test/fixtures/controller.radar/pointStyle/indexable.png
  test/fixtures/controller.radar/pointStyle/value.png
  test/fixtures/plugin.filler/fill-radar-boundary-end-circular.json
  test/fixtures/plugin.filler/fill-radar-boundary-end.json
  test/fixtures/plugin.filler/fill-radar-boundary-origin-circular.json
  test/fixtures/plugin.filler/fill-radar-boundary-origin-spline.json
  test/fixtures/plugin.filler/fill-radar-boundary-origin.json
  test/fixtures/plugin.filler/fill-radar-boundary-start-circular.json
  test/fixtures/plugin.filler/fill-radar-boundary-start.json
  test/fixtures/plugin.filler/fill-radar-dataset-border.json
  test/fixtures/plugin.filler/fill-radar-dataset-spline.json
  test/fixtures/plugin.filler/fill-radar-dataset.json
Labels: type: bug

#6257 Allow specifying labels in time scale options
  docs/axes/cartesian/time.md
  src/core/core.scale.js
  src/scales/scale.category.js
  src/scales/scale.time.js
  test/specs/scale.time.tests.js
Labels: time scale, type: enhancement

#6288 Fix regression with lineTension
  docs/charts/radar.md
  src/controllers/controller.line.js
  src/controllers/controller.radar.js
Labels: type: bug

#6287 Support rotation for pointStyle image
  src/helpers/helpers.canvas.js
  test/fixtures/element.point/point-style-image.js
  test/fixtures/element.point/point-style-image.png
Labels: type: enhancement
