Repository chartjs/Chart.js, pull requests merged in 2019-03, with the labels that each got.

#6096 Revamp the README.md and add link to the awesome list
  README.md
  docs/SUMMARY.md
  docs/notes/extensions.md
Labels: type: documentation

#6099 Fix document errors related to ticks
  docs/axes/cartesian/README.md
  docs/axes/styling.md
Labels: type: documentation

#6107 Add a note about how to include an example against master
  .github/ISSUE_TEMPLATE/BUG.md
  docs/developers/contributing.md
Labels: type: documentation, type: infrastructure

#6089 Improve timeseries sample
  samples/scales/time/financial.html
Labels: type: documentation

#6105 Optimize the npm package size
  .npmignore
  karma.conf.js
  package.json
  rollup.config.js
  src/index.js
  src/scales/scale.category.js
  src/scales/scale.linear.js
  src/scales/scale.logarithmic.js
  src/scales/scale.radialLinear.js
  src/scales/scale.time.js
Labels: type: infrastructure

#6108 Fix animation regression from 5331
  src/core/core.animations.js
Labels: type: bug

#6100 Properly initialize variables if ticks aren't being displayed
  src/core/core.scale.js
Labels: type: bug

#6113 Tighten check for Moment
  src/adapters/adapter.moment.js
Labels: type: bug

#6112 Fix the missing Chart.Chart (deprecated) alias
  src/index.js
  test/specs/global.deprecations.tests.js
Labels: type: chore

#6122 Correct typo in a comment in test/index.js
  test/index.js
Labels: type: chore

#6127 Keep the previous extensions page link alive
  book.json
  docs/SUMMARY.md
  docs/notes/extensions.md
Labels: type: documentation

#6131 Make decimalPlaces private and update CDN links
  docs/README.md
  docs/getting-started/README.md
  src/core/core.helpers.js
  src/scales/scale.linearbase.js
  test/specs/core.helpers.tests.js
Labels: type: chore

#6139 Add the description of the tooltip alignment options
  docs/configuration/tooltip.md
Labels: type: documentation

#6134 Add docs for the date adapter used by the time scale
  docs/axes/cartesian/time.md
Labels: type: documentation

#6120 Improvements to helpers.almostWhole
  src/core/core.helpers.js
  test/specs/core.helpers.tests.js
Labels: type: bug

#6148 Replace helpers.extend with Object.assign when available or use helpers.merge
  src/helpers/helpers.core.js
Labels: type: enhancement

#6129 Make hover animation work
  src/core/core.element.js
  test/specs/core.element.tests.js
  test/specs/core.tooltip.tests.js
Labels: type: bug

#6141 Implement legend.align: 'start'/'center'/'end'
  docs/configuration/legend.md
  src/plugins/plugin.legend.js
  test/fixtures/plugin.legend/legend-doughnut-bottom-center-mulitiline.json
  test/fixtures/plugin.legend/legend-doughnut-bottom-center-mulitiline.png
  test/fixtures/plugin.legend/legend-doughnut-bottom-center-single.json
  test/fixtures/plugin.legend/legend-doughnut-bottom-center-single.png
  test/fixtures/plugin.legend/legend-doughnut-bottom-end-mulitiline.json
  test/fixtures/plugin.legend/legend-doughnut-bottom-end-mulitiline.png
  test/fixtures/plugin.legend/legend-doughnut-bottom-start-mulitiline.json
  test/fixtures/plugin.legend/legend-doughnut-bottom-start-mulitiline.png
  test/fixtures/plugin.legend/legend-doughnut-left-center-mulitiline.json
  test/fixtures/plugin.legend/legend-doughnut-left-center-mulitiline.png
  test/fixtures/plugin.legend/legend-doughnut-left-center-single.json
  test/fixtures/plugin.legend/legend-doughnut-left-center-single.png
  test/fixtures/plugin.legend/legend-doughnut-left-default-center.json
  test/fixtures/plugin.legend/legend-doughnut-left-default-center.png
  test/fixtures/plugin.legend/legend-doughnut-left-end-mulitiline.json
  test/fixtures/plugin.legend/legend-doughnut-left-end-mulitiline.png
  test/fixtures/plugin.legend/legend-doughnut-left-start-mulitiline.json
  test/fixtures/plugin.legend/legend-doughnut-left-start-mulitiline.png
  test/fixtures/plugin.legend/legend-doughnut-right-center-mulitiline.json
  test/fixtures/plugin.legend/legend-doughnut-right-center-mulitiline.png
  test/fixtures/plugin.legend/legend-doughnut-right-center-single.json
  test/fixtures/plugin.legend/legend-doughnut-right-center-single.png
  test/fixtures/plugin.legend/legend-doughnut-right-default-center.json
  test/fixtures/plugin.legend/legend-doughnut-right-default-center.png
  test/fixtures/plugin.legend/legend-doughnut-right-end-mulitiline.json
  test/fixtures/plugin.legend/legend-doughnut-right-end-mulitiline.png
  test/fixtures/plugin.legend/legend-doughnut-right-start-mulitiline.json
  test/fixtures/plugin.legend/legend-doughnut-right-start-mulitiline.png
  test/fixtures/plugin.legend/legend-doughnut-top-center-mulitiline.json
  test/fixtures/plugin.legend/legend-doughnut-top-center-mulitiline.png
  test/fixtures/plugin.legend/legend-doughnut-top-center-single.json
  test/fixtures/plugin.legend/legend-doughnut-top-center-single.png
  test/fixtures/plugin.legend/legend-doughnut-top-end-mulitiline.json
  test/fixtures/plugin.legend/legend-doughnut-top-end-mulitiline.png
  test/fixtures/plugin.legend/legend-doughnut-top-start-mulitiline.json
  test/fixtures/plugin.legend/legend-doughnut-top-start-mulitiline.png
  test/specs/plugin.legend.tests.js
Labels: type: enhancement

#6119 Demonstrate multiple units on financial timeseries sample
  samples/scales/time/financial.html
Labels: type: documentation
