Repository chartjs/Chart.js, pull requests merged in 2019-12, with the labels that each got.

#6705 Update GitHub Actions CI to include pull requests
  .github/workflows/ci.yml
Labels: type: infrastructure

#6818 Allow axes to be centered on the chart area
  docs/axes/cartesian/README.md
  samples/samples.js
  samples/scales/axis-center-position.html
  src/core/core.controller.js
  src/core/core.layouts.js
  src/core/core.scale.js
  src/scales/scale.category.js
  src/scales/scale.linear.js
  src/scales/scale.logarithmic.js
  src/scales/scale.time.js
  test/fixtures/core.scale/x-axis-position-center.json
  test/fixtures/core.scale/x-axis-position-center.png
  test/fixtures/core.scale/x-axis-position-dynamic.json
  test/fixtures/core.scale/x-axis-position-dynamic.png
  test/fixtures/core.scale/y-axis-position-center.json
  test/fixtures/core.scale/y-axis-position-center.png
  test/fixtures/core.scale/y-axis-position-dynamic.json
  test/fixtures/core.scale/y-axis-position-dynamic.png
  test/specs/scale.category.tests.js
  test/specs/scale.linear.tests.js
  test/specs/scale.logarithmic.tests.js
  test/specs/scale.time.tests.js
Labels: type: enhancement

#6846 Fix rendering of table in tooltip documentation
  docs/configuration/tooltip.md
Labels: type: documentation

#6847 Fix category scale autoSkip
  src/scales/scale.category.js
Labels: type: bug

#6852 (feature) Added separate top and bottom padding for title plugin.
  docs/configuration/title.md
  src/helpers/helpers.options.js
  src/plugins/plugin.title.js
Labels: type: enhancement

#6854 Remove executable bit from tests
  test/specs/core.tooltip.tests.js
  test/specs/scale.time.tests.js
Labels: type: chore

#6860 Remove helpers.where and unnecessary calls to helpers.each
  docs/getting-started/v3-migration.md
  src/controllers/controller.polarArea.js
  src/core/core.datasetController.js
  src/core/core.layouts.js
  src/helpers/index.js
  src/index.js
  src/platforms/platform.dom.js
  src/plugins/plugin.legend.js
  src/scales/scale.radialLinear.js
  test/specs/core.helpers.tests.js
Labels: type: chore

#6845 Rewrite animation logic
  .eslintrc.yml
  docs/configuration/animations.md
  docs/configuration/tooltip.md
  docs/developers/api.md
  docs/developers/charts.md
  docs/developers/updates.md
  docs/general/interactions/README.md
  docs/general/performance.md
  docs/general/responsive.md
  docs/getting-started/v3-migration.md
  samples/animations/delay.html
  samples/animations/drop.html
  samples/animations/loop.html
  samples/charts/bubble.html
  samples/samples.js
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.line.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/core/core.animation.js
  src/core/core.animations.js
  src/core/core.animator.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.element.js
  src/core/core.interaction.js
  src/core/core.plugins.js
  src/core/core.tooltip.js
  src/elements/element.arc.js
  src/elements/element.line.js
  src/elements/element.point.js
  src/elements/element.rectangle.js
  src/helpers/helpers.curve.js
  src/index.js
  src/plugins/plugin.filler.js
  src/plugins/plugin.legend.js
  test/fixtures/controller.line/clip/default-y-max.png
  test/fixtures/controller.line/clip/default-y.png
  test/fixtures/core.tooltip/opacity.js
  test/specs/controller.bar.tests.js
  test/specs/controller.bubble.tests.js
  test/specs/controller.doughnut.tests.js
  test/specs/controller.line.tests.js
  test/specs/controller.polarArea.tests.js
  test/specs/controller.radar.tests.js
  test/specs/controller.scatter.tests.js
  test/specs/core.controller.tests.js
  test/specs/core.element.tests.js
  test/specs/core.interaction.tests.js
  test/specs/core.tooltip.tests.js
  test/specs/element.arc.tests.js
  test/specs/element.point.tests.js
  test/specs/element.rectangle.tests.js
  test/specs/global.defaults.tests.js
  test/specs/helpers.curve.tests.js
  test/specs/plugin.legend.tests.js
  test/utils.js
Labels: type: enhancement

#6865 Alphabetize migration guide
  docs/getting-started/v3-migration.md
Labels: type: documentation
