Repository chartjs/Chart.js, pull requests merged in 2019-10, with the labels that each got.

#6554 Add scale option examples for Radar Chart
  docs/charts/radar.md
Labels: type: documentation

#6268 Implement `dataset.order`
  docs/charts/bar.md
  docs/charts/bubble.md
  docs/charts/line.md
  docs/charts/mixed.md
  docs/charts/polar.md
  docs/charts/radar.md
  docs/charts/scatter.md
  src/controllers/controller.bar.js
  src/controllers/controller.line.js
  src/core/core.controller.js
  src/core/core.interaction.js
  src/core/core.scale.js
  src/core/core.tooltip.js
  src/plugins/plugin.filler.js
  src/plugins/plugin.legend.js
  src/scales/scale.linear.js
  test/fixtures/controller.bar/stacking/order-default.json
  test/fixtures/controller.bar/stacking/order-default.png
  test/fixtures/controller.bar/stacking/order-specified.json
  test/fixtures/controller.bar/stacking/order-specified.png
  test/fixtures/controller.line/fill/order-default.js
  test/fixtures/controller.line/fill/order-default.png
  test/fixtures/controller.line/fill/order.js
  test/fixtures/controller.line/fill/order.png
  test/fixtures/controller.line/stacking/order-default.js
  test/fixtures/controller.line/stacking/order-default.png
  test/fixtures/controller.line/stacking/order-specified.js
  test/fixtures/controller.line/stacking/order-specified.png
  test/specs/core.tooltip.tests.js
  test/specs/plugin.legend.tests.js
Labels: type: enhancement

#6247 Remove duplicate scale building
  src/core/core.controller.js
Labels: type: chore

#6585 Add a note to the perf documentation about rotation
  docs/general/performance.md
Labels: type: documentation

#6586 Fix sampleSize option
  src/core/core.scale.js
Labels: type: bug

#6584 Fix autoskip for first segment of chart
  src/core/core.scale.js
Labels: type: bug

#6556 Inject styles into Shadow DOM when inside Shadow DOM (#5763)
  src/platforms/platform.dom.js
Labels: type: bug

#6613 Add link to performance documentation
  docs/general/README.md
Labels: type: documentation

#6227 Limit onClick to chartArea
  src/core/core.controller.js
Labels: breaking change

#6605 Remove undocumented "custom" feature
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.line.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/core/core.datasetController.js
  test/specs/controller.bar.tests.js
  test/specs/controller.bubble.tests.js
  test/specs/controller.doughnut.tests.js
  test/specs/controller.line.tests.js
  test/specs/controller.polarArea.tests.js
  test/specs/controller.radar.tests.js
Labels: breaking change

#6607 Remove deprecated helpers
  src/core/core.helpers.js
  src/core/core.ticks.js
  src/helpers/helpers.canvas.js
  src/helpers/helpers.core.js
  src/helpers/helpers.easing.js
  src/helpers/helpers.math.js
  src/platforms/platform.dom.js
  test/specs/core.helpers.tests.js
  test/specs/global.deprecations.tests.js
Labels: breaking change

#6606 Remove xLabel and yLabel from tooltip and chart and scales from element
  docs/configuration/tooltip.md
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.line.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/controllers/controller.scatter.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.tooltip.js
  src/elements/element.arc.js
  src/elements/element.line.js
  src/elements/element.point.js
  src/elements/element.rectangle.js
  src/plugins/plugin.filler.js
  test/specs/controller.bar.tests.js
  test/specs/controller.line.tests.js
  test/specs/core.tooltip.tests.js
  test/specs/element.line.tests.js
  test/specs/element.point.tests.js
Labels: breaking change

#6521 Add label alignment option to axis label title
  docs/axes/labelling.md
  src/core/core.scale.js
Labels: type: enhancement

#6616 Time scale: return time from getValueForPixel
  src/adapters/adapter.moment.js
  src/core/core.adapters.js
  src/scales/scale.time.js
  test/specs/scale.time.tests.js
Labels: breaking change, type: infrastructure

#6621 Remove mergeTicksOptions
  src/core/core.controller.js
  src/core/core.scale.js
  src/scales/scale.time.js
Labels: breaking change

#6624 Remove deprecated code from animations and core
  src/core/core.animation.js
  src/core/core.controller.js
  test/specs/core.tooltip.tests.js
  test/specs/scale.time.tests.js
Labels: breaking change

#6622 Remove deprecated code from time scale and bar chart
  package-lock.json
  src/controllers/controller.bar.js
  src/scales/scale.time.js
  test/specs/controller.bar.tests.js
  test/specs/scale.time.tests.js
Labels: breaking change

#6623 Remove deprecated code from index.js
  src/index.js
  test/.eslintrc.yml
  test/specs/plugin.title.tests.js
Labels: breaking change

#6625 Remove deprecated interaction modes
  docs/general/interactions/modes.md
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.line.js
  src/controllers/controller.scatter.js
  src/core/core.controller.js
  src/core/core.interaction.js
  test/specs/controller.line.tests.js
  test/specs/core.controller.tests.js
  test/specs/core.tooltip.tests.js
Labels: breaking change

#6639 Start v3 migration guide
  docs/SUMMARY.md
  docs/getting-started/v3-migration.md
  src/helpers/helpers.easing.js
Labels: type: documentation

#6638 Remove deprecated userCallback
  src/core/core.scale.js
  src/scales/scale.time.js
Labels: breaking change

#6641 Use `document` when `getRootNode` is unsupported
  src/platforms/platform.dom.js
Labels: type: bug

#6571 Adding title for the axes
  samples/samples.js
  samples/scales/axes-labels.html
Labels: type: documentation
