Repository chartjs/Chart.js, pull requests merged in 2019-06, with the labels that each got.

#6291 Assign unique scale IDs
  src/core/core.controller.js
  test/specs/core.controller.tests.js
Labels: type: bug

#6321 Update dataset metadata when axisID changes
  src/core/core.datasetController.js
  test/specs/core.datasetController.tests.js
Labels: type: bug

#6307 [performance] faster major tick calculation
  src/scales/scale.time.js
Labels: time scale

#6323 Support object values for bar charts
  src/scales/scale.category.js
  test/specs/scale.category.tests.js
Labels: type: enhancement

#6304 Refactor core.layouts
  src/core/core.layouts.js
  src/core/core.scale.js
  src/scales/scale.category.js
  src/scales/scale.linear.js
  src/scales/scale.logarithmic.js
  src/scales/scale.time.js
  test/specs/core.layouts.tests.js
  test/specs/scale.linear.tests.js
  test/specs/scale.time.tests.js
Labels: type: chore

#6328 Fix getValueForPixel in time scale
  src/scales/scale.time.js
  test/specs/scale.time.tests.js
Labels: type: bug

#6293 Correct descriptions on ticks.display and add pointLabels.display
  docs/axes/radial/linear.md
  docs/axes/styling.md
Labels: type: documentation

#6347 Render charts only once in time scale tests
  test/specs/scale.time.tests.js
Labels: type: infrastructure
