Repository chartjs/Chart.js, pull requests merged in 2019-02, with the labels that each got.

#6030 Update doc on label types for TooltipItem
  docs/configuration/tooltip.md
  src/core/core.tooltip.js
  test/specs/core.tooltip.tests.js
Labels: type: documentation

#6032 Replace deprecated gulp-util and remove unused watchify
  gulpfile.js
  package.json
Labels: type: infrastructure

#6021 Fix padding of horizontal axes when labels are rotated
  src/core/core.layouts.js
Labels: type: bug

#6040 Remove unused eslint directive
  src/scales/scale.time.js
Labels: type: chore

#6027 Provide a rectangle getArea implementation for horizontal bars
  src/elements/element.rectangle.js
  test/specs/element.rectangle.tests.js
Labels: type: bug

#6038 Fix duplicate anchor
  docs/axes/README.md
  docs/axes/cartesian/README.md
  docs/charts/bar.md
  docs/charts/line.md
  docs/developers/README.md
  docs/developers/contributing.md
  docs/getting-started/installation.md
Labels: type: documentation

#6053 Fix typo in broken url
  docs/charts/line.md
Labels: type: documentation

#6043 Autoskip cleanup
  src/core/core.scale.js
Labels: type: chore

#6054 Simple spelling error fix.
  docs/axes/radial/linear.md
Labels: type: documentation

#6041 Radar scriptable options
  docs/charts/radar.md
  src/controllers/controller.line.js
  src/controllers/controller.radar.js
  test/fixtures/controller.radar/backgroundColor/indexable.js
  test/fixtures/controller.radar/backgroundColor/indexable.png
  test/fixtures/controller.radar/backgroundColor/scriptable.js
  test/fixtures/controller.radar/backgroundColor/scriptable.png
  test/fixtures/controller.radar/backgroundColor/value.js
  test/fixtures/controller.radar/backgroundColor/value.png
  test/fixtures/controller.radar/borderColor/indexable.js
  test/fixtures/controller.radar/borderColor/indexable.png
  test/fixtures/controller.radar/borderColor/scriptable.js
  test/fixtures/controller.radar/borderColor/scriptable.png
  test/fixtures/controller.radar/borderColor/value.js
  test/fixtures/controller.radar/borderColor/value.png
  test/fixtures/controller.radar/borderWidth/indexable.js
  test/fixtures/controller.radar/borderWidth/indexable.png
  test/fixtures/controller.radar/borderWidth/scriptable.js
  test/fixtures/controller.radar/borderWidth/scriptable.png
  test/fixtures/controller.radar/borderWidth/value.js
  test/fixtures/controller.radar/borderWidth/value.png
  test/fixtures/controller.radar/pointStyle/indexable.js
  test/fixtures/controller.radar/pointStyle/indexable.png
  test/fixtures/controller.radar/pointStyle/scriptable.js
  test/fixtures/controller.radar/pointStyle/scriptable.png
  test/fixtures/controller.radar/pointStyle/value.js
  test/fixtures/controller.radar/pointStyle/value.png
  test/fixtures/controller.radar/radius/indexable.js
  test/fixtures/controller.radar/radius/indexable.png
  test/fixtures/controller.radar/radius/scriptable.js
  test/fixtures/controller.radar/radius/scriptable.png
  test/fixtures/controller.radar/radius/value.js
  test/fixtures/controller.radar/radius/value.png
  test/fixtures/controller.radar/rotation/indexable.js
  test/fixtures/controller.radar/rotation/indexable.png
  test/fixtures/controller.radar/rotation/scriptable.js
  test/fixtures/controller.radar/rotation/scriptable.png
  test/fixtures/controller.radar/rotation/value.js
  test/fixtures/controller.radar/rotation/value.png
  test/specs/controller.radar.tests.js
Labels: type: enhancement

#6061 Fix randomly failing tooltip test
  test/specs/core.tooltip.tests.js
Labels: type: infrastructure

#6006 Enhance legend label color point when usePointStyle is true
  docs/configuration/legend.md
  src/plugins/plugin.legend.js
Labels: type: bug

#6033 Use lowercase for primitives in jsdocs
  .gitignore
  src/controllers/controller.bar.js
  src/controllers/controller.horizontalBar.js
  src/core/core.animations.js
  src/core/core.controller.js
  src/core/core.helpers.js
  src/core/core.interaction.js
  src/core/core.layouts.js
  src/core/core.plugins.js
  src/core/core.scale.js
  src/core/core.ticks.js
  src/core/core.tooltip.js
  src/helpers/helpers.canvas.js
  src/helpers/helpers.core.js
  src/helpers/helpers.options.js
  src/platforms/platform.dom.js
  src/platforms/platform.js
  src/plugins/plugin.legend.js
  src/scales/scale.linearbase.js
  src/scales/scale.logarithmic.js
  src/scales/scale.time.js
Labels: type: chore

#6060 Handle a frozen `dataset.data` array.
  src/core/core.datasetController.js
  test/specs/core.datasetController.tests.js
Labels: type: bug

#6063 fix resize on rtl page
  src/platforms/platform.dom.css
  test/specs/core.controller.tests.js
Labels: type: bug

#6042 Add examples of scriptable charts
  samples/samples.js
  samples/scriptable/line.html
  samples/scriptable/pie.html
  samples/scriptable/polar.html
  samples/scriptable/radar.html
Labels: type: documentation

#6070 Add crosshair plugin to extensions page
  docs/notes/extensions.md
Labels: type: documentation

#6019 Time scale performance improvement
  src/adapters/adapter.moment.js
  src/core/core.adapters.js
  src/scales/scale.time.js
  test/specs/scale.time.tests.js
Labels: type: enhancement

#6079 Improve autoSkip documentation
  docs/axes/cartesian/README.md
Labels: type: documentation

#6081 Add a link to chartjs-plugin-rough to extensions.md
  docs/notes/extensions.md
Labels: type: documentation

#6016 Initialize date adapter with chart options
  docs/axes/cartesian/time.md
  docs/getting-started/integration.md
  src/adapters/adapter.moment.js
  src/core/core.adapters.js
  src/scales/scale.time.js
  test/specs/scale.time.tests.js
Labels: type: enhancement

#6059 Add onLeave callback to legend
  samples/legend/callbacks.html
  samples/samples.js
  src/plugins/plugin.legend.js
  test/specs/plugin.legend.tests.js
Labels: type: enhancement

#6058 Ignore invalid log scale min and max
  src/scales/scale.logarithmic.js
  test/specs/scale.logarithmic.tests.js
Labels: type: bug

#6088 Add onLeave to legend config docs
  docs/configuration/legend.md
Labels: type: documentation

#6073 Add instructions for image-based tests to the contributors guide
  docs/developers/contributing.md
Labels: type: documentation

#5951 Pie doughnut dataset weight
  docs/charts/doughnut.md
  src/controllers/controller.doughnut.js
  test/fixtures/controller.doughnut/doughnut-weight.json
  test/fixtures/controller.doughnut/doughnut-weight.png
  test/fixtures/controller.doughnut/pie-weight.json
  test/fixtures/controller.doughnut/pie-weight.png
Labels: type: enhancement
