Repository chartjs/Chart.js, pull requests merged in 2019-01, with the labels that each got.

#5938 Improve tick generation for linear scales
  src/scales/scale.linear.js
  src/scales/scale.linearbase.js
  src/scales/scale.logarithmic.js
  src/scales/scale.radialLinear.js
  test/specs/scale.linear.tests.js
  test/specs/scale.radialLinear.tests.js
Labels: type: enhancement

#5947 cast getRightValue to number
  src/controllers/controller.bar.js
  test/specs/controller.bar.tests.js
Labels: type: bug

#5933 Fix time scale ticks.reverse issue
  src/controllers/controller.bar.js
  src/scales/scale.time.js
  test/fixtures/controller.bar/bar-thickness-flex-single-reverse.json
  test/fixtures/controller.bar/bar-thickness-flex-single-reverse.png
  test/fixtures/controller.bar/bar-thickness-flex-single.json
  test/fixtures/controller.bar/bar-thickness-flex-single.png
  test/fixtures/controller.bar/bar-thickness-reverse.json
  test/fixtures/controller.bar/bar-thickness-reverse.png
  test/specs/scale.time.tests.js
Labels: type: bug

#5331 #5329 Animation duration is not consistent across browsers
  src/core/core.animations.js
  src/core/core.controller.js
  test/specs/core.controller.tests.js
Labels: type: bug

#5953 Cleanup scales export for better import strategy
  src/chart.js
  src/controllers/index.js
  src/scales/index.js
  src/scales/scale.category.js
  src/scales/scale.linear.js
  src/scales/scale.linearbase.js
  src/scales/scale.logarithmic.js
  src/scales/scale.radialLinear.js
  src/scales/scale.time.js
  test/specs/global.deprecations.tests.js
Labels: type: chore

#5958 Use `Chart.min.js` in samples
  samples/advanced/data-labelling.html
  samples/advanced/progress-bar.html
  samples/charts/area/line-boundaries.html
  samples/charts/area/line-datasets.html
  samples/charts/area/line-stacked.html
  samples/charts/area/radar.html
  samples/charts/bar/horizontal.html
  samples/charts/bar/multi-axis.html
  samples/charts/bar/stacked-group.html
  samples/charts/bar/stacked.html
  samples/charts/bar/vertical.html
  samples/charts/bubble.html
  samples/charts/combo-bar-line.html
  samples/charts/doughnut.html
  samples/charts/line/basic.html
  samples/charts/line/interpolation-modes.html
  samples/charts/line/line-styles.html
  samples/charts/line/multi-axis.html
  samples/charts/line/point-sizes.html
  samples/charts/line/point-styles.html
  samples/charts/line/skip-points.html
  samples/charts/line/stepped.html
  samples/charts/pie.html
  samples/charts/polar-area.html
  samples/charts/radar-skip-points.html
  samples/charts/radar.html
  samples/charts/scatter/basic.html
  samples/charts/scatter/multi-axis.html
  samples/legend/point-style.html
  samples/legend/positioning.html
  samples/samples.js
  samples/scales/filtering-labels.html
  samples/scales/gridlines-display.html
  samples/scales/gridlines-style.html
  samples/scales/linear/min-max-suggested.html
  samples/scales/linear/min-max.html
  samples/scales/linear/step-size.html
  samples/scales/logarithmic/line.html
  samples/scales/logarithmic/scatter.html
  samples/scales/multiline-labels.html
  samples/scales/non-numeric-y.html
  samples/scales/time/combo.html
  samples/scales/time/financial.html
  samples/scales/time/line-point-data.html
  samples/scales/time/line.html
  samples/scales/toggle-scale-type.html
  samples/scriptable/bar.html
  samples/scriptable/bubble.html
  samples/tooltips/border.html
  samples/tooltips/callbacks.html
  samples/tooltips/custom-line.html
  samples/tooltips/custom-pie.html
  samples/tooltips/custom-points.html
  samples/tooltips/interactions.html
  samples/tooltips/positioning.html
Labels: type: documentation

#5925 Align title, body and footer inside tooltip
  src/core/core.tooltip.js
  test/specs/core.tooltip.tests.js
Labels: type: bug

#5965 Refactoring using helpers.options.resolve
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.line.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.scale.js
  src/core/core.tooltip.js
  src/elements/element.line.js
  src/elements/element.point.js
  src/helpers/helpers.options.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.title.js
  src/scales/scale.logarithmic.js
  src/scales/scale.radialLinear.js
  src/scales/scale.time.js
Labels: type: chore

#5948 Fix generateTicks when working with tiny numbers
  src/scales/scale.linearbase.js
  test/specs/scale.linear.tests.js
Labels: type: bug

#5968 fixed contribution docs
  docs/developers/contributing.md
Labels: type: documentation

#5967 Updated controller.scatter.test.js to test default tooltip callbacks
  test/specs/controller.scatter.test.js
Labels: type: chore

#5970 Remove unused parameter in removeResizeListener invocation
  src/platforms/platform.dom.js
Labels: type: chore

#5969 Make the main controller importable
  src/chart.js
  src/core/core.controller.js
  src/core/core.defaults.js
  src/core/core.js
  src/core/core.layouts.js
  test/specs/global.deprecations.tests.js
Labels: type: chore

#5966 Doughnut scriptable options
  docs/charts/bar.md
  docs/charts/bubble.md
  docs/charts/doughnut.md
  src/controllers/controller.doughnut.js
  test/fixtures/controller.doughnut/backgroundColor/indexable.js
  test/fixtures/controller.doughnut/backgroundColor/indexable.png
  test/fixtures/controller.doughnut/backgroundColor/scriptable.js
  test/fixtures/controller.doughnut/backgroundColor/scriptable.png
  test/fixtures/controller.doughnut/backgroundColor/value.js
  test/fixtures/controller.doughnut/backgroundColor/value.png
  test/fixtures/controller.doughnut/borderAlign/indexable.js
  test/fixtures/controller.doughnut/borderAlign/indexable.png
  test/fixtures/controller.doughnut/borderAlign/scriptable.js
  test/fixtures/controller.doughnut/borderAlign/scriptable.png
  test/fixtures/controller.doughnut/borderAlign/value.js
  test/fixtures/controller.doughnut/borderAlign/value.png
  test/fixtures/controller.doughnut/borderColor/indexable.js
  test/fixtures/controller.doughnut/borderColor/indexable.png
  test/fixtures/controller.doughnut/borderColor/scriptable.js
  test/fixtures/controller.doughnut/borderColor/scriptable.png
  test/fixtures/controller.doughnut/borderColor/value.js
  test/fixtures/controller.doughnut/borderColor/value.png
  test/fixtures/controller.doughnut/borderWidth/indexable.js
  test/fixtures/controller.doughnut/borderWidth/indexable.png
  test/fixtures/controller.doughnut/borderWidth/scriptable.js
  test/fixtures/controller.doughnut/borderWidth/scriptable.png
  test/fixtures/controller.doughnut/borderWidth/value.js
  test/fixtures/controller.doughnut/borderWidth/value.png
  test/specs/controller.doughnut.tests.js
Labels: type: enhancement

#5975 Fix typo / grammar in docs
  docs/general/responsive.md
Labels: type: documentation

#5960 Implement adapter to abstract date/time features
  src/adapters/adapter.moment.js
  src/adapters/index.js
  src/chart.js
  src/core/core.adapters.js
  src/scales/scale.time.js
  test/specs/scale.time.tests.js
Labels: type: enhancement

#5976 Polar area scriptable options
  docs/charts/polar.md
  src/controllers/controller.doughnut.js
  src/controllers/controller.polarArea.js
  src/elements/element.arc.js
  test/fixtures/controller.polarArea/backgroundColor/indexable-dataset.js
  test/fixtures/controller.polarArea/backgroundColor/indexable-dataset.png
  test/fixtures/controller.polarArea/backgroundColor/indexable-element-options.js
  test/fixtures/controller.polarArea/backgroundColor/indexable-element-options.png
  test/fixtures/controller.polarArea/backgroundColor/scriptable-dataset.js
  test/fixtures/controller.polarArea/backgroundColor/scriptable-dataset.png
  test/fixtures/controller.polarArea/backgroundColor/scriptable-element-options.js
  test/fixtures/controller.polarArea/backgroundColor/scriptable-element-options.png
  test/fixtures/controller.polarArea/backgroundColor/value-dataset.js
  test/fixtures/controller.polarArea/backgroundColor/value-dataset.png
  test/fixtures/controller.polarArea/backgroundColor/value-element-options.js
  test/fixtures/controller.polarArea/backgroundColor/value-element-options.png
  test/fixtures/controller.polarArea/borderAlign/indexable-dataset.js
  test/fixtures/controller.polarArea/borderAlign/indexable-dataset.png
  test/fixtures/controller.polarArea/borderAlign/indexable-element-options.js
  test/fixtures/controller.polarArea/borderAlign/indexable-element-options.png
  test/fixtures/controller.polarArea/borderAlign/scriptable-dataset.js
  test/fixtures/controller.polarArea/borderAlign/scriptable-dataset.png
  test/fixtures/controller.polarArea/borderAlign/scriptable-element-options.js
  test/fixtures/controller.polarArea/borderAlign/scriptable-element-options.png
  test/fixtures/controller.polarArea/borderAlign/value-dataset.js
  test/fixtures/controller.polarArea/borderAlign/value-dataset.png
  test/fixtures/controller.polarArea/borderAlign/value-element-options.js
  test/fixtures/controller.polarArea/borderAlign/value-element-options.png
  test/fixtures/controller.polarArea/borderColor/indexable-dataset.js
  test/fixtures/controller.polarArea/borderColor/indexable-dataset.png
  test/fixtures/controller.polarArea/borderColor/indexable-element-options.js
  test/fixtures/controller.polarArea/borderColor/indexable-element-options.png
  test/fixtures/controller.polarArea/borderColor/scriptable-dataset.js
  test/fixtures/controller.polarArea/borderColor/scriptable-dataset.png
  test/fixtures/controller.polarArea/borderColor/scriptable-element-options.js
  test/fixtures/controller.polarArea/borderColor/scriptable-element-options.png
  test/fixtures/controller.polarArea/borderColor/value-dataset.js
  test/fixtures/controller.polarArea/borderColor/value-dataset.png
  test/fixtures/controller.polarArea/borderColor/value-element-options.js
  test/fixtures/controller.polarArea/borderColor/value-element-options.png
  test/fixtures/controller.polarArea/borderWidth/indexable-dataset.js
  test/fixtures/controller.polarArea/borderWidth/indexable-dataset.png
  test/fixtures/controller.polarArea/borderWidth/indexable-element-options.js
  test/fixtures/controller.polarArea/borderWidth/indexable-element-options.png
  test/fixtures/controller.polarArea/borderWidth/scriptable-dataset.js
  test/fixtures/controller.polarArea/borderWidth/scriptable-dataset.png
  test/fixtures/controller.polarArea/borderWidth/scriptable-element-options.js
  test/fixtures/controller.polarArea/borderWidth/scriptable-element-options.png
  test/fixtures/controller.polarArea/borderWidth/value-dataset.js
  test/fixtures/controller.polarArea/borderWidth/value-dataset.png
  test/fixtures/controller.polarArea/borderWidth/value-element-options.js
  test/fixtures/controller.polarArea/borderWidth/value-element-options.png
  test/specs/controller.polarArea.tests.js
Labels: type: enhancement

#5974 Added note about maintainAspectRatio
  docs/general/responsive.md
Labels: type: documentation

#5962 Update contributors guide and issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/BUG.md
  .github/ISSUE_TEMPLATE/DOCS.md
  .github/ISSUE_TEMPLATE/FEATURE.md
  .github/ISSUE_TEMPLATE/SUPPORT.md
  docs/developers/contributing.md
Labels: type: documentation

#5982 Remove date auto type conversions
  src/adapters/adapter.moment.js
  src/scales/scale.time.js
Labels: type: enhancement

#5994 _resolveElementPoint utility for triggerMouseEvent
  test/specs/controller.polarArea.tests.js
  test/utils.js
Labels: type: chore

#6007 stop drawing radialLinear scale twice
  src/core/core.controller.js
  test/fixtures/scale.radialLinear/border-dash.png
  test/fixtures/scale.radialLinear/circular-border-dash.png
  test/fixtures/scale.radialLinear/indexable-gridlines.png
Labels: type: bug

#6013 set pointBackgroundColor in radar sample
  samples/charts/radar.html
Labels: type: bug, type: documentation

#6017 Fix typo in comment
  test/utils.js
Labels: type: chore

#6020 Fix typos and minor doc issues
  docs/README.md
  docs/axes/README.md
  docs/axes/cartesian/README.md
  docs/axes/cartesian/category.md
  docs/axes/cartesian/linear.md
  docs/axes/cartesian/logarithmic.md
  docs/axes/cartesian/time.md
  docs/axes/labelling.md
  docs/axes/radial/README.md
  docs/axes/radial/linear.md
  docs/axes/styling.md
  docs/charts/area.md
  docs/charts/bar.md
  docs/charts/bubble.md
  docs/charts/doughnut.md
  docs/charts/line.md
  docs/charts/mixed.md
  docs/charts/polar.md
  docs/charts/radar.md
  docs/charts/scatter.md
  docs/configuration/README.md
  docs/configuration/animations.md
  docs/configuration/elements.md
  docs/configuration/layout.md
  docs/configuration/legend.md
  docs/configuration/title.md
  docs/configuration/tooltip.md
  docs/developers/api.md
  docs/developers/axes.md
  docs/developers/charts.md
  docs/developers/contributing.md
  docs/developers/plugins.md
  docs/developers/updates.md
  docs/general/accessibility.md
  docs/general/colors.md
  docs/general/device-pixel-ratio.md
  docs/general/fonts.md
  docs/general/interactions/README.md
  docs/general/interactions/events.md
  docs/general/interactions/modes.md
  docs/general/responsive.md
  docs/getting-started/README.md
  docs/getting-started/installation.md
  docs/getting-started/integration.md
  docs/getting-started/usage.md
  docs/notes/README.md
  docs/notes/comparison.md
  docs/notes/extensions.md
  docs/notes/license.md
Labels: type: documentation

#6005 Common logic for resolving element options
  src/controllers/controller.line.js
Labels: type: chore

#6022 Deprecate configMerge and scaleMerge helpers
  src/core/core.controller.js
  src/core/core.helpers.js
  src/helpers/helpers.core.js
  test/specs/core.controller.tests.js
  test/specs/core.helpers.tests.js
  test/specs/global.deprecations.tests.js
Labels: type: chore

#5978 Make moment optional from our UMD builds
  docs/getting-started/integration.md
  package.json
  rollup.config.js
  rollup.plugins.js
Labels: type: enhancement, type: infrastructure

#5996 Replace tooltip item xLabel and yLabel with label and value
  docs/configuration/tooltip.md
  src/controllers/controller.horizontalBar.js
  src/core/core.tooltip.js
Labels: type: bug
