Repository chartjs/Chart.js, pull requests merged in 2020-03, with the labels that each got.

#7156 Use global element hidden status for Pie charts
  docs/developers/api.md
  docs/getting-started/v3-migration.md
  src/controllers/controller.doughnut.js
  src/controllers/controller.polarArea.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.element.js
  test/specs/core.controller.tests.js
  test/specs/global.defaults.tests.js
Labels: type: enhancement

#7171 Remove unused constructor parameter
  src/controllers/controller.bubble.js
  src/core/core.element.js
Labels: type: chore

#7168 Shorten imports
  src/core/core.animations.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.interaction.js
Labels: type: chore

#7170 Alphabetize element default options
  src/elements/element.arc.js
  src/elements/element.line.js
  src/elements/element.point.js
Labels: type: chore

#7177 Make update_latest work with alpha, beta, etc.
  scripts/deploy.sh
Labels: type: infrastructure

#7175 Add tests for rendering to offscreen canvas
  karma.conf.js
  package-lock.json
  package.json
  test/BasicChartWebWorker.js
  test/fixtures/controller.line/point-style-offscreen-canvas.json
  test/fixtures/controller.line/point-style-offscreen-canvas.png
  test/specs/platform.basic.tests.js
  test/specs/platform.dom.tests.js
  test/utils.js
Labels: type: chore

#6995 Add tooltip boxWidth and boxHeight options
  docs/configuration/tooltip.md
  src/plugins/plugin.tooltip.js
Labels: type: enhancement

#7183 Bump package version for first alpha release of v3
  package.json
Labels: type: chore

#7190 Travis deploy provider uses a different syntax for conditional releases
  .travis.yml
Labels: type: infrastructure

#7196 Update running animations
  src/core/core.animation.js
  src/core/core.animations.js
  src/core/core.controller.js
Labels: type: bug

#7212 Cleaner handling of fitting no ticks
  src/core/core.scale.js
Labels: type: chore

#7211 Fix filterBetween
  src/helpers/helpers.collection.js
  src/scales/scale.time.js
  test/specs/helpers.collection.tests.js
Labels: type: bug

#7224 Fix event position in shadow dom
  src/helpers/helpers.dom.js
Labels: type: bug

#7218 Improve migration guide for innerRadius/outerRadius
  docs/getting-started/v3-migration.md
Labels: type: documentation

#7225 getPixelForTick cleanup
  src/core/core.scale.js
  src/scales/scale.category.js
  src/scales/scale.linear.js
  src/scales/scale.logarithmic.js
  src/scales/scale.time.js
Labels: type: chore

#7233 Update dependencies
  package-lock.json
  package.json
Labels: type: chore

#7229 Remove unused method parameter
  src/core/core.scale.js
Labels: type: chore
