Repository chartjs/Chart.js, pull requests merged in 2020-01, with the labels that each got.

#6892 Linear scale: use suggested limits as defaults
  src/scales/scale.linear.js
  test/specs/scale.linear.tests.js
Labels: type: bug

#6897 Update documentation of `order`
  docs/charts/bar.md
  docs/charts/bubble.md
  docs/charts/line.md
  docs/charts/mixed.md
  docs/configuration/legend.md
Labels: type: bug, type: documentation

#6883 Enable override settings for the axis border
  docs/axes/styling.md
  src/core/core.scale.js
  test/fixtures/core.scale/cartesian-axis-border-settings.json
  test/fixtures/core.scale/cartesian-axis-border-settings.png
Labels: type: enhancement

#6887 Remove HTML legend that is mostly unsupported.
  docs/configuration/legend.md
  docs/developers/api.md
  docs/getting-started/v3-migration.md
  src/controllers/controller.doughnut.js
  src/controllers/controller.polarArea.js
  src/core/core.controller.js
  src/plugins/plugin.legend.js
  test/specs/global.defaults.tests.js
Labels: breaking change

#6893 Remove global from defaults
  docs/charts/line.md
  docs/charts/radar.md
  docs/configuration/README.md
  docs/configuration/animations.md
  docs/configuration/elements.md
  docs/configuration/layout.md
  docs/configuration/legend.md
  docs/configuration/title.md
  docs/configuration/tooltip.md
  docs/developers/charts.md
  docs/general/colors.md
  docs/general/fonts.md
  docs/general/interactions/README.md
  docs/getting-started/v3-migration.md
  samples/animations/loop.html
  samples/tooltips/custom-line.html
  samples/tooltips/custom-pie.html
  src/controllers/controller.bar.js
  src/controllers/controller.horizontalBar.js
  src/controllers/controller.scatter.js
  src/core/core.animations.js
  src/core/core.controller.js
  src/core/core.defaults.js
  src/core/core.layouts.js
  src/core/core.plugins.js
  src/core/core.scale.js
  src/core/core.tooltip.js
  src/elements/element.arc.js
  src/elements/element.line.js
  src/elements/element.point.js
  src/elements/element.rectangle.js
  src/helpers/helpers.options.js
  src/plugins/plugin.filler.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.title.js
  src/scales/scale.logarithmic.js
  src/scales/scale.radialLinear.js
  src/scales/scale.time.js
  test/specs/controller.bar.tests.js
  test/specs/controller.bubble.tests.js
  test/specs/controller.line.tests.js
  test/specs/controller.radar.tests.js
  test/specs/core.controller.tests.js
  test/specs/core.plugin.tests.js
  test/specs/core.tooltip.tests.js
  test/specs/helpers.options.tests.js
  test/specs/plugin.legend.tests.js
  test/specs/plugin.title.tests.js
  test/specs/scale.logarithmic.tests.js
  test/utils.js
Labels: breaking change, type: infrastructure

#6901 #5573 Link PolarArea chart docs to radial axis docs
  docs/charts/polar.md
Labels: type: documentation

#6910 Remove minSize
  docs/getting-started/v3-migration.md
  src/core/core.scale.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.title.js
  test/specs/plugin.title.tests.js
Labels: breaking change

#6917 Bar chart defaults to begin at zero
  src/controllers/controller.bar.js
  test/fixtures/controller.bar/bar-default-begin-at-zero.js
  test/fixtures/controller.bar/bar-default-begin-at-zero.png
  test/specs/controller.bar.tests.js
  test/specs/scale.linear.tests.js
Labels: breaking change

#6919 Add multi series pie example
  samples/charts/multi-series-pie.html
  samples/samples.js
Labels: type: documentation

#6918 Update tooltip docs with working example
  docs/configuration/tooltip.md
Labels: type: documentation

#6927 Improve calculation for number of ticks that can fit
  src/core/core.scale.js
  src/scales/scale.time.js
  test/specs/scale.time.tests.js
Labels: type: bug

#6935 Switch most requires to imports
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.horizontalBar.js
  src/controllers/controller.line.js
  src/controllers/controller.pie.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/controllers/controller.scatter.js
  src/controllers/index.js
  src/core/core.animation.js
  src/core/core.animator.js
  src/core/core.datasetController.js
  src/core/core.layouts.js
  src/core/core.plugins.js
  src/core/core.scale.js
  src/core/core.scaleService.js
  src/core/core.ticks.js
  src/core/core.tooltip.js
  src/index.js
  src/platforms/platform.dom.js
  src/platforms/platform.js
  src/plugins/index.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.title.js
Labels: type: infrastructure

#6937 Fix broken config in log scatter sample
  samples/scales/logarithmic/scatter.html
Labels: type: documentation

#6945 Account for hoverRadius in Point.size()
  src/elements/element.point.js
  test/fixtures/controller.line/clip/default-y-max.png
  test/fixtures/controller.line/clip/default-y.png
Labels: type: bug

#6933 Try beta Chrome
  .travis.yml
Labels: type: infrastructure

#6925 Re-parse existing elements when data is replaced
  src/core/core.datasetController.js
  test/specs/core.datasetController.tests.js
Labels: type: bug

#6787 Add stroke lines option around ticks to improve readability
  docs/axes/styling.md
  src/core/core.scale.js
  test/context.js
  test/specs/scale.category.tests.js
  test/specs/scale.linear.tests.js
  test/specs/scale.logarithmic.tests.js
  test/specs/scale.radialLinear.tests.js
  test/specs/scale.time.tests.js
Labels: type: enhancement

#6954 waitForResize before resizing
  test/specs/core.controller.tests.js
  test/specs/platform.dom.tests.js
Labels: type: infrastructure

#6903 Fix log scale calculations
  docs/getting-started/v3-migration.md
  src/core/core.datasetController.js
  src/core/core.scale.js
  src/scales/scale.logarithmic.js
  test/fixtures/controller.bar/stacking/logarithmic-strings.png
  test/fixtures/controller.bar/stacking/logarithmic.png
  test/specs/scale.logarithmic.tests.js
Labels: breaking change

#6955 Move location of dataset options
  docs/configuration/README.md
  docs/developers/charts.md
  docs/getting-started/v3-migration.md
  src/controllers/controller.bar.js
  src/controllers/controller.horizontalBar.js
  src/controllers/controller.scatter.js
  src/core/core.datasetController.js
  test/fixtures/controller.bar/bar-thickness-multiple.json
  test/fixtures/controller.bar/bar-thickness-no-overlap.json
  test/fixtures/controller.bar/bar-thickness-offset.json
  test/fixtures/controller.bar/bar-thickness-reverse.json
  test/fixtures/controller.bar/bar-thickness-stacked.json
  test/fixtures/controller.bar/stacking/logarithmic-strings.js
  test/fixtures/controller.bar/stacking/logarithmic.js
  test/fixtures/plugin.filler/fill-line-dataset-interpolated.js
  test/specs/controller.bar.tests.js
  test/specs/controller.line.tests.js
Labels: breaking change

#6884 Proposed fix for issue #6830
  docs/getting-started/v3-migration.md
  src/elements/element.point.js
  src/helpers/helpers.canvas.js
  test/fixtures/controller.bubble/point-style.json
Labels: type: bug

#6969 Rebuild legend after datasets are updated
  src/plugins/plugin.legend.js
Labels: type: bug

#6972 Fix bar border artifacts
  src/elements/element.rectangle.js
  test/fixtures/controller.bar/horizontal-borders.png
Labels: type: bug

#6977 Use import statements in test code
  src/adapters/adapter.moment.js
  src/adapters/index.js
  src/core/core.adapters.js
  test/fixture.js
  test/index.js
  test/matchers.js
Labels: type: chore

#6975 fix drawPoint parameters
  src/plugins/plugin.legend.js
Labels: type: bug

#6966 Linear scale with min/max/stepSize set should use all 3 if the range fit
  src/scales/scale.linearbase.js
  test/specs/scale.linear.tests.js
  test/specs/scale.radialLinear.tests.js
Labels: type: bug

#6961 Fix tooltip for 'dataset' mode
  src/core/core.controller.js
  src/core/core.interaction.js
  test/specs/core.interaction.tests.js
Labels: type: bug

#6994 Update version in package-lock
  package-lock.json
Labels: type: chore

#6997 Enable imports for tests
  karma.conf.js
  test/specs/helpers.math.tests.js
Labels: type: infrastructure

#6989 Filler fix
  src/plugins/plugin.filler.js
Labels: type: bug

#6988 Proper text alignment for multiline tick labels
  src/core/core.scale.js
Labels: type: bug

#6998 Improved financial sample
  samples/advanced/financial.html
  samples/samples.js
  samples/scales/time/financial.html
Labels: type: documentation

#7004 Format numbers in tooltip
  src/plugins/plugin.tooltip.js
  src/scales/scale.linearbase.js
  src/scales/scale.logarithmic.js
  test/specs/scale.linear.tests.js
  test/specs/scale.logarithmic.tests.js
  test/specs/scale.radialLinear.tests.js
Labels: type: enhancement

#7023 Fix binarySearch for empty dataset
  src/core/core.interaction.js
Labels: type: bug

#7024 Switch to const/let in platform.dom.js and fix bug
  src/platform/platform.dom.js
Labels: type: bug, type: chore

#7031 Remove unused variable
  src/scales/scale.time.js
Labels: type: chore

#7028 Move text helpers and reduce scope of imports
  docs/getting-started/v3-migration.md
  src/core/core.scale.js
  src/core/core.ticks.js
  src/helpers/helpers.canvas.js
  src/helpers/index.js
  src/scales/scale.radialLinear.js
  test/specs/core.helpers.tests.js
  test/specs/helpers.canvas.tests.js
Labels: type: chore

#7032 Convert the DateAdapter to ES6
  src/core/core.adapters.js
Labels: type: chore

#7033 Reduce requestAnimationFrame polyfill
  src/helpers/index.js
Labels: type: chore

#7037 Fix isRadial is always false
  src/core/core.controller.js
Labels: type: bug

#7039 Remove unused helpers
  docs/getting-started/v3-migration.md
  src/helpers/index.js
  test/specs/core.helpers.tests.js
Labels: type: chore

#7040 Fix typo in elements.line
  src/elements/element.line.js
Labels: type: bug

#7034 Fix legend.md markdown syntax
  docs/configuration/legend.md
Labels: type: documentation
