Repository chartjs/Chart.js, pull requests merged in 2020-09, with the labels that each got.

#7747 Reduce code duplication and sort generated ticks
  src/scales/scale.time.js
  test/fixtures/scale.time/negative-times.js
  test/fixtures/scale.time/negative-times.png
Labels: type: bug

#7753 Chart.register instead of Chart.plugins.register
  docs/docs/developers/plugins.md
  docs/docs/getting-started/v3-migration.md
  samples/charts/area/analyser.js
Labels: type: documentation

#7756 Remove duplicate code, clearer parameter names
  src/core/core.controller.js
Labels: type: chore

#7757 Fix the parameter order of before/afterEvent
  src/core/core.plugins.js
Labels: type: documentation

#7755 Cache Intl.NumberFormat instances
  package-lock.json
  package.json
  src/core/core.ticks.js
  src/index.js
Labels: type: chore, type: performance

#7765 Update pull request template contributing docs link
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: documentation

#7792 Fix: relative position in FF
  src/helpers/helpers.dom.js
  test/specs/helpers.dom.tests.js
Labels: type: bug

#7790 Better error message when importing charts incorrectly.
  src/core/core.controller.js
Labels: type: bug

#7794 Merge x/y interaction mode functions
  src/core/core.interaction.js
Labels: type: chore

#7795 Cache event offset coordinates
  src/core/core.controller.js
  src/helpers/helpers.dom.js
  src/helpers/helpers.extras.js
  src/platform/platform.dom.js
  test/specs/helpers.dom.tests.js
Labels: type: chore

#7796 Fix some CC issues
  src/elements/element.rectangle.js
  src/helpers/helpers.collection.js
  src/helpers/helpers.dom.js
  src/helpers/helpers.options.js
  types/elements/index.d.ts
Labels: type: chore

#7800 Limit pixel values to 32bit integer range
  src/core/core.scale.js
  src/helpers/helpers.math.js
Labels: type: bug

#7793 [perf] Update/draw only visible line/points
  docs/docs/getting-started/v3-migration.md
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.line.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/core/core.datasetController.js
  src/elements/element.line.js
  test/fixtures/scale.time/source-labels-linear-offset-min-max.png
  test/fixtures/scale.time/ticks-reverse-linear-min-max.png
  test/fixtures/scale.time/ticks-reverse-linear.png
  types/core/index.d.ts
Labels: type: performance

#7808 Fix: Update/draw only visible -regression
  src/controllers/controller.line.js
Labels: type: bug

#7816 Fix: maximum size and mouse position with styling
  docs/docs/getting-started/v3-migration.md
  src/core/core.controller.js
  src/helpers/helpers.dom.js
  src/platform/platform.base.js
  src/platform/platform.dom.js
  test/specs/helpers.dom.tests.js
  types/helpers/helpers.dom.d.ts
  types/platform/index.d.ts
Labels: type: bug
