Repository chartjs/Chart.js, pull requests merged in 2020-05, with the labels that each got.

#7314 Remove old docs from gitignore
  .gitignore
Labels: type: chore

#7315 Improve Docusaurus URLs
  docs/docs/axes/cartesian/index.md
  docs/docs/axes/index.md
  docs/docs/axes/radial/index.md
  docs/docs/configuration/index.md
  docs/docs/developers/index.md
  docs/docs/general/interactions/index.md
  docs/docs/getting-started/index.md
  docs/docs/index.md
  docs/sidebars.js
  docs/src/pages/index.js
Labels: type: documentation

#7316 feat(website): add DocSearch as recommended by docusaurus
  docs/docusaurus.config.js
Labels: type: documentation

#7317 Upgrade dependencies
  package-lock.json
  package.json
Labels: type: chore

#7327 Update the contributing guide for Docusaurus
  docs/docs/developers/contributing.md
Labels: type: documentation

#7334 Document the removal of deprecated properties
  docs/docs/getting-started/v3-migration.md
Labels: type: documentation

#7333 Remove unused bar property and confusing docs referring to it
  docs/docs/developers/charts.md
  docs/docs/getting-started/v3-migration.md
  src/controllers/controller.bar.js
Labels: type: chore

#7329 Add Algolia to docs
  docs/docusaurus.config.js
Labels: type: documentation

#7349 When the container padding is an empty string, handle it as 0px
  src/helpers/helpers.dom.js
Labels: type: bug

#7358 Developer migration documentation
  docs/docs/developers/index.md
  docs/docs/getting-started/v3-migration.md
  src/core/core.datasetController.js
Labels: type: documentation

#7360 Use @rollup/plugin-inject for ResizeObserver poly
  package-lock.json
  package.json
  rollup.config.js
Labels: type: bug

#7352 Upgrade dependencies
  package-lock.json
  package.json
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/core/core.datasetController.js
  src/helpers/index.js
Labels: type: chore

#7348 Fix broken links to contributor's guide
  README.md
Labels: type: documentation

#7345 Better organize calls in main controller
  src/core/core.controller.js
Labels: type: chore

#7375 Use correct index when resolving bubble options
  src/controllers/controller.bubble.js
Labels: type: bug

#7376 Upgrade Docusaurus to alpha.55
  docs/package-lock.json
  docs/package.json
Labels: type: chore

#7377 Add a JSDoc for _dataCheck
  src/core/core.datasetController.js
Labels: type: documentation

#7385 use direct imports instead of generic helpers import
  src/core/core.animation.js
  src/core/core.animator.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.interaction.js
  src/helpers/helpers.extras.js
  src/helpers/index.js
  src/platform/platform.dom.js
  src/plugins/plugin.title.js
  src/plugins/plugin.tooltip.js
  src/scales/scale.radialLinear.js
Labels: type: chore

#7384 Small update to animation documentation
  docs/docs/configuration/animations.md
  docs/docs/configuration/animations.mdx
  docs/docs/general/options.md
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
Labels: type: documentation

#7383 Move font* to font.*
  docs/docs/axes/labelling.md
  docs/docs/axes/radial/linear.md
  docs/docs/axes/styling.md
  docs/docs/configuration/legend.md
  docs/docs/configuration/title.md
  docs/docs/configuration/tooltip.md
  docs/docs/general/fonts.md
  docs/docs/getting-started/v3-migration.md
  samples/scales/axes-labels.html
  samples/scales/financial.html
  samples/scales/time/line-max-span.html
  samples/scales/time/line-point-data.html
  samples/tooltips/custom-line.html
  samples/tooltips/custom-pie.html
  src/core/core.defaults.js
  src/core/core.scale.js
  src/helpers/helpers.canvas.js
  src/helpers/helpers.options.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.title.js
  src/plugins/plugin.tooltip.js
  src/scales/scale.linear.js
  src/scales/scale.radialLinear.js
  src/scales/scale.time.js
  test/specs/core.controller.tests.js
  test/specs/helpers.options.tests.js
  test/specs/plugin.title.tests.js
  test/specs/plugin.tooltip.tests.js
  test/specs/scale.radialLinear.tests.js
Labels: breaking change, type: enhancement

#7405 Docs: fix z-index default
  docs/docs/axes/styling.md
Labels: type: documentation

#7410 Legend onClick callback supports arrow functions
  docs/docs/configuration/legend.md
  docs/docs/general/interactions/events.md
  docs/docs/getting-started/v3-migration.md
  samples/charts/multi-series-pie.html
  samples/charts/pie.html
  src/controllers/controller.doughnut.js
  src/controllers/controller.polarArea.js
  src/core/core.controller.js
  src/plugins/plugin.legend.js
  test/specs/global.defaults.tests.js
Labels: breaking change, type: bug

#7298 Fix chart resizing issue (#7297)
  src/platform/platform.dom.js
  test/specs/core.controller.tests.js
Labels: type: bug

#7414 Default aspectRatio to 1 for square charts
  docs/docs/getting-started/v3-migration.md
  src/controllers/controller.doughnut.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
Labels: breaking change

#7411 Only draw the tooltip if it is defined
  src/plugins/plugin.tooltip.js
Labels: type: bug

#7421 Consider all timestamps for bar measuring
  karma.conf.js
  src/scales/scale.time.js
  test/fixtures/scale.time/bar-large-gap-between-data.js
  test/fixtures/scale.time/bar-large-gap-between-data.png
Labels: type: bug

#7432 Upgrade to Docusaurus alpha.56
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
  docs/src/pages/index.js
Labels: type: chore

#7440 Clean lint errors from samples by refactoring
  samples/scriptable/bubble.html
  samples/tooltips/custom-line.html
  samples/utils.js
Labels: type: chore

#7439 Cleanup resize complexity
  src/core/core.controller.js
Labels: type: chore

#7437 Remove missing setDataVisibility for documentation
  docs/docs/developers/api.md
Labels: type: documentation

#7438 Arc: Stop drawing anything when hidden
  src/elements/element.arc.js
  test/fixtures/controller.doughnut/doughnut-hidden.js
  test/fixtures/controller.doughnut/doughnut-hidden.png
Labels: type: bug, type: chore

#7441 Remove unused dependency
  package-lock.json
  package.json
Labels: type: chore

#7442 Make indexable options looping
  docs/docs/getting-started/v3-migration.md
  src/helpers/helpers.options.js
  test/fixtures/controller.bar/backgroundColor/loopable.js
  test/fixtures/controller.bar/backgroundColor/loopable.png
  test/specs/helpers.options.tests.js
Labels: breaking change, type: enhancement

#7446 Radar charts should fill to the center by default
  src/controllers/controller.radar.js
  test/fixtures/controller.radar/backgroundColor/scriptable.js
  test/fixtures/controller.radar/backgroundColor/value.js
  test/fixtures/controller.radar/borderDash/scriptable.js
Labels: type: bug

#7447 Update doc samples for changed file name
  docs/docusaurus.config.js
Labels: type: documentation
