Repository chartjs/Chart.js, pull requests merged in 2020-12, with the labels that each got.

#8101 Fix CategoryScale.getValueForPixel with autoSkip
  src/scales/scale.category.js
  test/specs/scale.category.tests.js
Labels: type: bug

#8112 Add new scale hooks for plugins
  src/core/core.controller.js
  src/core/core.plugins.js
  src/core/core.scale.js
  test/specs/core.controller.tests.js
  test/specs/core.plugin.tests.js
  types/core/index.d.ts
Labels: type: enhancement

#8118 [v3] Add locale to ChartOptions type
  docs/docs/general/locale.md
  docs/sidebars.js
  types/core/interfaces.d.ts
Labels: type: types

#8127 New release workflow
  .github/workflows/npmpublish.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  package-lock.json
  package.json
Labels: type: infrastructure

#8129 Fix the needs name in release.yml
  .github/workflows/release.yml
Labels: type: infrastructure

#8130 Update release.yml
  .github/workflows/release.yml
Labels: type: infrastructure

#8131 Revert "New release workflow (#8127)" and fixes
  .github/workflows/npmpublish.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  package-lock.json
  package.json
Labels: type: infrastructure

#8132 CI: Conditionally run steps based on changes
  .github/workflows/ci.yml
Labels: type: chore, type: infrastructure

#8142 Respect the set locale in the pie/doughnut tooltips
  src/controllers/controller.doughnut.js
Labels: type: bug

#8156 default values for element background and border color were wrong
  docs/docs/configuration/elements.md
Labels: type: documentation

#8162 Prevent double plugin registers from losing the list of plugins
  src/core/core.plugins.js
  test/specs/core.plugin.tests.js
Labels: type: bug

#8161 Quick exit the legend fit function when the legend is not displayed
  src/plugins/plugin.legend.js
  test/specs/plugin.legend.tests.js
Labels: type: bug

#8151 Update docs for .resize() method
  docs/docs/developers/api.md
  src/core/core.controller.js
Labels: type: documentation

#8109 Legend plugin cleanup
  src/helpers/helpers.extras.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.title.js
Labels: type: chore

#8167 Use correct color for legend labels
  docs/docs/configuration/legend.md
  src/plugins/plugin.legend.js
  test/specs/plugin.legend.tests.js
Labels: type: bug

#8170 ArcElement: Skip draw when radius is negative
  src/elements/element.arc.js
  test/specs/element.arc.tests.js
Labels: type: bug

#8168 Fix legend alignment issues
  src/plugins/plugin.legend.js
  test/fixtures/plugin.legend/title/bottom-center-center.js
  test/fixtures/plugin.legend/title/bottom-center-center.png
  test/fixtures/plugin.legend/title/bottom-end-end.js
  test/fixtures/plugin.legend/title/bottom-end-end.png
  test/fixtures/plugin.legend/title/bottom-start-start.js
  test/fixtures/plugin.legend/title/bottom-start-start.png
  test/fixtures/plugin.legend/title/left-center-center.js
  test/fixtures/plugin.legend/title/left-center-center.png
  test/fixtures/plugin.legend/title/left-end-end.js
  test/fixtures/plugin.legend/title/left-end-end.png
  test/fixtures/plugin.legend/title/left-start-start.js
  test/fixtures/plugin.legend/title/left-start-start.png
  test/fixtures/plugin.legend/title/right-center-center.js
  test/fixtures/plugin.legend/title/right-center-center.png
  test/fixtures/plugin.legend/title/right-end-end.js
  test/fixtures/plugin.legend/title/right-end-end.png
  test/fixtures/plugin.legend/title/right-start-start.js
  test/fixtures/plugin.legend/title/right-start-start.png
  test/fixtures/plugin.legend/title/top-center-center.js
  test/fixtures/plugin.legend/title/top-center-center.png
  test/fixtures/plugin.legend/title/top-end-end.js
  test/fixtures/plugin.legend/title/top-end-end.png
  test/fixtures/plugin.legend/title/top-start-start.js
  test/fixtures/plugin.legend/title/top-start-start.png
Labels: type: bug

#8177 added comma to fix syntax issue
  docs/docs/charts/mixed.mdx
Labels: type: documentation

#8181 Remove dataset while hovered
  src/core/core.controller.js
Labels: type: bug

#8174 fix: add ArcElement to getting-started.md
  docs/docs/getting-started/integration.md
Labels: type: documentation

#8184 Reject pending promises when animation is updated
  src/core/core.animation.js
  src/core/core.animations.js
  test/specs/core.animations.tests.js
Labels: type: bug

#8185 Hover: only update styles of changed elements
  src/core/core.controller.js
Labels: type: enhancement

#8160 Move tooltip plugin hooks to the core Plugin type
  types/core/index.d.ts
  types/plugins/index.d.ts
Labels: type: types

#8191 Radius validation for drawRadiusLine
  src/scales/scale.radialLinear.js
Labels: type: bug

#8195 Update defaults and types for tick stroke
  src/core/core.scale.js
  types/scales/index.d.ts
Labels: type: bug, type: types

#8194 Make PointLabels color scriptable
  src/scales/scale.radialLinear.js
Labels: type: bug

#8190 TypeScript updates
  docs/docs/configuration/animations.mdx
  docs/docs/configuration/legend.md
  types/core/index.d.ts
  types/core/interfaces.d.ts
  types/index.esm.d.ts
  types/interfaces.d.ts
  types/plugins/index.d.ts
Labels: type: types

#8193 Layout: enforce box limits, reject <0 chartArea
  src/core/core.controller.js
  src/core/core.layouts.js
  src/plugins/plugin.legend.js
  test/fixtures/plugin.legend/title/left-center-center.png
  test/fixtures/plugin.legend/title/left-end-end.png
  test/fixtures/plugin.legend/title/right-center-center.png
  test/fixtures/plugin.legend/title/right-end-end.png
  test/fixtures/plugin.legend/title/right-start-start.png
Labels: type: enhancement

#8196 Add color options to documentation and types where missing
  docs/docs/axes/_common_ticks.md
  docs/docs/axes/labelling.md
  docs/docs/axes/radial/linear.mdx
  docs/docs/axes/styling.mdx
  docs/docs/charts/bar.mdx
  docs/docs/charts/bubble.mdx
  docs/docs/charts/doughnut.mdx
  docs/docs/charts/polar.mdx
  docs/docs/charts/radar.mdx
  docs/docs/configuration/animations.mdx
  docs/docs/configuration/elements.md
  docs/docs/configuration/layout.md
  docs/docs/configuration/legend.md
  docs/docs/configuration/title.md
  docs/docs/configuration/tooltip.md
  docs/docs/general/data-structures.md
  docs/docs/general/fonts.md
  types/core/interfaces.d.ts
  types/plugins/index.d.ts
  types/scales/index.d.ts
Labels: type: documentation, type: types

#8199 Controller defaults wrong adressing
  docs/docs/configuration/index.md
Labels: type: documentation

#8198 Merge TS files into a single file to prevent circular loops
  types/controllers/index.d.ts
  types/core/index.d.ts
  types/core/interfaces.d.ts
  types/elements/index.d.ts
  types/helpers/helpers.canvas.d.ts
  types/helpers/helpers.easing.d.ts
  types/helpers/helpers.options.d.ts
  types/index.esm.d.ts
  types/interfaces.d.ts
  types/platform/index.d.ts
  types/plugins/index.d.ts
  types/scales/index.d.ts
Labels: type: types

#8203 Update dependencies
  package-lock.json
  package.json
Labels: type: infrastructure

#8204 Update CI
  .github/workflows/ci.yml
Labels: type: infrastructure

#8202 Split geometric types to their own definition file
  types/geometric.d.ts
  types/helpers/helpers.canvas.d.ts
  types/index.esm.d.ts
Labels: type: chore

#8205 Split adapter types to their own definition file
  types/adapters.d.ts
  types/index.esm.d.ts
Labels: type: chore

#8206 Split Element type to it's own definition file
  types/element.d.ts
  types/index.esm.d.ts
Labels: type: chore

#8201 Docs/multiline labels
  docs/docs/general/data-structures.md
Labels: type: documentation

#8208 Split animation definitions
  types/animation.d.ts
  types/index.esm.d.ts
Labels: type: chore

#8212 Ensure that default animation modes table is clear
  docs/docs/configuration/animations.mdx
Labels: type: documentation

#8214 Add note about loading fonts and chart updates
  docs/docs/general/fonts.md
Labels: type: documentation

#8216 Ensure that default collections table is clear
  docs/docs/configuration/animations.mdx
Labels: type: documentation

#8215 Add options to configure tick styling independent of grid lines
  docs/docs/axes/styling.mdx
  docs/docs/getting-started/v3-migration.md
  src/core/core.scale.js
  test/fixtures/core.scale/tick-override-styles.json
  test/fixtures/core.scale/tick-override-styles.png
  types/index.esm.d.ts
Labels: breaking change, type: enhancement

#8221 Horizontal axis with center position should display labels
  src/core/core.scale.js
  test/fixtures/core.scale/x-axis-position-center.json
  test/fixtures/core.scale/x-axis-position-center.png
  test/fixtures/core.scale/x-axis-position-dynamic.json
  test/fixtures/core.scale/x-axis-position-dynamic.png
  test/fixtures/core.scale/y-axis-position-center.json
  test/fixtures/core.scale/y-axis-position-center.png
  test/fixtures/core.scale/y-axis-position-dynamic.json
  test/fixtures/core.scale/y-axis-position-dynamic.png
Labels: type: bug

#8222 Scriptable tick colours
  src/core/core.scale.js
Labels: type: bug

#8223 Remove duplicate Scriptable definitions
  types/index.esm.d.ts
  types/scriptable.d.ts
Labels: breaking change, type: chore

#8226 Enable changing the chart type
  src/core/core.config.js
Labels: type: bug

#8230 Example code plugin outdated
  docs/docs/developers/plugins.md
Labels: type: documentation

#8227 Create standardized text render method
  docs/docs/axes/_common_ticks.md
  src/core/core.scale.js
  src/helpers/helpers.canvas.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.title.js
  src/scales/scale.radialLinear.js
  test/context.js
  test/specs/helpers.canvas.tests.js
  test/specs/plugin.title.tests.js
  test/specs/plugin.tooltip.tests.js
  types/color.d.ts
  types/helpers/helpers.canvas.d.ts
  types/index.esm.d.ts
Labels: type: chore

#8234 Cache data limits to ensure they are only computed once per update
  src/core/core.datasetController.js
  src/core/core.layouts.js
  src/core/core.scale.js
  src/scales/scale.time.js
  types/index.esm.d.ts
Labels: type: performance

#8235 Clean up the LayoutItem type
  types/index.esm.d.ts
  types/layout.d.ts
Labels: type: chore

#8237 Migrate to chartjs-test-utils
  package-lock.json
  package.json
  test/context.js
  test/fixture.js
  test/index.js
  test/matchers.js
  test/spriting.js
  test/utils.js
Labels: type: infrastructure

#8240 Cache the lineheight regex
  src/helpers/helpers.options.js
Labels: type: performance

#8241 2.9 docs - fix broken link
  docs/README.md
Labels: type: documentation

#8236 Update spelling of cancellable
  src/core/core.controller.js
  src/core/core.plugins.js
  test/specs/core.plugin.tests.js
Labels: type: chore

#8238 Rename helpers.clear to helpers.clearCanvas
  docs/docs/getting-started/v3-migration.md
  src/core/core.controller.js
  src/helpers/helpers.canvas.js
  test/specs/helpers.canvas.tests.js
  types/helpers/helpers.canvas.d.ts
Labels: type: chore

#8239 Line: Use Path2D as cache
  src/elements/element.line.js
  src/helpers/helpers.extras.js
Labels: type: performance

#8245 Mention npm in installation section
  docs/docs/index.md
Labels: type: documentation

#8244 Use cached Intl.NumberFormat everywhere
  src/controllers/controller.doughnut.js
  src/core/core.intl.js
  src/core/core.ticks.js
  src/scales/scale.linearbase.js
  src/scales/scale.logarithmic.js
Labels: type: performance

#8246 Line: Update points directly, when possible
  src/controllers/controller.line.js
Labels: type: performance

#8247 Always freeze cached options
  src/core/core.datasetController.js
Labels: type: bug

#8248 Skip reset when animations are disabled
  src/core/core.controller.js
  src/core/core.datasetController.js
Labels: breaking change, type: performance

#8253 Fix small bugs when animations are disabled
  src/core/core.controller.js
  src/core/core.element.js
  src/helpers/helpers.extras.js
  test/specs/core.element.tests.js
Labels: type: bug

#8250 Line: Set points on resize (to reset Path2D cache)
  src/controllers/controller.line.js
Labels: type: bug

#8252 Tooltip: Render when animations are disabled
  docs/docs/getting-started/v3-migration.md
  src/core/core.controller.js
  src/plugins/plugin.tooltip.js
  types/index.esm.d.ts
Labels: type: bug

#8254 Use provided options in tooltip plugin
  src/core/core.defaults.js
  src/plugins/plugin.tooltip.js
  test/specs/plugin.tooltip.tests.js
Labels: type: chore

#8259 Change title font default option in the documentation
  docs/docs/configuration/title.md
Labels: type: documentation

#8257 Adds backgroundColor and borderColor options to the documentation
  docs/docs/general/colors.md
Labels: type: documentation
