Repository chartjs/Chart.js, pull requests merged in 2020-07, with the labels that each got.

#7584 The hover* options of bar chart doc page change as scriptable
  docs/docs/charts/bar.mdx
Labels: type: documentation

#7587 docs: fix rollup external moment
  docs/getting-started/integration.md
Labels: type: documentation

#7579 Pass context parameter to custom tooltip
  docs/docs/configuration/tooltip.md
  docs/docs/getting-started/v3-migration.md
  src/plugins/plugin.tooltip.js
Labels: type: bug, type: enhancement

#7573 Use all timestamps for calculating offsets
  src/scales/scale.timeseries.js
  test/specs/scale.time.tests.js
Labels: type: bug

#7572 Fix padding for labels
  src/core/core.scale.js
Labels: type: bug

#7570 Enable autoSkip for time scale to match others
  docs/docs/getting-started/v3-migration.md
  src/scales/scale.time.js
  test/specs/scale.time.tests.js
Labels: breaking change, type: chore

#7568 Remove duplicate tests
  test/specs/scale.time.tests.js
Labels: type: chore

#7435 Generic registry for controllers, scales, elements and plugins
  docs/docs/axes/index.md
  docs/docs/developers/axes.md
  docs/docs/developers/charts.md
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.line.js
  src/controllers/controller.pie.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/controllers/controller.scatter.js
  src/controllers/index.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.defaults.js
  src/core/core.element.js
  src/core/core.registry.js
  src/core/core.scaleService.js
  src/core/core.typedRegistry.js
  src/core/index.js
  src/elements/element.arc.js
  src/elements/element.line.js
  src/elements/element.point.js
  src/elements/element.rectangle.js
  src/index.js
  src/scales/scale.category.js
  src/scales/scale.linear.js
  src/scales/scale.logarithmic.js
  src/scales/scale.radialLinear.js
  src/scales/scale.time.js
  src/scales/scale.timeseries.js
  test/specs/controller.doughnut.tests.js
  test/specs/core.controller.tests.js
  test/specs/core.scale.tests.js
  test/specs/core.scaleService.tests.js
  test/specs/global.namespace.tests.js
  test/specs/scale.category.tests.js
  test/specs/scale.linear.tests.js
  test/specs/scale.logarithmic.tests.js
  test/specs/scale.radialLinear.tests.js
  test/specs/scale.time.tests.js
Labels: type: infrastructure

#7538 Add normalized option
  docs/docs/axes/cartesian/timeseries.md
  docs/docs/general/performance.md
  src/controllers/controller.bar.js
  src/controllers/controller.line.js
  src/core/core.controller.js
  src/core/core.scale.js
  src/scales/scale.time.js
  src/scales/scale.timeseries.js
  test/specs/scale.time.tests.js
Labels: type: enhancement

#7592 Tooltip Model documentation sounds not correct
  docs/docs/configuration/tooltip.md
  docs/docs/getting-started/v3-migration.md
Labels: type: documentation

#7590 PluginService using registry
  docs/docs/configuration/title.md
  docs/docs/configuration/tooltip.md
  docs/docs/developers/axes.md
  docs/docs/developers/charts.md
  docs/docs/getting-started/integration.md
  docs/docs/getting-started/v3-migration.md
  docs/docs/index.md
  package.json
  samples/tooltips/custom-pie.html
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.defaults.js
  src/core/core.plugins.js
  src/core/core.registry.js
  src/helpers/helpers.collection.js
  src/helpers/helpers.core.js
  src/index.js
  src/plugins/index.js
  src/plugins/plugin.title.js
  src/plugins/plugin.tooltip.js
  test/specs/core.plugin.tests.js
  test/specs/global.namespace.tests.js
  test/specs/plugin.title.tests.js
  test/specs/plugin.tooltip.tests.js
Labels: breaking change, type: enhancement

#7595 Fix errors in custom tooltip samples
  samples/tooltips/custom-line.html
  samples/tooltips/custom-pie.html
  samples/tooltips/custom-points.html
Labels: type: documentation

#7603 Align the tooltip callbacks parameters with scriptable options
  docs/docs/configuration/tooltip.md
  docs/docs/getting-started/v3-migration.md
  samples/charts/multi-series-pie.html
  samples/scales/financial.html
  samples/tooltips/callbacks.html
  src/controllers/controller.doughnut.js
  src/controllers/controller.polarArea.js
  src/plugins/plugin.tooltip.js
  test/specs/plugin.tooltip.tests.js
Labels: breaking change

#7618 Tooltip: add dataPoint and rename value to formattedValue
  docs/docs/configuration/tooltip.md
  docs/docs/general/options.md
  docs/docs/getting-started/v3-migration.md
  samples/scriptable/bar.html
  samples/scriptable/line.html
  samples/scriptable/pie.html
  samples/scriptable/radar.html
  samples/tooltips/callbacks.html
  src/controllers/controller.bubble.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.scatter.js
  src/core/core.datasetController.js
  src/plugins/plugin.tooltip.js
  test/specs/plugin.tooltip.tests.js
Labels: breaking change, type: enhancement

#7620 Move registration migration guide to user migration section
  docs/docs/getting-started/v3-migration.md
Labels: type: documentation

#7623 Fix links to fonts.md
  docs/docs/axes/labelling.md
  docs/docs/axes/radial/linear.md
  docs/docs/axes/styling.md
  docs/docs/configuration/title.md
  docs/docs/configuration/tooltip.md
Labels: type: documentation

#7626 Move register/unregister to core.controller
  src/core/core.controller.js
  src/index.js
Labels: type: bug

#7624 Align axes documentation with the changes
  docs/docs/axes/cartesian/category.md
  docs/docs/axes/cartesian/index.md
  docs/docs/axes/cartesian/time.md
  docs/docs/axes/index.md
  docs/docs/axes/styling.md
Labels: type: documentation

#7622 Fix category scale tick placement with autoSkip
  src/scales/scale.category.js
  test/specs/scale.category.tests.js
Labels: type: bug

#7625 Fix remaining issues in samples
  docs/docs/configuration/tooltip.md
  docs/docs/getting-started/v3-migration.md
  samples/animations/loop.html
  samples/tooltips/custom-line.html
  samples/tooltips/custom-points.html
  src/core/core.animation.js
  src/plugins/plugin.tooltip.js
Labels: type: bug, type: documentation

#7631 Removes the line hegiht property from title documentation
  docs/docs/configuration/title.md
Labels: type: documentation

#7634 FloatBar: update range only for value scale
  src/controllers/controller.bar.js
Labels: type: bug

#7635 Add test fixture for financial sample
  test/fixtures/scale.timeseries/financial-daily.js
  test/fixtures/scale.timeseries/financial-daily.png
Labels: type: chore

#7637 Determine unit automatically in test
  test/fixtures/scale.timeseries/financial-daily.js
Labels: type: chore

#7638 Fix tooltip in financial sample
  samples/scales/financial.html
Labels: type: documentation

#7649 Do not use line defaults in legend
  src/plugins/plugin.legend.js
Labels: type: bug

#7653 Fix import statement in docs
  docs/docs/getting-started/integration.md
  docs/docs/getting-started/v3-migration.md
Labels: type: documentation

#7658 Docs: chart should live in own container
  docs/docs/getting-started/index.md
Labels: type: documentation

#7659 Live demo in getting-started page
  docs/docs/getting-started/index.mdx
  docs/package.json
  package.json
Labels: type: chore, type: documentation

#7670 Fix casing of dist files in docs
  .github/ISSUE_TEMPLATE/BUG.md
  docs/docs/developers/contributing.md
  docs/docs/developers/index.md
Labels: type: documentation

#7685 Add some additional info and sections to animation documentation
  docs/docs/configuration/animations.mdx
Labels: type: documentation
