Repository chartjs/Chart.js, pull requests merged in 2020-02, with the labels that each got.

#7047 Fix bug in opacity handling
  src/plugins/plugin.tooltip.js
Labels: type: bug

#6999 Remove extra call to _getLabelCapacity
  src/scales/scale.time.js
Labels: type: chore

#7048 Update legend imports
  src/plugins/plugin.legend.js
Labels: type: chore

#7049 Update imports for elements
  src/elements/element.point.js
  src/elements/element.rectangle.js
Labels: type: chore

#7007 Improved formatting of numeric scale labels
  docs/getting-started/v3-migration.md
  src/core/core.ticks.js
  src/scales/scale.linear.js
  src/scales/scale.linearbase.js
  src/scales/scale.logarithmic.js
  src/scales/scale.radialLinear.js
  test/specs/core.ticks.tests.js
  test/specs/scale.linear.tests.js
  test/specs/scale.logarithmic.tests.js
  test/specs/scale.radialLinear.tests.js
  test/utils.js
Labels: type: enhancement

#7026 Fix some JSDoc errors
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.interaction.js
  src/core/core.scale.js
  src/helpers/helpers.dom.js
  src/platform/platform.base.js
  src/plugins/plugin.filler.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.tooltip.js
  src/scales/scale.linearbase.js
  src/scales/scale.logarithmic.js
  src/scales/scale.time.js
Labels: type: chore

#7056 Make datasetController an ES6 class
  src/core/core.datasetController.js
Labels: type: chore

#7060 Fix legend title drawing & update sample
  samples/legend/title.html
  src/plugins/plugin.legend.js
Labels: type: bug

#7061 Convert controllers to ES6 classes
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.horizontalBar.js
  src/controllers/controller.line.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
Labels: type: chore

#7055 Configurable hide/show animations
  docs/configuration/animations.md
  docs/developers/api.md
  src/controllers/controller.bar.js
  src/controllers/controller.line.js
  src/core/core.animation.js
  src/core/core.animations.js
  src/core/core.animator.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/plugins/plugin.legend.js
Labels: type: enhancement

#7067 core.scale cleanup
  src/core/core.scale.js
Labels: type: chore

#7030 Allow codebase to be checked by TypeScript compiler
  docs/SUMMARY.md
  docs/getting-started/v3-migration.md
  gulpfile.js
  package-lock.json
  package.json
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.line.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/core/core.animation.js
  src/core/core.animator.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.element.js
  src/core/core.interaction.js
  src/core/core.layouts.js
  src/core/core.plugins.js
  src/core/core.scale.js
  src/core/core.ticks.js
  src/elements/element.arc.js
  src/elements/element.line.js
  src/elements/element.point.js
  src/elements/element.rectangle.js
  src/helpers/helpers.canvas.js
  src/helpers/helpers.core.js
  src/helpers/helpers.curve.js
  src/helpers/helpers.interpolation.js
  src/helpers/helpers.math.js
  src/helpers/helpers.rtl.js
  src/helpers/helpers.segment.js
  src/index.js
  src/platform/platform.base.js
  src/platform/platform.dom.js
  src/plugins/plugin.filler.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.title.js
  src/plugins/plugin.tooltip.js
  src/scales/scale.category.js
  src/scales/scale.linear.js
  src/scales/scale.linearbase.js
  src/scales/scale.logarithmic.js
  src/scales/scale.radialLinear.js
  src/scales/scale.time.js
  tsconfig.json
Labels: type: infrastructure

#7059 Switch from chartjs-color to @kurkle/color
  package-lock.json
  package.json
  src/core/core.animation.js
  src/helpers/index.js
  test/specs/controller.bar.tests.js
  test/specs/controller.bubble.tests.js
  test/specs/controller.doughnut.tests.js
  test/specs/controller.line.tests.js
  test/specs/controller.polarArea.tests.js
  test/specs/controller.radar.tests.js
  test/specs/core.helpers.tests.js
Labels: type: chore

#7070 Simplify financial sample
  samples/samples.js
  samples/scales/financial.html
Labels: type: documentation

#7072 Fix time scale computeOffsets
  src/scales/scale.time.js
  test/specs/scale.time.tests.js
Labels: type: bug

#7074 Defaults as ES6 class
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.horizontalBar.js
  src/controllers/controller.line.js
  src/controllers/controller.pie.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/controllers/controller.scatter.js
  src/core/core.animations.js
  src/core/core.defaults.js
  src/core/core.layouts.js
  src/core/core.plugins.js
  src/core/core.scale.js
  src/elements/element.arc.js
  src/elements/element.line.js
  src/elements/element.point.js
  src/elements/element.rectangle.js
  src/plugins/plugin.filler.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.title.js
  src/plugins/plugin.tooltip.js
Labels: type: chore

#7076 Fix lint issues in gulpfile.js
  .eslintignore
  gulpfile.js
Labels: type: chore

#7079 Animate circumference
  src/controllers/controller.doughnut.js
Labels: type: bug

#7080 Utilize _angleBetween in Arc
  src/elements/element.arc.js
Labels: type: chore

#7083 Document types for TimeScale
  src/core/core.adapters.js
  src/core/core.scale.js
  src/scales/scale.logarithmic.js
  src/scales/scale.time.js
Labels: type: chore, type: documentation

#7081 Prefix private controller methods with underscore
  docs/getting-started/v3-migration.md
  src/controllers/controller.bar.js
  src/core/core.animator.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.plugins.js
  test/fixtures/core.tooltip/opacity.js
  test/specs/controller.bar.tests.js
  test/specs/core.datasetController.tests.js
  test/utils.js
Labels: type: chore

#7087 Look for any branch starting with release
  scripts/deploy.sh
  scripts/release.sh
Labels: type: infrastructure

#7089 Look for any branch starting with release
  scripts/deploy.sh
  scripts/release.sh
Labels: type: infrastructure

#7082 Cleanup private methods on Scales
  docs/getting-started/v3-migration.md
  src/core/core.scale.js
  src/helpers/helpers.segment.js
  src/platform/platform.dom.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.tooltip.js
  src/scales/scale.category.js
  src/scales/scale.linearbase.js
  src/scales/scale.logarithmic.js
  src/scales/scale.radialLinear.js
  src/scales/scale.time.js
Labels: type: chore

#7088 Cleanup some Typescript comments
  src/core/core.interaction.js
  src/core/core.plugins.js
  src/helpers/helpers.segment.js
  src/scales/scale.time.js
Labels: type: chore

#7097 Fix memory leak
  src/core/core.animator.js
  src/core/core.controller.js
Labels: type: bug

#7098 Fix transparentize in samples
  samples/utils.js
Labels: type: bug

#7101 Remove unused property _maxLabelLines
  src/core/core.scale.js
Labels: type: chore

#7073 Allow "spriting" text in fixtures
  test/fixtures/scale.category/ticks-from-data.js
  test/fixtures/scale.category/ticks-from-data.png
  test/specs/scale.category.tests.js
  test/spriting.js
  test/utils.js
Labels: type: infrastructure

#7103 Change remaining `for of` loops to regular ones
  src/helpers/helpers.segment.js
  src/plugins/plugin.filler.js
Labels: type: bug

#7112 JSDoc fixes
  src/core/core.interaction.js
  src/core/core.scale.js
  src/helpers/helpers.dom.js
  src/helpers/helpers.options.js
  src/helpers/helpers.segment.js
  src/platform/platform.base.js
  src/platform/platform.dom.js
  src/scales/scale.linearbase.js
  src/scales/scale.time.js
Labels: type: chore, type: documentation

#7123 Make margins private
  docs/getting-started/v3-migration.md
  src/core/core.scale.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.title.js
Labels: type: chore

#7119 Include Typedoc files on GitHub pages
  docs/_config.yml
Labels: type: documentation

#7128 Remove version from docs. Use latest
  docs/getting-started/README.md
Labels: type: documentation

#7120 Simplify rtlAdapter export
  src/helpers/helpers.rtl.js
Labels: type: chore

#7126 Prepare babel & karma for class properties
  babel.config.json
  gulpfile.js
  karma.conf.js
  package-lock.json
  package.json
Labels: type: chore, type: infrastructure

#7127 Rename steppedLine to stepped
  docs/charts/line.md
  docs/configuration/elements.md
  docs/general/performance.md
  docs/getting-started/v3-migration.md
  samples/charts/line/stepped.html
  src/controllers/controller.line.js
  src/elements/element.line.js
  test/fixtures/element.line/stepped/after.js
  test/fixtures/element.line/stepped/before.js
  test/fixtures/element.line/stepped/default.js
  test/fixtures/element.line/stepped/middle.js
  test/fixtures/plugin.filler/fill-line-dataset-stepped.json
Labels: type: chore

#7130 Move color helpers to helpers.color
  src/helpers/helpers.color.js
  src/helpers/index.js
Labels: type: chore

#7122 No need to use rollup commonjs plugin
  rollup.config.js
Labels: type: infrastructure

#7132 Fix deploy.sh if
  scripts/deploy.sh
Labels: type: infrastructure

#7129 Include version in Chart
  package-lock.json
  package.json
  rollup.config.js
  src/core/core.controller.js
Labels: type: infrastructure

#7131 Remove css from deploy scripts
  scripts/deploy.sh
  scripts/release.sh
Labels: type: infrastructure

#7116 Turn on some TypeScript checks
  src/controllers/controller.line.js
  src/core/core.controller.js
  src/core/core.scale.js
  src/helpers/helpers.segment.js
  src/platform/platform.dom.js
  src/scales/scale.category.js
  src/scales/scale.linearbase.js
  src/scales/scale.logarithmic.js
  src/scales/scale.radialLinear.js
  src/scales/scale.time.js
  tsconfig.json
Labels: type: chore

#7121 Enable Typedoc excludeNotExported
  babel.config.json
  karma.conf.js
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.horizontalBar.js
  src/controllers/controller.line.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/core/core.adapters.js
  src/core/core.animation.js
  src/core/core.animator.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.defaults.js
  src/core/core.element.js
  src/core/core.plugins.js
  src/core/core.scale.js
  src/elements/element.arc.js
  src/elements/element.line.js
  src/elements/element.point.js
  src/elements/element.rectangle.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.title.js
  src/plugins/plugin.tooltip.js
  src/scales/scale.category.js
  src/scales/scale.linear.js
  src/scales/scale.linearbase.js
  src/scales/scale.logarithmic.js
  src/scales/scale.radialLinear.js
  src/scales/scale.time.js
  tsconfig.json
Labels: type: chore, type: documentation

#7134 Rollup plugins live in new location
  karma.conf.js
  package-lock.json
  package.json
  rollup.config.js
Labels: type: infrastructure

#7140 Remove unnecessary changes
  .travis.yml
  docs/_config.yml
Labels: type: chore

#7124 Create a Tick typedef
  src/core/core.scale.js
Labels: type: documentation

#7147 Ensure all samples use correct scale options
  samples/advanced/line-gradient.html
  samples/scales/axes-labels.html
  samples/scales/gridlines-scriptable.html
Labels: type: documentation

#7148 Fix coveralls
  gulpfile.js
  karma.conf.js
Labels: type: bug, type: infrastructure

#7146 WebWorker support
  docs/general/performance.md
  src/core/core.controller.js
  src/helpers/helpers.dom.js
Labels: type: enhancement

#7142 Make test Context an ES6 module
  karma.conf.js
  test/context.js
Labels: type: chore

#7150 Stop leaking fonts (and fillStyle) to ctx
  src/helpers/helpers.canvas.js
  src/plugins/plugin.title.js
  src/plugins/plugin.tooltip.js
  test/specs/helpers.canvas.tests.js
  test/specs/plugin.title.tests.js
Labels: type: bug

#7084 Issue 4991
  src/core/core.controller.js
  src/core/core.element.js
  src/core/core.interaction.js
  src/core/core.plugins.js
  src/elements/element.arc.js
  src/elements/element.point.js
  src/elements/element.rectangle.js
  src/plugins/plugin.tooltip.js
  test/specs/element.arc.tests.js
  test/specs/element.point.tests.js
  test/specs/global.defaults.tests.js
Labels: type: bug

#7135 Turn elements/index into an index
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.line.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/elements/index.js
  src/index.js
  test/specs/global.namespace.tests.js
Labels: type: chore, type: infrastructure

#7165 Remove position defaults
  src/controllers/controller.bubble.js
  src/controllers/controller.horizontalBar.js
  src/controllers/controller.scatter.js
Labels: type: chore

#7155 Give the boot to chartjs-adapter-moment
  docs/axes/cartesian/time.md
  docs/getting-started/integration.md
  docs/getting-started/v3-migration.md
  karma.conf.js
  package-lock.json
  package.json
  rollup.config.js
  rollup.plugins.js
  samples/.eslintrc.yml
  samples/scales/financial.html
  samples/scales/time/combo.html
  samples/scales/time/line-max-span.html
  samples/scales/time/line-point-data.html
  samples/scales/time/line.html
  src/adapters/adapter.moment.js
  src/adapters/index.js
  src/index.js
  src/scales/scale.time.js
Labels: breaking change, type: enhancement

#7154 Convert some of the time scale tests to fixtures
  test/fixtures/scale.time/autoskip-major.js
  test/fixtures/scale.time/autoskip-major.png
  test/fixtures/scale.time/custom-parser.js
  test/fixtures/scale.time/custom-parser.png
  test/fixtures/scale.time/data-ty.js
  test/fixtures/scale.time/data-ty.png
  test/fixtures/scale.time/data-xy.js
  test/fixtures/scale.time/data-xy.png
  test/fixtures/scale.time/labels-date.js
  test/fixtures/scale.time/labels-date.png
  test/fixtures/scale.time/labels-strings.js
  test/fixtures/scale.time/labels-strings.png
  test/fixtures/scale.time/labels.js
  test/fixtures/scale.time/labels.png
  test/fixtures/scale.time/source-auto-linear.js
  test/fixtures/scale.time/source-auto-linear.png
  test/fixtures/scale.time/source-auto-series.js
  test/fixtures/scale.time/source-auto-series.png
  test/fixtures/scale.time/source-data-linear.js
  test/fixtures/scale.time/source-data-linear.png
  test/fixtures/scale.time/source-data-series-offset-min-max.js
  test/fixtures/scale.time/source-data-series-offset-min-max.png
  test/fixtures/scale.time/source-data-series.js
  test/fixtures/scale.time/source-data-series.png
  test/fixtures/scale.time/source-labels-linear-offset-min-max.js
  test/fixtures/scale.time/source-labels-linear-offset-min-max.png
  test/fixtures/scale.time/source-labels-linear.js
  test/fixtures/scale.time/source-labels-linear.png
  test/fixtures/scale.time/source-labels-series-offset-min-max.js
  test/fixtures/scale.time/source-labels-series-offset-min-max.png
  test/fixtures/scale.time/source-labels-series.js
  test/fixtures/scale.time/source-labels-series.png
  test/fixtures/scale.time/ticks-capacity.js
  test/fixtures/scale.time/ticks-capacity.png
  test/fixtures/scale.time/ticks-minunit.js
  test/fixtures/scale.time/ticks-minunit.png
  test/fixtures/scale.time/ticks-reverse-linear-min-max.js
  test/fixtures/scale.time/ticks-reverse-linear-min-max.png
  test/fixtures/scale.time/ticks-reverse-linear.js
  test/fixtures/scale.time/ticks-reverse-linear.png
  test/fixtures/scale.time/ticks-reverse-offset.js
  test/fixtures/scale.time/ticks-reverse-offset.png
  test/fixtures/scale.time/ticks-reverse-series-max.js
  test/fixtures/scale.time/ticks-reverse-series-max.png
  test/fixtures/scale.time/ticks-reverse-series-min-max.js
  test/fixtures/scale.time/ticks-reverse-series-min-max.png
  test/fixtures/scale.time/ticks-reverse-series-min.js
  test/fixtures/scale.time/ticks-reverse-series-min.png
  test/fixtures/scale.time/ticks-reverse-series.js
  test/fixtures/scale.time/ticks-reverse-series.png
  test/fixtures/scale.time/ticks-reverse.js
  test/fixtures/scale.time/ticks-reverse.png
  test/fixtures/scale.time/ticks-round.js
  test/fixtures/scale.time/ticks-round.png
  test/fixtures/scale.time/ticks-stepsize.js
  test/fixtures/scale.time/ticks-stepsize.png
  test/fixtures/scale.time/ticks-unit.js
  test/fixtures/scale.time/ticks-unit.png
  test/specs/scale.time.tests.js
Labels: type: chore
