Repository chartjs/Chart.js, pull requests merged in 2020-06, with the labels that each got.

#7451 Indicate that axis callbacks are at top level of options
  docs/docs/axes/index.md
Labels: type: documentation

#7449 Radial Linear Scale: Compute Value based on distance from center
  src/scales/scale.radialLinear.js
  test/specs/scale.radialLinear.tests.js
Labels: type: enhancement

#7455 Use verbose build in dev mode
  karma.conf.js
Labels: type: bug, type: infrastructure

#7459 Enable custom legend box heights
  docs/docs/configuration/legend.md
  src/plugins/plugin.legend.js
  test/specs/plugin.legend.tests.js
Labels: type: enhancement

#7468 Stacked scatter chart
  src/core/core.datasetController.js
  test/fixtures/controller.line/stacking/stacked-scatter.js
  test/fixtures/controller.line/stacking/stacked-scatter.png
Labels: type: bug

#7399 Document the context properties for ticks
  docs/docs/axes/cartesian/category.md
  docs/docs/axes/cartesian/index.md
  docs/docs/axes/cartesian/linear.md
  docs/docs/axes/cartesian/logarithmic.md
  docs/docs/axes/cartesian/time.md
  docs/docs/axes/index.md
  docs/docs/axes/labelling.md
  docs/docs/axes/radial/index.md
  docs/docs/axes/styling.md
  docs/docs/general/options.md
  docs/docs/general/performance.md
  docs/src/css/custom.css
Labels: type: documentation

#7480 Remove unused parameter
  src/scales/scale.linearbase.js
Labels: type: chore

#7484 Fix link to animations docs
  docs/docs/developers/api.md
  docs/docs/getting-started/v3-migration.md
Labels: type: documentation

#7488 Update horizontal bar chart default tooltip mode
  docs/docs/getting-started/v3-migration.md
  src/controllers/controller.horizontalBar.js
Labels: breaking change

#7471 Radial scale scriptable options
  docs/docs/axes/radial/linear.md
  docs/docs/getting-started/v3-migration.md
  src/helpers/helpers.core.js
  src/scales/scale.radialLinear.js
  test/fixtures/scale.radialLinear/anglelines-indexable.js
  test/fixtures/scale.radialLinear/anglelines-indexable.png
  test/fixtures/scale.radialLinear/anglelines-scriptable.js
  test/fixtures/scale.radialLinear/anglelines-scriptable.png
  test/fixtures/scale.radialLinear/gridlines-scriptable.js
  test/fixtures/scale.radialLinear/gridlines-scriptable.png
  test/specs/helpers.core.tests.js
Labels: type: documentation, type: enhancement

#7492 Fix measureText bug in spriting
  test/fixtures/core.layouts/long-labels.js
  test/fixtures/core.layouts/long-labels.png
  test/fixtures/scale.category/ticks-from-data.png
  test/fixtures/scale.time/autoskip-major.js
  test/fixtures/scale.time/autoskip-major.png
  test/fixtures/scale.time/custom-parser.png
  test/fixtures/scale.time/data-ty.js
  test/fixtures/scale.time/data-ty.png
  test/fixtures/scale.time/data-xy.js
  test/fixtures/scale.time/data-xy.png
  test/fixtures/scale.time/labels-date.png
  test/fixtures/scale.time/labels-strings.png
  test/fixtures/scale.time/labels.png
  test/fixtures/scale.time/source-auto-linear.png
  test/fixtures/scale.time/source-auto-series.png
  test/fixtures/scale.time/source-data-linear.png
  test/fixtures/scale.time/source-data-series-offset-min-max.png
  test/fixtures/scale.time/source-data-series.png
  test/fixtures/scale.time/source-labels-linear-offset-min-max.png
  test/fixtures/scale.time/source-labels-linear.png
  test/fixtures/scale.time/source-labels-series-offset-min-max.png
  test/fixtures/scale.time/source-labels-series.png
  test/fixtures/scale.time/ticks-capacity.png
  test/fixtures/scale.time/ticks-minunit.png
  test/fixtures/scale.time/ticks-reverse-linear-min-max.png
  test/fixtures/scale.time/ticks-reverse-linear.png
  test/fixtures/scale.time/ticks-reverse-offset.png
  test/fixtures/scale.time/ticks-reverse-series-max.png
  test/fixtures/scale.time/ticks-reverse-series-min-max.png
  test/fixtures/scale.time/ticks-reverse-series-min.png
  test/fixtures/scale.time/ticks-reverse-series.png
  test/fixtures/scale.time/ticks-reverse.png
  test/fixtures/scale.time/ticks-round.png
  test/fixtures/scale.time/ticks-stepsize.png
  test/fixtures/scale.time/ticks-unit.png
  test/specs/core.layouts.tests.js
  test/spriting.js
Labels: type: bug, type: chore, type: infrastructure

#7491 Replace ineffective test with a fixture
  test/fixture.js
  test/fixtures/scale.linear/tiny-numbers.js
  test/fixtures/scale.linear/tiny-numbers.png
  test/specs/scale.linear.tests.js
Labels: type: chore

#7502 Read Title font options from correct place
  src/plugins/plugin.title.js
Labels: type: bug

#7508 Remove lineHeight property from LegendTitle doc
  docs/docs/configuration/legend.md
Labels: type: documentation

#7514 Replace horizontalBar with indexAxis: 'y'
  docs/docs/charts/bar.mdx
  docs/docs/configuration/elements.md
  docs/docs/developers/charts.md
  docs/docs/general/interactions/modes.md
  docs/docs/getting-started/v3-migration.md
  samples/charts/bar/horizontal.html
  src/controllers/controller.bar.js
  src/controllers/controller.horizontalBar.js
  src/controllers/controller.line.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/controllers/index.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/elements/element.line.js
  src/elements/element.rectangle.js
  test/fixtures/controller.bar/floatBar/data-as-objects-horizontal.js
  test/fixtures/controller.bar/floatBar/float-bar-horizontal.json
  test/fixtures/controller.bar/floatBar/float-bar-stacked-horizontal.json
  test/fixtures/controller.bar/horizontal-borders.js
  test/fixtures/core.scale/label-offset-vertical-axes.json
  test/fixtures/core.scale/tick-drawing.json
  test/fixtures/mixed/bar+line.js
  test/fixtures/mixed/bar+line.png
  test/fixtures/scale.category/ticks-from-data.js
  test/specs/controller.bar.tests.js
  test/specs/controller.radar.tests.js
  test/specs/core.interaction.tests.js
  test/specs/mixed.tests.js
  test/specs/plugin.tooltip.tests.js
  test/specs/scale.category.tests.js
  test/specs/scale.linear.tests.js
  test/specs/scale.logarithmic.tests.js
Labels: type: enhancement

#7489 Parse from custom properties in data
  docs/docs/axes/cartesian/time.md
  docs/docs/general/data-structures.md
  docs/docs/getting-started/v3-migration.md
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/core/core.datasetController.js
  src/core/core.scale.js
  src/helpers/helpers.core.js
  src/scales/scale.time.js
  test/fixtures/controller.bar/bar-thickness-no-overlap.json
  test/fixtures/controller.bar/data/parsing.js
  test/fixtures/controller.bar/data/parsing.png
  test/fixtures/scale.time/data-ty.js
  test/specs/core.datasetController.tests.js
  test/specs/scale.time.tests.js
Labels: type: enhancement

#7522 Tooltip: Provide argument for custom callback
  src/plugins/plugin.tooltip.js
Labels: type: bug

#7521 Remove babel from tests
  karma.conf.js
Labels: type: chore

#7525 Split time scale into time and timeseries
  docs/docs/axes/cartesian/time.md
  docs/docs/axes/cartesian/timeseries.md
  docs/docs/getting-started/v3-migration.md
  src/helpers/helpers.collection.js
  src/scales/index.js
  src/scales/scale.time.js
  src/scales/scale.timeseries.js
  test/fixtures/scale.time/source-auto-series.js
  test/fixtures/scale.time/source-data-series-offset-min-max.js
  test/fixtures/scale.time/source-data-series.js
  test/fixtures/scale.time/source-labels-series-offset-min-max.js
  test/fixtures/scale.time/source-labels-series.js
  test/fixtures/scale.time/ticks-reverse-series-max.js
  test/fixtures/scale.time/ticks-reverse-series-min-max.js
  test/fixtures/scale.time/ticks-reverse-series-min.js
  test/fixtures/scale.time/ticks-reverse-series.js
  test/specs/scale.time.tests.js
Labels: breaking change, type: enhancement

#7528 Update the legend object during beforeUpdate
  src/plugins/plugin.legend.js
Labels: type: bug

#7530 Mark parameter as optional
  src/controllers/controller.line.js
  src/controllers/controller.radar.js
  src/core/core.datasetController.js
Labels: type: documentation

#7532 Remove lookup table from TimeScale
  src/scales/scale.time.js
  src/scales/scale.timeseries.js
Labels: type: chore

#7536 Move timeseries fixtures to their own directory
  test/fixtures/scale.time/source-data-series-offset-min-max.png
  test/fixtures/scale.time/source-labels-series-offset-min-max.png
  test/fixtures/scale.time/ticks-reverse-series-max.png
  test/fixtures/scale.time/ticks-reverse-series-min-max.png
  test/fixtures/scale.time/ticks-reverse-series-min.png
  test/fixtures/scale.time/ticks-reverse-series.png
  test/fixtures/scale.timeseries/source-auto.js
  test/fixtures/scale.timeseries/source-auto.png
  test/fixtures/scale.timeseries/source-data-offset-min-max.js
  test/fixtures/scale.timeseries/source-data-offset-min-max.png
  test/fixtures/scale.timeseries/source-data.js
  test/fixtures/scale.timeseries/source-data.png
  test/fixtures/scale.timeseries/source-labels-offset-min-max.js
  test/fixtures/scale.timeseries/source-labels-offset-min-max.png
  test/fixtures/scale.timeseries/source-labels.js
  test/fixtures/scale.timeseries/source-labels.png
  test/fixtures/scale.timeseries/ticks-reverse-max.js
  test/fixtures/scale.timeseries/ticks-reverse-max.png
  test/fixtures/scale.timeseries/ticks-reverse-min-max.js
  test/fixtures/scale.timeseries/ticks-reverse-min-max.png
  test/fixtures/scale.timeseries/ticks-reverse-min.js
  test/fixtures/scale.timeseries/ticks-reverse-min.png
  test/fixtures/scale.timeseries/ticks-reverse.js
  test/fixtures/scale.timeseries/ticks-reverse.png
Labels: type: chore

#7469 Update tooltip when the display position changes
  src/plugins/plugin.tooltip.js
  test/specs/plugin.tooltip.tests.js
Labels: type: bug

#7562 Remove "for bugs" from bug issue template
  .github/ISSUE_TEMPLATE/BUG.md
Labels: type: infrastructure

#7557 Fix typo in sample
  samples/tooltips/custom-pie.html
Labels: type: documentation

#7552 Fix financial sample
  samples/scales/financial.html
Labels: type: documentation

#7556 Add parameters to tooltip filter option
  docs/docs/configuration/tooltip.md
  docs/docs/getting-started/v3-migration.md
  src/plugins/plugin.tooltip.js
  test/specs/plugin.tooltip.tests.js
Labels: breaking change, type: enhancement

#7559 Generate ticks from small to large
  docs/docs/getting-started/v3-migration.md
  src/scales/scale.linear.js
  src/scales/scale.linearbase.js
  test/fixtures/core.layouts/long-labels.png
  test/specs/core.layouts.tests.js
  test/specs/core.ticks.tests.js
  test/specs/plugin.tooltip.tests.js
  test/specs/scale.linear.tests.js
Labels: breaking change, type: enhancement

#7558 Update time scale docs to be Moment agnostic
  docs/docs/axes/cartesian/time.md
Labels: type: documentation

#7565 Fix tooltip caret border when caret is on right or bottom
  src/plugins/plugin.tooltip.js
Labels: type: bug
