Repository chartjs/Chart.js, pull requests merged in 2020-11, with the labels that each got.

#7988 Use TypeScript syntax highlight for TypeScript code
  docs/docs/developers/charts.md
Labels: type: documentation

#7987 Fix typo in test options
  test/specs/controller.bar.tests.js
Labels: type: chore, type: infrastructure

#7981 Preserve scriptable context
  docs/docs/general/options.md
  samples/animations/delay.html
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.scale.js
  test/fixtures/controller.line/backgroundColor/scriptable.js
  test/fixtures/controller.line/borderColor/scriptable.js
  test/fixtures/controller.line/borderWidth/scriptable.js
  test/fixtures/controller.radar/backgroundColor/scriptable.js
  test/fixtures/controller.radar/borderColor/scriptable.js
  test/fixtures/controller.radar/borderWidth/scriptable.js
Labels: type: enhancement

#7989 Delay resize to just before draw when animating
  docs/docs/getting-started/v3-migration.md
  src/core/core.controller.js
  test/specs/core.controller.tests.js
  types/core/index.d.ts
Labels: breaking change, type: bug

#7996 Remove use of null propagation operator since it's still in a draft state
  src/core/core.datasetController.js
Labels: type: bug

#7997 Change version to 3.0.0-mater and update deps
  package-lock.json
  package.json
Labels: type: infrastructure

#8006 Use same merging logic for init and update
  src/core/core.config.js
  test/specs/core.controller.tests.js
  test/utils.js
Labels: type: bug

#8001 [types][beta-5] fixed stacked scale, changed default type for data.labels
  docs/docs/general/data-structures.md
  types/controllers/index.d.ts
  types/interfaces.d.ts
  types/scales/index.d.ts
Labels: type: types

#8013 When data is removed, remove from stacks too
  src/core/core.controller.js
  src/core/core.datasetController.js
  test/specs/core.datasetController.tests.js
Labels: type: bug

#8015 Normalize rotation and circumference resolution
  src/controllers/controller.doughnut.js
Labels: type: chore

#8014 Remove +-10px limit from bar controller
  src/controllers/controller.bar.js
  test/specs/controller.bar.tests.js
Labels: type: chore

#8017 Remove I prefix from TS types
  docs/docs/developers/charts.md
  src/core/core.controller.js
  src/core/core.interaction.js
  src/core/core.layouts.js
  src/core/core.plugins.js
  src/platform/platform.base.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.tooltip.js
  types/controllers/index.d.ts
  types/core/index.d.ts
  types/core/interfaces.d.ts
  types/elements/index.d.ts
  types/helpers/helpers.canvas.d.ts
  types/helpers/helpers.collection.d.ts
  types/helpers/helpers.core.d.ts
  types/helpers/helpers.curve.d.ts
  types/helpers/helpers.options.d.ts
  types/helpers/helpers.rtl.d.ts
  types/interfaces.d.ts
  types/platform/index.d.ts
  types/plugins/index.d.ts
  types/scales/index.d.ts
Labels: breaking change, type: types

#8007 Add type to context objects
  docs/docs/general/options.md
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.scale.js
Labels: type: enhancement

#8018 Bubble: Use point.size() in getMaxOverflow
  src/controllers/controller.bubble.js
Labels: type: chore

#8024 dataset tooltip now shows correctly
  src/plugins/plugin.tooltip.js
Labels: type: bug

#8027 [beta.6][types] fix inconsistency in types for LABEL
  types/core/index.d.ts
  types/interfaces.d.ts
Labels: type: types

#8029 Change to coveralls action
  .github/workflows/ci.yml
Labels: type: infrastructure

#8028 Add tests and clean up resolveObjectKey helper
  src/helpers/helpers.core.js
  test/specs/helpers.core.tests.js
Labels: type: chore

#8033 Record test coverage per browser
  .github/workflows/ci.yml
  karma.conf.js
Labels: type: infrastructure

#8034 Improve helpers.color test coverage
  test/specs/helpers.color.tests.js
Labels: type: infrastructure

#8036 Try and get the version number without a `v`
  .github/workflows/npmpublish.yml
Labels: type: chore

#8037 documentation error
  docs/docs/configuration/tooltip.md
Labels: type: documentation

#8039 Fix import names in integration example
  docs/docs/getting-started/integration.md
Labels: type: documentation

#8041 Fix broken link
  samples/samples.js
Labels: type: documentation

#8047 Update v3-migration.md
  docs/docs/getting-started/v3-migration.md
Labels: type: documentation

#8049 Events: Only render when needed
  src/core/core.controller.js
Labels: type: bug

#8052 Chart.register: preserve existing defaults
  src/core/core.typedRegistry.js
  test/specs/core.registry.tests.js
Labels: type: bug

#8053 CategoryScale: automatically add missing labels
  src/scales/scale.category.js
  test/fixtures/controller.bar/bar-skip-null-object-data.js
  test/specs/scale.category.tests.js
Labels: type: enhancement

#8057 Refactor/cleanup range option handling
  src/core/core.scale.js
  src/helpers/helpers.core.js
  src/scales/scale.linear.js
  src/scales/scale.linearbase.js
  src/scales/scale.logarithmic.js
Labels: type: chore

#8048 Add plugins to CoreChartOptions
  types/core/interfaces.d.ts
Labels: type: types

#8009 Drop legacy browser support
  .browserslistrc
  .eslintrc.yml
  babel.config.json
  docs/docs/developers/index.md
  karma.conf.js
  package-lock.json
  package.json
  rollup.config.js
  src/plugins/plugin.legend.js
Labels: breaking change

#8062 Unify cartesian scale tick order
  src/scales/scale.logarithmic.js
  test/specs/core.ticks.tests.js
  test/specs/scale.logarithmic.tests.js
Labels: breaking change

#8060 Enable bounds option to all cartesian axes
  src/core/core.scale.js
  src/scales/scale.category.js
  src/scales/scale.linearbase.js
  src/scales/scale.logarithmic.js
  test/specs/scale.category.tests.js
  test/specs/scale.linear.tests.js
  test/specs/scale.logarithmic.tests.js
Labels: type: enhancement

#8061 Update axis documentation
  docs/docs/axes/_common.md
  docs/docs/axes/_common_ticks.md
  docs/docs/axes/cartesian/_common.md
  docs/docs/axes/cartesian/_common_ticks.md
  docs/docs/axes/cartesian/category.mdx
  docs/docs/axes/cartesian/index.mdx
  docs/docs/axes/cartesian/linear.md
  docs/docs/axes/cartesian/linear.mdx
  docs/docs/axes/cartesian/logarithmic.md
  docs/docs/axes/cartesian/logarithmic.mdx
  docs/docs/axes/cartesian/time.mdx
  docs/docs/axes/index.mdx
  docs/docs/axes/radial/linear.mdx
  docs/docs/axes/styling.mdx
  docs/docs/general/fonts.md
  docs/sidebars.js
Labels: type: documentation

#8063 Remove set-env from actions
  .github/workflows/ci.yml
  .github/workflows/npmpublish.yml
Labels: type: infrastructure

#8065 Add missing import to styling.mdx
  docs/docs/axes/styling.mdx
Labels: type: documentation

#8071 v2 note not nessecary in v3 docs and update example
  docs/docs/developers/api.md
Labels: type: documentation

#8070 fix broken url in docs
  docs/docs/axes/cartesian/timeseries.md
  docs/docs/axes/radial/index.md
Labels: type: documentation

#8076 Remove classic style extensions from docs/tests
  docs/docs/developers/axes.md
  docs/docs/developers/charts.md
  test/specs/core.registry.tests.js
Labels: type: documentation

#8074 Rename uppercase types to camel case
  types/core/index.d.ts
  types/interfaces.d.ts
Labels: breaking change, type: types

#8080 made scatter chart a lot better readable, removed unnecesarry notes
  docs/docs/charts/area.md
  docs/docs/charts/scatter.mdx
Labels: type: documentation

#8050 Allow single parameter to Defaults.set
  src/core/core.defaults.js
  types/core/index.d.ts
Labels: type: enhancement

#8066 Align font options with CSS
  docs/docs/axes/_common_ticks.md
  docs/docs/general/fonts.md
  docs/docs/getting-started/v3-migration.md
  src/core/core.defaults.js
  src/core/core.scale.js
  src/core/core.typedRegistry.js
  src/elements/element.arc.js
  src/elements/element.bar.js
  src/elements/element.line.js
  src/elements/element.point.js
  src/helpers/helpers.options.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.title.js
  src/plugins/plugin.tooltip.js
  src/scales/scale.radialLinear.js
  test/specs/controller.bubble.tests.js
  test/specs/controller.radar.tests.js
  test/specs/core.datasetController.tests.js
  test/specs/core.scale.tests.js
  test/specs/helpers.options.tests.js
  test/specs/plugin.title.tests.js
  test/specs/plugin.tooltip.tests.js
  test/specs/scale.radialLinear.tests.js
Labels: breaking change

#8075 Switch to eslint-plugin-es
  .eslintrc.yml
  package-lock.json
  package.json
  src/core/core.config.js
  src/core/core.controller.js
  src/helpers/index.js
  src/index.js
Labels: type: infrastructure

#8081 coppied to wrong place in file, backgroundColor should be in the data…
  docs/docs/charts/scatter.mdx
Labels: type: documentation

#8082 Do not use offsetX/Y in shadow DOM
  src/helpers/helpers.dom.js
  test/specs/helpers.dom.tests.js
  test/utils.js
Labels: type: bug

#8093 Update interpolation-modes sample to new defaults
  samples/charts/line/interpolation-modes.html
Labels: type: documentation

#8087 Improve test coverage
  src/core/core.typedRegistry.js
  src/helpers/helpers.dom.js
  test/specs/core.animations.tests.js
  test/specs/core.defaults.tests.js
Labels: type: infrastructure

#8097 Fix disabling hover
  src/core/core.config.js
  test/specs/core.controller.tests.js
Labels: type: bug

#8099 fixed samples: area dataset (line), Radar and Logarithmic scale scatter
  samples/charts/area/analyser.js
  samples/scales/logarithmic/scatter.html
Labels: type: documentation

#8090 Restore `datasets` namespace (revert 6955)
  docs/docs/configuration/index.md
  docs/docs/getting-started/v3-migration.md
  src/core/core.config.js
  src/core/core.datasetController.js
  test/fixtures/controller.bar/bar-thickness-multiple.json
  test/fixtures/controller.bar/bar-thickness-no-overlap.json
  test/fixtures/controller.bar/bar-thickness-offset.json
  test/fixtures/controller.bar/bar-thickness-reverse.json
  test/fixtures/controller.bar/bar-thickness-stacked.json
  test/fixtures/controller.bar/stacking/logarithmic-strings.js
  test/fixtures/controller.bar/stacking/logarithmic.js
  test/fixtures/plugin.filler/fill-line-dataset-interpolated.js
  test/specs/controller.bar.tests.js
  test/specs/controller.line.tests.js
Labels: breaking change

#8104 Title plugin cleanup
  samples/title/alignment.html
  src/plugins/plugin.title.js
Labels: type: chore

#8102 Unify signature of plugin hooks
  docs/docs/getting-started/v3-migration.md
  src/core/core.controller.js
  src/core/core.plugins.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.tooltip.js
  test/specs/core.plugin.tests.js
  test/specs/platform.dom.tests.js
  types/core/index.d.ts
Labels: breaking change, type: enhancement

#8110 fix color type & add background and border color
  types/core/interfaces.d.ts
Labels: type: types

#8111 LineElement: no fill by default
  docs/docs/charts/area.md
  docs/docs/charts/bar.mdx
  docs/docs/charts/line.mdx
  docs/docs/charts/radar.mdx
  docs/docs/configuration/elements.md
  docs/docs/getting-started/v3-migration.md
  src/elements/element.line.js
  test/fixtures/controller.line/backgroundColor/scriptable.js
  test/fixtures/controller.line/backgroundColor/value.js
  test/fixtures/controller.line/showLine/false.js
  test/fixtures/scale.time/negative-times.js
  test/fixtures/scale.time/negative-times.png
Labels: breaking change

#8103 Add new hooks for plugins
  docs/docs/getting-started/v3-migration.md
  src/core/core.plugins.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.title.js
  test/specs/core.controller.tests.js
  test/specs/plugin.legend.tests.js
  test/specs/plugin.title.tests.js
  types/core/index.d.ts
Labels: type: enhancement

#8107 Fix typo in performance.md
  docs/docs/general/performance.md
Labels: type: documentation

#8113 Fix/area fill and chart titles
  docs/docs/developers/updates.md
  docs/docs/getting-started/v3-migration.md
  samples/advanced/progress-bar.html
  samples/charts/area/line-boundaries.html
  samples/charts/area/line-stacked.html
  samples/charts/bar/stacked.html
  samples/charts/line/multi-axis.html
  samples/charts/line/stepped.html
  samples/charts/multi-series-pie.html
  samples/charts/radar-skip-points.html
  samples/charts/scatter/basic.html
  samples/charts/scatter/multi-axis.html
  samples/index.html
  samples/samples.js
  samples/scales/axis-center-position.html
  samples/scales/filtering-labels.html
  samples/scales/gridlines-display.html
  samples/scales/gridlines-scriptable.html
  samples/scales/gridlines-style.html
  samples/scales/linear/min-max.html
  samples/scales/logarithmic/line.html
  samples/scales/logarithmic/scatter.html
  samples/scales/multiline-labels.html
  samples/scales/non-numeric-y.html
  samples/scales/time/combo.html
  samples/scales/time/line-max-span.html
  samples/scales/time/line-point-data.html
  samples/scales/time/line.html
  samples/scales/toggle-scale-type.html
Labels: type: documentation
