Repository chartjs/Chart.js, pull requests merged in 2020-10, with the labels that each got.

#7830 Include dist/chunks in the NPM package
  package-lock.json
  package.json
Labels: type: bug, type: infrastructure

#7828 Allow contextmenu (right click) events to trigger the onClick handler
  src/core/core.controller.js
Labels: type: bug

#7835 Fix tooltip font options in sample
  samples/tooltips/border.html
Labels: type: documentation

#7836 Use full height for fullWidth box when left/right
  src/core/core.layouts.js
Labels: type: bug

#7837 Clone cached options if enableOptionSharing!=true
  src/core/core.datasetController.js
  test/specs/core.datasetController.tests.js
Labels: type: bug

#7833 Enable per-dataset circumference and rotation for pie/doughnut charts
  docs/docs/charts/doughnut.mdx
  docs/docs/getting-started/v3-migration.md
  src/controllers/controller.doughnut.js
  test/fixtures/controller.doughnut/doughnut-circumference-over-2pi.json
  test/fixtures/controller.doughnut/doughnut-circumference-per-dataset.js
  test/fixtures/controller.doughnut/doughnut-circumference-per-dataset.png
  test/fixtures/controller.doughnut/doughnut-circumference.json
  test/fixtures/controller.doughnut/doughnut-rotation-per-dataset.js
  test/fixtures/controller.doughnut/doughnut-rotation-per-dataset.png
  test/fixtures/controller.doughnut/pie-circumference.json
  test/specs/controller.doughnut.tests.js
  types/controllers/index.d.ts
Labels: breaking change, type: enhancement

#7841 Remove enum types
  docs/docs/developers/charts.md
  types/core/index.d.ts
  types/interfaces.d.ts
Labels: type: types

#7844 JS test files should have tabs to correctly lint
  test/fixtures/controller.doughnut/doughnut-circumference-per-dataset.js
  test/fixtures/controller.doughnut/doughnut-rotation-per-dataset.js
Labels: type: chore

#7843 Provide method to lookup a chart from a canvas
  docs/docs/developers/api.md
  docs/docs/getting-started/v3-migration.md
  src/core/core.controller.js
  test/specs/core.controller.tests.js
  types/core/index.d.ts
Labels: breaking change, type: enhancement

#7848 Limit pixel values further to 16bit integer range
  src/core/core.scale.js
  src/helpers/helpers.math.js
Labels: type: bug

#7847 Normalize context creation for option resolution
  src/controllers/controller.bubble.js
  src/controllers/controller.polarArea.js
  src/core/core.datasetController.js
  src/core/core.scale.js
  src/scales/scale.radialLinear.js
Labels: type: chore

#7845 Provide APIs to set active (hovered) and tooltip elements.
  docs/docs/developers/api.md
  samples/advanced/programmatic-events.html
  samples/samples.js
  src/core/core.controller.js
  src/plugins/plugin.tooltip.js
  test/specs/core.controller.tests.js
  test/specs/plugin.tooltip.tests.js
  types/core/index.d.ts
  types/plugins/index.d.ts
Labels: type: enhancement

#7851 Enable custom sorting of the legend items
  docs/docs/configuration/legend.md
  src/plugins/plugin.legend.js
  test/specs/plugin.legend.tests.js
  types/plugins/index.d.ts
Labels: type: enhancement

#7849 Add new option, `skipNull` to bar charts that enables skipping null values
  docs/docs/charts/bar.mdx
  src/controllers/controller.bar.js
  test/fixtures/controller.bar/bar-skip-null-object-data.js
  test/fixtures/controller.bar/bar-skip-null-object-data.png
  test/fixtures/controller.bar/bar-skip-null.js
  test/fixtures/controller.bar/bar-skip-null.png
  types/controllers/index.d.ts
Labels: type: enhancement

#7852 Add maxWidth/maxHeight options for legend
  docs/docs/configuration/legend.md
  src/controllers/controller.doughnut.js
  src/controllers/controller.polarArea.js
  src/core/core.scale.js
  src/elements/element.arc.js
  src/helpers/helpers.canvas.js
  src/helpers/helpers.dom.js
  src/helpers/helpers.easing.js
  src/helpers/helpers.math.js
  src/plugins/plugin.filler.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.title.js
  src/scales/scale.radialLinear.js
Labels: type: enhancement

#7862 beginAtZero support for logarithmic
  src/scales/scale.logarithmic.js
  test/fixtures/controller.bar/stacking/logarithmic-strings.png
  test/fixtures/controller.bar/stacking/logarithmic.png
  test/specs/scale.logarithmic.tests.js
Labels: type: enhancement

#7865 Add tooltip positioning sample
  samples/samples.js
  samples/tooltips/positioning-custom.html
Labels: type: documentation

#7872 Fix typo in const name
  src/helpers/helpers.dom.js
Labels: type: chore

#7874 Cartesian axis label cross alignment
  docs/docs/axes/cartesian/index.mdx
  docs/docs/axes/styling.md
  src/core/core.scale.js
  test/fixtures/core.scale/crossAlignment/cross-align-bottom-center.js
  test/fixtures/core.scale/crossAlignment/cross-align-bottom-center.png
  test/fixtures/core.scale/crossAlignment/cross-align-bottom-far.js
  test/fixtures/core.scale/crossAlignment/cross-align-bottom-far.png
  test/fixtures/core.scale/crossAlignment/cross-align-bottom-near.js
  test/fixtures/core.scale/crossAlignment/cross-align-bottom-near.png
  test/fixtures/core.scale/crossAlignment/cross-align-left-center.js
  test/fixtures/core.scale/crossAlignment/cross-align-left-center.png
  test/fixtures/core.scale/crossAlignment/cross-align-left-far.js
  test/fixtures/core.scale/crossAlignment/cross-align-left-far.png
  test/fixtures/core.scale/crossAlignment/cross-align-left-near.js
  test/fixtures/core.scale/crossAlignment/cross-align-left-near.png
  test/fixtures/core.scale/crossAlignment/cross-align-right-center.js
  test/fixtures/core.scale/crossAlignment/cross-align-right-center.png
  test/fixtures/core.scale/crossAlignment/cross-align-right-far.js
  test/fixtures/core.scale/crossAlignment/cross-align-right-far.png
  test/fixtures/core.scale/crossAlignment/cross-align-right-near.js
  test/fixtures/core.scale/crossAlignment/cross-align-right-near.png
  test/fixtures/core.scale/crossAlignment/cross-align-top-center.js
  test/fixtures/core.scale/crossAlignment/cross-align-top-center.png
  test/fixtures/core.scale/crossAlignment/cross-align-top-far.js
  test/fixtures/core.scale/crossAlignment/cross-align-top-far.png
  test/fixtures/core.scale/crossAlignment/cross-align-top-near.js
  test/fixtures/core.scale/crossAlignment/cross-align-top-near.png
  types/scales/index.d.ts
Labels: type: enhancement

#7870 Ability to toggle individual bar visibility
  docs/docs/developers/api.md
  src/controllers/controller.bar.js
  test/specs/controller.bar.tests.js
Labels: type: enhancement

#7871 Polar Area `elements.arc.angle` option now returns degrees
  docs/docs/getting-started/v3-migration.md
  src/controllers/controller.polarArea.js
  test/fixtures/controller.polarArea/angle-array.json
  test/fixtures/controller.polarArea/border-align-center.json
  test/fixtures/controller.polarArea/border-align-inner.json
Labels: breaking change

#7868 Update custom tooltips to work with multiple charts on a page
  samples/tooltips/custom-line.html
  samples/tooltips/custom-pie.html
Labels: type: documentation

#7875 docs: Grammar fixes for cartesian and radial docs
  docs/docs/axes/cartesian/category.md
  docs/docs/axes/cartesian/index.mdx
  docs/docs/axes/cartesian/linear.md
  docs/docs/axes/cartesian/logarithmic.md
  docs/docs/axes/cartesian/time.md
  docs/docs/axes/index.md
  docs/docs/axes/labelling.md
  docs/docs/axes/radial/linear.md
  docs/docs/axes/styling.md
  docs/docs/charts/area.md
  docs/docs/charts/bar.mdx
  docs/docs/charts/bubble.mdx
  docs/docs/charts/doughnut.mdx
  docs/docs/charts/line.mdx
  docs/docs/charts/mixed.mdx
  docs/docs/charts/polar.mdx
  docs/docs/charts/radar.mdx
Labels: type: documentation

#7878 Add release-drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: type: chore, type: infrastructure

#7879 Update release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: type: infrastructure

#7827 Remove release branch workflow
  .github/workflows/ci.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/npmpublish.yml
  .travis.yml
  README.md
  scripts/deploy-docs.sh
  scripts/docs-config.sh
  scripts/publish.sh
  scripts/release.sh
Labels: type: chore, type: infrastructure

#7882 Ensure scripts are marked as executable in git
  scripts/deploy-docs.sh
  scripts/publish.sh
Labels: type: chore

#7884 Tune release-drafter settings
  .github/release-drafter.yml
Labels: type: infrastructure

#7886 Shorten alignment settings for axes
  docs/docs/axes/cartesian/index.mdx
  samples/scales/label-text-alignment.html
  src/core/core.scale.js
  test/fixtures/core.scale/crossAlignment/cross-align-bottom-center.js
  test/fixtures/core.scale/crossAlignment/cross-align-bottom-far.js
  test/fixtures/core.scale/crossAlignment/cross-align-bottom-near.js
  test/fixtures/core.scale/crossAlignment/cross-align-left-center.js
  test/fixtures/core.scale/crossAlignment/cross-align-left-far.js
  test/fixtures/core.scale/crossAlignment/cross-align-left-near.js
  test/fixtures/core.scale/crossAlignment/cross-align-right-center.js
  test/fixtures/core.scale/crossAlignment/cross-align-right-far.js
  test/fixtures/core.scale/crossAlignment/cross-align-right-near.js
  test/fixtures/core.scale/crossAlignment/cross-align-top-center.js
  test/fixtures/core.scale/crossAlignment/cross-align-top-far.js
  test/fixtures/core.scale/crossAlignment/cross-align-top-near.js
  test/fixtures/core.scale/label-align-center.js
  test/fixtures/core.scale/label-align-end.js
  test/fixtures/core.scale/label-align-start.js
  types/scales/index.d.ts
Labels: breaking change, type: enhancement

#7892 Fix double env
  .github/workflows/npmpublish.yml
Labels: type: infrastructure

#7893 Expand filename
  .github/workflows/npmpublish.yml
  MAINTAINING.md
Labels: type: infrastructure

#7898 Remove circular dependencies from helpers
  src/helpers/helpers.canvas.js
  src/helpers/helpers.dom.js
  src/helpers/helpers.easing.js
Labels: type: chore

#7897 Share min sample size with all bars on same scale
  src/controllers/controller.bar.js
  src/core/core.scale.js
  test/fixtures/controller.bar/bar-thickness-min-interval-multi.json
  test/fixtures/controller.bar/bar-thickness-min-interval-multi.png
Labels: type: bug

#7899 Fix: beginAtZero for logarighmic
  src/scales/scale.logarithmic.js
  test/specs/scale.logarithmic.tests.js
Labels: type: bug

#7902 Renamed .browserlistrc -> .browserslistrc
  .browserslistrc
Labels: type: chore

#7900 Document `getElementsAtEventForMode` and remove APIs that can be replaced by it
  docs/docs/developers/api.md
  docs/docs/getting-started/v3-migration.md
  src/core/core.controller.js
  types/core/index.d.ts
Labels: breaking change, type: documentation

#7905 Ability to fill a line to a specified value along an axis
  docs/docs/charts/area.md
  samples/charts/area/analyser.js
  samples/charts/area/line-datasets.html
  samples/charts/area/radar.html
  src/plugins/plugin.filler.js
  test/fixtures/plugin.filler/fill-line-value.json
  test/fixtures/plugin.filler/fill-line-value.png
  test/fixtures/plugin.filler/fill-radar-value.json
  test/fixtures/plugin.filler/fill-radar-value.png
  types/plugins/index.d.ts
Labels: type: enhancement

#7904 Bar chart base value overrides
  docs/docs/charts/bar.mdx
  src/controllers/controller.bar.js
  test/fixtures/controller.bar/bar-base-value.js
  test/fixtures/controller.bar/bar-base-value.png
  types/elements/index.d.ts
Labels: type: enhancement

#7883 Fix Maximum call stack size exception in computeLabelSizes
  src/core/core.scale.js
Labels: version: 2

#7906 Fix Maximum call stack size exception in _computeLabelSizes
  src/core/core.scale.js
Labels: type: bug

#7907 Added in note for browserslist
  docs/docs/developers/index.md
Labels: type: chore

#7909 Fix version numbers in Developers section of docs
  docs/docs/developers/index.md
Labels: type: documentation

#7911 Stop deploying docs / drafting releases from forks
  .github/workflows/deploy-docs.yml
  .github/workflows/release-drafter.yml
Labels: type: chore, type: infrastructure

#7913 some minor typo fix
  src/controllers/controller.doughnut.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.scale.js
  src/elements/element.arc.js
Labels: type: documentation

#7908 Reduce tooltip implied padding at top and bottom edges of the canvas
  src/plugins/plugin.tooltip.js
  test/fixtures/core.tooltip/opacity.js
  test/fixtures/core.tooltip/opacity.png
  test/specs/plugin.tooltip.tests.js
  types/plugins/index.d.ts
Labels: type: bug

#7914 fix some typos
  docs/docs/configuration/legend.md
  docs/docs/general/performance.md
  docs/docs/general/responsive.md
  src/core/core.animations.js
  src/core/core.plugins.js
  src/scales/scale.category.js
Labels: type: documentation

#7910 Render points while animations are active
  src/elements/element.point.js
Labels: type: bug

#7915 Update dependencies
  package-lock.json
  package.json
Labels: dependencies, type: infrastructure

#7917 Use Object.create(null) as `merge` target, to prevent prototype pollution
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.defaults.js
  src/core/core.layouts.js
  src/helpers/helpers.core.js
  src/plugins/plugin.filler.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.tooltip.js
  test/specs/core.helpers.tests.js
Labels: type: bug

#7918 When objects are merged together, the target prototype can be polluted.
  src/helpers/helpers.core.js
  test/specs/helpers.core.tests.js
Labels: type: bug

#7920 Use Object.create(null) as `merge` target, to prevent prototype pollution
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.scaleService.js
  test/specs/helpers.core.tests.js
Labels: type: bug

#7919 Block incorrect keys in merge code to prevent prototype pollution
  src/helpers/helpers.core.js
  test/specs/helpers.core.tests.js
Labels: type: bug

#7912 Fix broken url in docs
  docs/docs/axes/radial/linear.md
  docs/docs/developers/updates.md
  docs/docs/general/performance.md
  docs/docs/getting-started/v3-migration.md
Labels: type: documentation

#7925 Add example of event to data value transformation
  docs/docs/general/interactions/events.md
Labels: type: documentation

#7922 Add interaction options
  docs/docs/configuration/tooltip.md
  docs/docs/general/interactions/index.md
  docs/docs/general/interactions/modes.md
  docs/docs/getting-started/v3-migration.md
  samples/charts/line/multi-axis.html
  samples/charts/scatter/multi-axis.html
  src/controllers/controller.bar.js
  src/controllers/controller.line.js
  src/core/core.controller.js
  src/core/core.defaults.js
  src/plugins/plugin.tooltip.js
  test/specs/core.controller.tests.js
  types/core/index.d.ts
Labels: breaking change, type: enhancement

#7924 Rename elements to mark as elements, i.e. Arc -> ArcElement
  docs/docs/charts/bar.mdx
  docs/docs/configuration/elements.md
  docs/docs/developers/api.md
  docs/docs/getting-started/v3-migration.md
  samples/charts/bar/horizontal.html
  samples/scriptable/bar.html
  src/controllers/controller.bar.js
  src/core/core.datasetController.js
  src/elements/element.arc.js
  src/elements/element.bar.js
  src/elements/element.line.js
  src/elements/element.point.js
  src/elements/index.js
  src/helpers/helpers.segment.js
  src/plugins/plugin.filler.js
  test/fixtures/controller.bar/backgroundColor/indexable.js
  test/fixtures/controller.bar/backgroundColor/loopable.js
  test/fixtures/controller.bar/backgroundColor/scriptable.js
  test/fixtures/controller.bar/backgroundColor/value.js
  test/fixtures/controller.bar/borderColor/indexable.js
  test/fixtures/controller.bar/borderColor/scriptable.js
  test/fixtures/controller.bar/borderColor/value.js
  test/fixtures/controller.bar/borderSkipped/indexable.js
  test/fixtures/controller.bar/borderSkipped/scriptable.js
  test/fixtures/controller.bar/borderSkipped/value.js
  test/fixtures/controller.bar/borderWidth/indexable-object.js
  test/fixtures/controller.bar/borderWidth/indexable.js
  test/fixtures/controller.bar/borderWidth/negative.js
  test/fixtures/controller.bar/borderWidth/object.js
  test/fixtures/controller.bar/borderWidth/scriptable-object.js
  test/fixtures/controller.bar/borderWidth/scriptable.js
  test/fixtures/controller.bar/borderWidth/value.js
  test/fixtures/controller.bar/chart-area-clip.js
  test/fixtures/controller.bar/horizontal-borders.js
  test/fixtures/scale.category/ticks-from-data.js
  test/specs/controller.bar.tests.js
  test/specs/controller.bubble.tests.js
  test/specs/controller.doughnut.tests.js
  test/specs/controller.line.tests.js
  test/specs/controller.polarArea.tests.js
  test/specs/controller.radar.tests.js
  test/specs/element.arc.tests.js
  test/specs/element.bar.tests.js
  test/specs/element.line.tests.js
  test/specs/element.point.tests.js
  test/specs/element.rectangle.tests.js
  test/specs/global.namespace.tests.js
  types/controllers/index.d.ts
  types/elements/index.d.ts
Labels: breaking change, type: enhancement

#7936 Rename showLines to showLine
  docs/docs/charts/line.mdx
  docs/docs/general/performance.md
  docs/docs/getting-started/v3-migration.md
  src/controllers/controller.line.js
  src/controllers/controller.radar.js
  src/core/core.defaults.js
  test/fixtures/controller.line/showLines/dataset.js
  test/fixtures/controller.line/showLines/false.js
  test/fixtures/controller.radar/showLines/value.js
  test/fixtures/controller.scatter/showLines/true.js
  test/fixtures/controller.scatter/showLines/undefined.js
  test/specs/controller.bubble.tests.js
  test/specs/controller.line.tests.js
  test/specs/controller.polarArea.tests.js
  test/specs/controller.radar.tests.js
  test/specs/core.controller.tests.js
  types/controllers/index.d.ts
Labels: breaking change, type: chore

#7940 Add bundlewatch
  .github/workflows/bundlewatch.yml
  package-lock.json
  package.json
Labels: type: chore, type: infrastructure

#7941 Add *.json to .editorconfig
  .editorconfig
  .github/workflows/bundlewatch.yml
Labels: type: chore, type: infrastructure

#7943 Switch from bundlewatch to compressed-size
  .github/workflows/bundlewatch.yml
  .github/workflows/compressed-size.yml
  package-lock.json
  package.json
Labels: type: chore, type: infrastructure

#7950 [2.9] Use default color value for generateLegend when backgroundColor is undefined
  src/controllers/controller.doughnut.js
  src/controllers/controller.polarArea.js
  src/plugins/plugin.legend.js
Labels: type: bug, version: 2

#7949 Add `args.mode` to before/after update plugin hooks
  docs/docs/getting-started/v3-migration.md
  src/core/core.controller.js
  src/core/core.plugins.js
  src/plugins/plugin.filler.js
  types/core/index.d.ts
Labels: breaking change, type: chore, type: enhancement

#7939 Move config handling to a dedicated script
  src/core/core.config.js
  src/core/core.controller.js
  src/core/core.plugins.js
Labels: type: chore

#7953 Update category scale labels types to include string[][]
  docs/docs/axes/cartesian/category.md
  types/scales/index.d.ts
Labels: type: documentation

#7957 Update stacked line sample to remove duplicate dataset names
  samples/charts/area/line-stacked.html
Labels: type: documentation

#7955 Enable suggestedMin and suggestedMax settings for logarithmic axes
  docs/docs/axes/cartesian/logarithmic.md
  src/scales/scale.logarithmic.js
  test/specs/scale.logarithmic.tests.js
  types/scales/index.d.ts
Labels: type: enhancement

#7959 Enable overriding the legend pointStyle using new `pointStyle` option
  docs/docs/configuration/legend.md
  src/plugins/plugin.legend.js
  test/specs/plugin.legend.tests.js
  types/plugins/index.d.ts
Labels: type: enhancement

#7951 feat: add borderRadius to bar charts. Closes #7701
  docs/docs/charts/bar.mdx
  samples/charts/bar/border-radius.html
  samples/samples.js
  src/controllers/controller.bar.js
  src/elements/element.bar.js
  src/helpers/helpers.options.js
  test/fixtures/controller.bar/border-radius.js
  test/fixtures/controller.bar/border-radius.png
  test/fixtures/controller.bar/horizontal-borders.png
  test/specs/helpers.options.tests.js
  types/elements/index.d.ts
Labels: type: enhancement

#7961 fix return type for setActiveElements
  types/core/index.d.ts
  types/plugins/index.d.ts
Labels: type: types

#7964 Legend item lineWidth is the average of borderWidth when set as object (Bar)
  src/plugins/plugin.legend.js
Labels: type: bug

#7968 feat: Make options.layout.padding scriptable. Closes #7873
  docs/docs/configuration/layout.md
  src/core/core.layouts.js
  test/fixtures/core.layouts/scriptable.js
  test/fixtures/core.layouts/scriptable.png
  types/core/interfaces.d.ts
Labels: type: enhancement

#7972 feat: Draw tooltips with point styles. Closes #7774
  docs/docs/configuration/tooltip.md
  samples/samples.js
  samples/tooltips/point-style.html
  src/plugins/plugin.tooltip.js
  test/fixtures/core.tooltip/point-style.js
  test/fixtures/core.tooltip/point-style.png
  test/specs/plugin.tooltip.tests.js
  types/plugins/index.d.ts
Labels: type: enhancement

#7984 Allow 1px margin to getRelativePosition test
  test/specs/helpers.dom.tests.js
Labels: type: chore, type: infrastructure

#7979 Relocate dataset defaults to defaults.controllers
  docs/docs/charts/bar.mdx
  docs/docs/charts/doughnut.mdx
  docs/docs/charts/line.mdx
  docs/docs/charts/polar.mdx
  docs/docs/charts/radar.mdx
  docs/docs/configuration/index.md
  docs/docs/getting-started/v3-migration.md
  samples/charts/multi-series-pie.html
  src/core/core.config.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.registry.js
  test/specs/controller.bar.tests.js
  test/specs/controller.line.tests.js
  test/specs/core.controller.tests.js
  test/specs/core.registry.tests.js
  test/specs/global.defaults.tests.js
  test/specs/platform.dom.tests.js
Labels: breaking change, type: chore

#7983 Tooltip: clear cached animations on initialize
  src/plugins/plugin.tooltip.js
Labels: type: bug

#7986 Check index bounds of datasets for isDatasetVisible
  src/core/core.controller.js
  test/specs/core.controller.tests.js
Labels: type: bug

#7978 Rename lineTension back to tension
  docs/docs/charts/line.mdx
  docs/docs/charts/radar.mdx
  docs/docs/getting-started/v3-migration.md
  samples/charts/line/interpolation-modes.html
  samples/scales/financial.html
  src/controllers/controller.line.js
  src/controllers/controller.radar.js
  test/fixtures/element.line/skip/all.js
  test/fixtures/element.line/skip/first-span.js
  test/fixtures/element.line/skip/first.js
  test/fixtures/element.line/skip/last-span.js
  test/fixtures/element.line/skip/last.js
  test/fixtures/element.line/skip/middle-span.js
  test/fixtures/element.line/skip/middle.js
  test/fixtures/element.line/stepped/after.js
  test/fixtures/element.line/stepped/before.js
  test/fixtures/element.line/stepped/default.js
  test/fixtures/element.line/stepped/middle.js
  test/fixtures/element.line/tension/one.js
  test/fixtures/element.line/tension/zero.js
  test/fixtures/plugin.filler/fill-line-dataset-interpolated.js
  test/fixtures/scale.timeseries/financial-daily.js
  test/specs/controller.line.tests.js
  test/specs/controller.radar.tests.js
Labels: type: chore
