Repository chartjs/Chart.js, pull requests merged in 2021-09, with the labels that each got.

#9570 Add missing typings of helpers, add automatic test
  .gitignore
  package-lock.json
  package.json
  types/geometric.d.ts
  types/helpers/helpers.canvas.d.ts
  types/helpers/helpers.core.d.ts
  types/helpers/helpers.dom.d.ts
  types/helpers/helpers.math.d.ts
  types/helpers/helpers.options.d.ts
  types/tests/autogen.js
Labels: type: types

#9592 Fix control points on animated line w/o border
  src/elements/element.line.js
  test/fixtures/controller.line/fill/no-border.js
  test/fixtures/controller.line/fill/no-border.png
Labels: type: bug

#9613 Fix plugin event filtering of renamed events
  package-lock.json
  package.json
  src/core/core.controller.js
  test/specs/core.plugin.tests.js
Labels: type: bug

#9619 Update old codepen links to ones for v3
  .github/ISSUE_TEMPLATE/DOCS.md
  .github/PULL_REQUEST_TEMPLATE.md
  docs/developers/contributing.md
Labels: type: documentation

#9618 Update tooltip callback docs
  docs/configuration/tooltip.md
Labels: type: documentation

#9617 Remove offscreen canvas types
  types/index.esm.d.ts
Labels: type: types

#9620 Enable per-corner border radius in tooltip
  docs/configuration/tooltip.md
  src/plugins/plugin.tooltip.js
  test/fixtures/plugin.tooltip/corner-radius.js
  test/fixtures/plugin.tooltip/corner-radius.png
  types/index.esm.d.ts
Labels: type: enhancement

#9622 Add parsing support to pie/doughnut charts
  docs/general/data-structures.md
  src/controllers/controller.doughnut.js
  test/fixtures/controller.doughnut/doughnut-parsing.js
  test/fixtures/controller.doughnut/doughnut-parsing.png
Labels: type: enhancement

#9626 fix: broken link to `cubicInterpolationMode`
  docs/configuration/elements.md
Labels: type: documentation

#9624 Add sanity checks for scale options
  src/core/core.config.js
  test/specs/core.controller.tests.js
Labels: type: enhancement

#9625 Configurable tooltip box padding
  docs/configuration/tooltip.md
  src/plugins/plugin.tooltip.js
  test/fixtures/plugin.tooltip/box-padding.js
  test/fixtures/plugin.tooltip/box-padding.png
  types/index.esm.d.ts
Labels: type: enhancement

#9610 fix getRelativePosition type definition
  types/helpers/helpers.dom.d.ts
Labels: type: types

#9634 Add align to interface of scale title config
  types/index.esm.d.ts
Labels: type: types

#9644 Fix segment styling with gaps
  docs/charts/line.md
  docs/samples/line/segments.md
  src/elements/element.line.js
  src/helpers/helpers.segment.js
  test/fixtures/controller.line/segments/gap.js
  test/fixtures/controller.line/segments/spanGaps.js
  test/fixtures/controller.line/segments/spanGaps.png
  test/fixtures/plugin.filler/line/segments/gap.js
Labels: type: bug

#9646 Remove const me = this pattern
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.line.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/core/core.animation.js
  src/core/core.animator.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.element.js
  src/core/core.plugins.js
  src/core/core.registry.js
  src/core/core.scale.js
  src/core/core.typedRegistry.js
  src/elements/element.arc.js
  src/elements/element.line.js
  src/elements/element.point.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.title.js
  src/plugins/plugin.tooltip.js
  src/scales/scale.category.js
  src/scales/scale.linear.js
  src/scales/scale.linearbase.js
  src/scales/scale.logarithmic.js
  src/scales/scale.radialLinear.js
  src/scales/scale.time.js
  src/scales/scale.timeseries.js
Labels: type: chore

#9679 Add sanity check for stepSize
  src/scales/scale.linearbase.js
  test/specs/scale.linear.tests.js
Labels: type: enhancement

#9680 Fix some typings issues
  docs/samples/advanced/linear-gradient.md
  docs/samples/advanced/radial-gradient.md
  types/index.esm.d.ts
  types/tests/scales/options.ts
  types/tests/scriptable_core_chart_options.ts
Labels: type: types

#9678 Bar: fix too thick borders
  docs/charts/bar.md
  docs/configuration/elements.md
  src/controllers/controller.bar.js
  src/elements/element.bar.js
  test/fixtures/controller.bar/bar-base-value.png
  test/fixtures/controller.bar/bar-thickness-flex-offset.png
  test/fixtures/controller.bar/bar-thickness-flex.png
  test/fixtures/controller.bar/bar-thickness-offset.png
  test/fixtures/controller.bar/bar-thickness-reverse.png
  test/fixtures/controller.bar/bar-thickness-stacked.png
  test/fixtures/controller.bar/baseLine/bottom.png
  test/fixtures/controller.bar/baseLine/left.png
  test/fixtures/controller.bar/baseLine/mid-x.png
  test/fixtures/controller.bar/baseLine/mid-y.png
  test/fixtures/controller.bar/baseLine/right.png
  test/fixtures/controller.bar/baseLine/top.png
  test/fixtures/controller.bar/baseLine/value-x.png
  test/fixtures/controller.bar/baseLine/value-y.png
  test/fixtures/controller.bar/borderRadius/border-radius-stacked-number-mixed-chart.png
  test/fixtures/controller.bar/borderRadius/border-radius-stacked-number-with-order.png
  test/fixtures/controller.bar/borderRadius/border-radius-stacked-number.png
  test/fixtures/controller.bar/borderRadius/border-radius.png
  test/fixtures/controller.bar/borderSkipped/middle.png
  test/fixtures/controller.bar/borderWidth/indexable.png
  test/fixtures/controller.bar/borderWidth/object.png
  test/fixtures/controller.bar/borderWidth/value.png
  test/fixtures/controller.bar/horizontal-borders.png
  test/fixtures/controller.bar/minBarLength/vertical.png
  types/index.esm.d.ts
Labels: type: bug
