Repository chartjs/Chart.js, pull requests merged in 2021-11, with the labels that each got.

#9812 Docs/update scale position type
  docs/axes/cartesian/_common.md
  docs/axes/cartesian/index.md
Labels: type: documentation

#9831 Pass number format to tooltip
  src/scales/scale.linearbase.js
  src/scales/scale.logarithmic.js
Labels: type: bug

#9834 Types: include initial variable in the AnimationEvent
  types/animation.d.ts
Labels: type: types

#9837 update animation event to include currentStep instead of currentState
  types/animation.d.ts
Labels: type: types

#9843 Fix type linting and indent errors
  types/.eslintrc.yml
  types/adapters.d.ts
  types/animation.d.ts
  types/element.d.ts
  types/helpers/helpers.canvas.d.ts
  types/helpers/helpers.collection.d.ts
  types/helpers/helpers.color.d.ts
  types/helpers/helpers.core.d.ts
  types/helpers/helpers.curve.d.ts
  types/helpers/helpers.dom.d.ts
  types/helpers/helpers.math.d.ts
  types/helpers/helpers.options.d.ts
  types/helpers/helpers.rtl.d.ts
  types/index.esm.d.ts
  types/layout.d.ts
  types/utils.d.ts
Labels: type: infrastructure

#9855 Fix incomplete TS type for Chart.register + others
  types/index.esm.d.ts
  types/tests/defaults.ts
  types/tests/extensions/plugin.ts
Labels: type: bug, type: types

#9858 Types: add autopadding to typing
  types/index.esm.d.ts
Labels: type: types

#9861 Prevent proxying CanvasGradient in Node platform
  src/helpers/helpers.config.js
  test/specs/helpers.config.tests.js
Labels: type: bug

#9865 Update misleading sample comment
  docs/samples/scale-options/ticks.md
Labels: type: documentation

#9872 Configure all datasets before updating any
  src/controllers/controller.doughnut.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  test/fixtures/controller.doughnut/doughnut-full-to-semi.js
  test/fixtures/controller.doughnut/doughnut-full-to-semi.png
  test/specs/controller.radar.tests.js
Labels: type: bug

#9871 Fix inRange for full circle arc
  src/elements/element.arc.js
  src/elements/element.bar.js
  src/helpers/helpers.math.js
  src/helpers/helpers.segment.js
  src/plugins/plugin.filler.js
  src/plugins/plugin.legend.js
  test/specs/element.arc.tests.js
Labels: type: bug

#9857 Synchronize data visibility with data changes
  src/core/core.controller.js
  src/core/core.datasetController.js
  test/specs/core.controller.tests.js
Labels: type: bug

#9866 docs: Add a link to front-end integrations
  docs/index.md
Labels: type: documentation

#9893 Fix a typo in contributing.md
  docs/developers/contributing.md
Labels: type: documentation

#9900 Fix a typo in index.md
  docs/developers/index.md
Labels: type: documentation

#9876 Detect detach/attach in same observation
  src/platform/platform.dom.js
  test/specs/core.controller.tests.js
Labels: type: bug

#9915 Chart area boxes receive 0 margin during the final layout process
  src/core/core.layouts.js
  test/fixtures/plugin.legend/legend-line-chart-area.json
  test/fixtures/plugin.legend/legend-line-chart-area.png
Labels: type: bug

#9916 Doughnut chart options have an offset property
  types/index.esm.d.ts
  types/tests/controllers/doughnut_offset.ts
Labels: type: types

#9917 Add a note about the type parameters of the ChartData type
  types/index.esm.d.ts
Labels: type: documentation, type: types

#9921 Category: Track automatically added labels
  src/scales/scale.category.js
  test/specs/core.datasetController.tests.js
Labels: type: bug

#9922 Fix tooltip caret position when it is positioned at the corners
  src/plugins/plugin.tooltip.js
  test/fixtures/plugin.tooltip/caret-position.js
  test/fixtures/plugin.tooltip/caret-position.png
Labels: type: bug

#9923 Add notes about more specific options for axes
  docs/axes/cartesian/index.md
  docs/axes/index.md
Labels: type: documentation

#9929 Bump to 3.6.1
  package-lock.json
  package.json
Labels: type: chore
