Repository chartjs/Chart.js, pull requests merged in 2021-12, with the labels that each got.

#9938 Fix resolver caching issue when setting values
  src/helpers/helpers.config.js
  test/specs/helpers.config.tests.js
Labels: type: bug

#9939 Stop modifying options in interaction handlers
  src/core/core.interaction.js
Labels: type: bug

#9953 Bump version to 3.6.2
  package-lock.json
  package.json
Labels: type: chore

#9877 Add borderJoinStyle option for arc elements
  docs/charts/doughnut.md
  docs/charts/line.md
  docs/charts/polar.md
  docs/charts/radar.md
  docs/configuration/elements.md
  src/elements/element.arc.js
  test/fixtures/controller.doughnut/borderJoinStyle/bevel-default.js
  test/fixtures/controller.doughnut/borderJoinStyle/bevel-default.png
  test/fixtures/controller.doughnut/borderJoinStyle/miter.js
  test/fixtures/controller.doughnut/borderJoinStyle/miter.png
  test/fixtures/controller.doughnut/borderJoinStyle/round.js
  test/fixtures/controller.doughnut/borderJoinStyle/round.png
  types/index.esm.d.ts
  types/tests/elements/scriptable_element_options.ts
Labels: type: enhancement

#9920 Feature/active elements on top
  docs/charts/bubble.md
  docs/charts/line.md
  src/core/core.datasetController.js
  src/core/core.defaults.js
  test/fixtures/core.interaction/drawActiveElementsOnTop-false.js
  test/fixtures/core.interaction/drawActiveElementsOnTop-false.png
  types/index.esm.d.ts
Labels: type: enhancement

#9919 Support "r" axis for non-intersecting interaction
  docs/configuration/interactions.md
  src/core/core.interaction.js
  test/specs/core.interaction.tests.js
  types/index.esm.d.ts
Labels: type: enhancement

#9937 Types/allow for multiline labels in tick callback
  types/index.esm.d.ts
Labels: type: types

#9933 add beforeDestroy hook
  docs/developers/destroy_flowchart.png
  docs/developers/plugins.md
  src/core/core.controller.js
  src/core/core.plugins.js
  types/index.esm.d.ts
Labels: type: enhancement

#9952 Try to improve documentation for new users
  docs/configuration/index.md
  docs/configuration/interactions.md
  docs/general/data-structures.md
  docs/getting-started/index.md
  docs/samples/tooltip/interactions.md
Labels: type: documentation

#9945 Specify UTC time zone for the test suite
  karma.conf.js
  package-lock.json
  package.json
  test/index.js
  test/specs/scale.time.tests.js
Labels: type: infrastructure

#9944 Improvements to tooltip positioners
  docs/configuration/tooltip.md
  docs/samples/tooltip/position.md
  src/plugins/plugin.tooltip.js
  test/specs/plugin.tooltip.tests.js
  types/index.esm.d.ts
Labels: type: enhancement

#9960 Docs/clarify samples
  docs/.vuepress/config.js
  docs/.vuepress/redirects
  docs/samples/information.md
Labels: type: documentation

#9969 Pass object from array as value to _fallback
  src/helpers/helpers.config.js
  test/specs/helpers.config.tests.js
Labels: type: bug

#9970 Limit active element changes to chartArea
  src/core/core.controller.js
  src/core/core.interaction.js
  src/core/core.plugins.js
  src/helpers/helpers.core.js
  src/platform/platform.base.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.tooltip.js
  test/specs/core.controller.tests.js
  test/specs/plugin.tooltip.tests.js
  types/index.esm.d.ts
Labels: type: bug, type: enhancement

#9977 Add random seed reporting to test runs
  karma.conf.js
  test/seed-reporter.js
Labels: type: infrastructure

#9985 Types/Allow min-max as string timescale
  docs/axes/cartesian/time.md
  types/index.esm.d.ts
Labels: type: types

#9986 Types/ type suggestedMin and suggestedMax for time scale
  docs/axes/cartesian/time.md
  types/index.esm.d.ts
Labels: type: types

#9994 Docs/clarify usage of ticks callback (#9991)
  docs/axes/labelling.md
Labels: type: documentation

#9992 Fix setActiveElements behavior after a mouse event
  src/core/core.controller.js
  src/plugins/plugin.tooltip.js
  test/specs/core.controller.tests.js
  test/specs/plugin.tooltip.tests.js
Labels: type: bug

#9949 Add centerPointLabels option for linear radial scale
  docs/axes/radial/linear.md
  src/scales/scale.radialLinear.js
  test/specs/scale.radialLinear.tests.js
  types/index.esm.d.ts
Labels: type: enhancement

#10013 Docs/Add sample for centered point labels
  docs/.vuepress/config.js
  docs/axes/radial/linear.md
  docs/samples/other-charts/polar-area-center-labels.md
Labels: type: documentation

#10018 radialLinear: Hide pointLabels of hidden data
  src/scales/scale.radialLinear.js
  test/specs/scale.radialLinear.tests.js
Labels: type: bug

#10020 radialLinear: fix getIndexAngle when there are no labels (left)
  src/scales/scale.radialLinear.js
  test/fixtures/controller.polarArea/last-slice-animate.js
  test/fixtures/controller.polarArea/last-slice-animate.png
Labels: type: bug

#10021 radialLinear: fix positioning & scaling
  src/scales/scale.radialLinear.js
  test/fixtures/controller.polarArea/pointLabels/centered-180.js
  test/fixtures/controller.polarArea/pointLabels/centered-180.png
  test/fixtures/controller.polarArea/pointLabels/centered-45.js
  test/fixtures/controller.polarArea/pointLabels/centered-45.png
  test/fixtures/controller.polarArea/pointLabels/centered.js
  test/fixtures/controller.polarArea/pointLabels/centered.png
  test/fixtures/controller.polarArea/pointLabels/default-180.js
  test/fixtures/controller.polarArea/pointLabels/default-180.png
  test/fixtures/controller.polarArea/pointLabels/default-45.js
  test/fixtures/controller.polarArea/pointLabels/default-45.png
  test/fixtures/controller.polarArea/pointLabels/default.js
  test/fixtures/controller.polarArea/pointLabels/default.png
  test/fixtures/controller.polarArea/pointLabels/withTitle/bottom-centered-45.js
  test/fixtures/controller.polarArea/pointLabels/withTitle/bottom-centered-45.png
  test/fixtures/controller.polarArea/pointLabels/withTitle/bottom-centered.js
  test/fixtures/controller.polarArea/pointLabels/withTitle/bottom-centered.png
  test/fixtures/controller.polarArea/pointLabels/withTitle/left-centered-45.js
  test/fixtures/controller.polarArea/pointLabels/withTitle/left-centered-45.png
  test/fixtures/controller.polarArea/pointLabels/withTitle/left-centered.js
  test/fixtures/controller.polarArea/pointLabels/withTitle/left-centered.png
  test/fixtures/controller.polarArea/pointLabels/withTitle/right-centered-45.js
  test/fixtures/controller.polarArea/pointLabels/withTitle/right-centered-45.png
  test/fixtures/controller.polarArea/pointLabels/withTitle/right-centered.js
  test/fixtures/controller.polarArea/pointLabels/withTitle/right-centered.png
  test/fixtures/controller.polarArea/pointLabels/withTitle/top-centered-45.js
  test/fixtures/controller.polarArea/pointLabels/withTitle/top-centered-45.png
  test/fixtures/controller.polarArea/pointLabels/withTitle/top-centered.js
  test/fixtures/controller.polarArea/pointLabels/withTitle/top-centered.png
  test/fixtures/controller.polarArea/pointLabels/withTitle/top-default-45.js
  test/fixtures/controller.polarArea/pointLabels/withTitle/top-default-45.png
  test/fixtures/controller.polarArea/pointLabels/withTitle/top-default.js
  test/fixtures/controller.polarArea/pointLabels/withTitle/top-default.png
  test/fixtures/controller.radar/startAngle/135.js
  test/fixtures/controller.radar/startAngle/135.png
  test/fixtures/controller.radar/startAngle/180.js
  test/fixtures/controller.radar/startAngle/180.png
  test/fixtures/controller.radar/startAngle/225.js
  test/fixtures/controller.radar/startAngle/225.png
  test/fixtures/controller.radar/startAngle/270.js
  test/fixtures/controller.radar/startAngle/270.png
  test/fixtures/controller.radar/startAngle/315.js
  test/fixtures/controller.radar/startAngle/315.png
  test/fixtures/controller.radar/startAngle/45.js
  test/fixtures/controller.radar/startAngle/45.png
  test/fixtures/controller.radar/startAngle/90.js
  test/fixtures/controller.radar/startAngle/90.png
  test/fixtures/controller.radar/startAngle/default.js
  test/fixtures/controller.radar/startAngle/default.png
  test/fixtures/scale.radialLinear/pointLabels/background.png
  test/fixtures/scale.radialLinear/pointLabels/padding.png
  test/specs/controller.polarArea.tests.js
  test/specs/controller.radar.tests.js
  test/specs/core.layouts.tests.js
  test/specs/scale.radialLinear.tests.js
Labels: type: bug

#10011 Bump version to 3.7.0, update deps
  package-lock.json
  package.json
  tsconfig.json
  types/index.esm.d.ts
Labels: type: chore
