Repository chartjs/Chart.js, pull requests merged in 2021-04, with the labels that each got.

#8764 Scriptable title plugin options
  src/plugins/plugin.title.js
  test/fixtures/plugin.title/scriptable-options.js
  test/fixtures/plugin.title/scriptable-options.png
  test/specs/plugin.title.tests.js
Labels: type: bug

#8765 Ensure scriptable context reflects updated data
  src/core/core.datasetController.js
  test/specs/core.datasetController.tests.js
Labels: type: bug

#8768 Fix typo, add tests to catch
  src/elements/element.arc.js
  test/fixtures/controller.doughnut/single-slice-circumference-405.js
  test/fixtures/controller.doughnut/single-slice-circumference-405.png
  test/fixtures/controller.doughnut/single-slice-opacity.js
  test/fixtures/controller.doughnut/single-slice-opacity.png
Labels: type: bug

#8770 Remove line interaction overrides + hover.onHover
  docs/getting-started/v3-migration.md
  src/controllers/controller.bar.js
  src/controllers/controller.line.js
  src/core/core.controller.js
  src/core/core.defaults.js
  test/specs/core.controller.tests.js
  types/index.esm.d.ts
Labels: breaking change

#8774 Contributing link show 404 error page cause by wrong url
  README.md
Labels: type: documentation

#8775 Links: Rename .mdx to .md
  docs/axes/_common.md
  docs/axes/_common_ticks.md
  docs/axes/cartesian/_common.md
  docs/axes/cartesian/time.md
  docs/axes/cartesian/timeseries.md
  docs/axes/radial/index.md
  docs/charts/area.md
  docs/charts/polar.md
  docs/charts/scatter.md
  docs/configuration/elements.md
  docs/developers/api.md
  docs/general/performance.md
  docs/getting-started/v3-migration.md
Labels: type: bug, type: documentation

#8779 Bump to v3.0.0-rc.7
  package-lock.json
  package.json
Labels: type: chore

#8780 Make samples more inline with eachother
  docs/samples/advanced/progress-bar.md
  docs/samples/animations/drop.md
  docs/samples/animations/loop.md
  docs/samples/area/line-boundaries.md
  docs/samples/area/line-stacked.md
  docs/samples/line/line.md
  docs/samples/line/stepped.md
Labels: type: documentation

#8782 Fix tooltip align & external types
  types/index.esm.d.ts
Labels: type: bug, type: types

#8783 Redirect to first sample
  docs/.vuepress/config.js
  docs/samples/index.md
Labels: type: documentation

#8784 Add vuepress-plugin-flexsearch
  docs/.vuepress/config.js
  package-lock.json
  package.json
Labels: type: documentation

#8786 Adds scriptable column to options table in the title documentation
  docs/configuration/title.md
  docs/general/padding.md
Labels: type: documentation

#8785 Vuepress HTML redirect for samples folder
  docs/.vuepress/config.js
  docs/.vuepress/redirects
  package-lock.json
  package.json
Labels: type: documentation

#8787 Proxy: make sure set value ends up in first scope
  src/helpers/helpers.config.js
  test/specs/core.controller.tests.js
  test/specs/helpers.config.tests.js
Labels: type: bug

#8788 Tweak redirect urls
  docs/.vuepress/config.js
  docs/.vuepress/redirects
Labels: type: documentation

#8693 Update readme links and bug issue template
  .github/ISSUE_TEMPLATE/BUG.md
  README.md
Labels: type: documentation

#8781 v3.0.0 version bump
  .github/release-drafter.yml
  package-lock.json
  package.json
  types/index.esm.d.ts
Labels: type: chore

#8789 Patch: option scope might not be an object
  package-lock.json
  package.json
  src/helpers/helpers.config.js
Labels: status: blocker

#8790 Clean up a few sample issues
  docs/charts/bar.md
  docs/samples/tooltip/interactions.md
  docs/samples/tooltip/position.md
Labels: type: documentation

#8682 Doughnut/Pie chart border radius
  docs/charts/doughnut.md
  src/elements/element.arc.js
  src/helpers/helpers.options.js
  test/fixtures/controller.doughnut/borderRadius/scriptable.js
  test/fixtures/controller.doughnut/borderRadius/scriptable.png
  test/fixtures/controller.doughnut/borderRadius/value-corners.js
  test/fixtures/controller.doughnut/borderRadius/value-corners.png
  test/fixtures/controller.doughnut/borderRadius/value-large-radius.js
  test/fixtures/controller.doughnut/borderRadius/value-large-radius.png
  test/fixtures/controller.doughnut/borderRadius/value-small-number.js
  test/fixtures/controller.doughnut/borderRadius/value-small-number.png
  types/index.esm.d.ts
Labels: type: enhancement

#8793 Logarithmic: handle null/NaN values
  src/scales/scale.logarithmic.js
  test/fixtures/scale.logarithmic/null-values.js
  test/fixtures/scale.logarithmic/null-values.png
  test/specs/scale.logarithmic.tests.js
Labels: type: bug

#8795 Add legend events sample
  docs/.vuepress/config.js
  docs/samples/legend/events.md
Labels: type: documentation

#8797 Add ability to stack different dataset types
  docs/.vuepress/config.js
  docs/charts/bar.md
  docs/general/data-structures.md
  docs/samples/other-charts/stacked-bar-line.md
  src/core/core.datasetController.js
  test/fixtures/mixed/bar+line-stacked.js
  test/fixtures/mixed/bar+line-stacked.png
  test/specs/core.datasetController.tests.js
Labels: type: enhancement

#8798 Update ticks.callback documentation
  docs/axes/labelling.md
Labels: type: documentation

#8799 Proxy: Only create scopes when setting values
  src/helpers/helpers.config.js
  test/specs/helpers.config.tests.js
Labels: type: enhancement

#8800 Add the ability to change font color per legend item
  docs/configuration/legend.md
  src/plugins/plugin.legend.js
  test/specs/plugin.legend.tests.js
  types/index.esm.d.ts
Labels: type: enhancement

#8801 Correct decimation plugin documentation
  docs/.vuepress/config.js
  docs/configuration/decimation.md
  docs/samples/advanced/data-decimation.md
  docs/scripts/utils.js
  src/plugins/plugin.decimation.js
Labels: type: bug, type: documentation

#8803 Update documentation for getElementsAtEventForMode
  docs/developers/api.md
Labels: type: documentation

#8791 Docs small update
  docs/axes/cartesian/index.md
  docs/developers/index.md
Labels: type: documentation

#8804 HTML Legend sample
  docs/.vuepress/config.js
  docs/samples/legend/html.md
Labels: type: documentation

#8805 Update chart type documentation
  docs/charts/bar.md
  docs/charts/bubble.md
  docs/charts/doughnut.md
  docs/charts/line.md
  docs/charts/polar.md
  docs/charts/radar.md
  docs/charts/scatter.md
Labels: type: documentation

#8811 Fix: tick spacing when min=0 | niceMin or max=0
  src/scales/scale.linearbase.js
  test/fixtures/scale.linear/issue-8806.js
  test/fixtures/scale.linear/issue-8806.png
Labels: type: bug

#8815 Patch release workflow
  .github/workflows/release-drafter.yml
  MAINTAINING.md
Labels: type: documentation, type: infrastructure

#8816 Update codepen url in bug template
  .github/ISSUE_TEMPLATE/BUG.md
Labels: type: documentation

#8817 Update release process to create versioned docs
  .github/workflows/release.yml
  scripts/deploy-docs.sh
  scripts/docs-config.sh
  scripts/utils.sh
Labels: type: infrastructure

#8819 Fix utils.sh location
  scripts/deploy-docs.sh
  scripts/docs-config.sh
Labels: type: infrastructure

#8820 More script error fixes
  scripts/deploy-docs.sh
  scripts/utils.sh
Labels: type: infrastructure

#8821 Allow the CI to be manually run
  .github/workflows/ci.yml
Labels: type: infrastructure

#8822 Time: Use callback helper on ticks.callback
  src/scales/scale.time.js
Labels: type: bug

#8823 Dissociate border options from grid options
  docs/axes/_common.md
  docs/axes/_common_ticks.md
  docs/axes/styling.md
  src/core/core.scale.defaults.js
  src/core/core.scale.js
  test/fixtures/core.scale/cartesian-axis-border-settings.json
  test/fixtures/core.scale/x-axis-position-center.json
  test/fixtures/core.scale/x-axis-position-dynamic.json
  test/fixtures/core.scale/y-axis-position-center.json
  test/fixtures/core.scale/y-axis-position-dynamic.json
Labels: type: enhancement

#8828 Document plugin event handling
  docs/developers/event_flowchart.png
  docs/developers/plugin_flowcharts.drawio
  docs/developers/plugins.md
Labels: type: documentation

#8829 complete the first 'getting-started' example
  docs/getting-started/index.md
Labels: type: documentation

#8832 Fix: update line options on resize, for gradients
  src/controllers/controller.line.js
Labels: type: bug

#8836 Fix typo in migration guide
  docs/getting-started/v3-migration.md
Labels: type: documentation

#8838 _boundSegments did not work on rising line
  src/helpers/helpers.segment.js
  test/specs/helpers.segment.tests.js
Labels: type: bug

#8837 Fix typos in canvas-background.md
  docs/configuration/canvas-background.md
Labels: type: documentation

#8850 Docs migration register options
  docs/getting-started/v3-migration.md
Labels: type: documentation

#8847 Include `grace` in LinearScaleOptions type definition
  types/index.esm.d.ts
Labels: type: types

#8844 Allow styling of line segments
  docs/.vuepress/config.js
  docs/charts/line.md
  docs/samples/line/segments.md
  src/controllers/controller.line.js
  src/elements/element.line.js
  src/elements/element.point.js
  src/helpers/helpers.segment.js
  test/fixtures/controller.line/segments/gap.js
  test/fixtures/controller.line/segments/gap.png
  test/fixtures/controller.line/segments/range.js
  test/fixtures/controller.line/segments/range.png
  test/fixtures/controller.line/segments/slope.js
  test/fixtures/controller.line/segments/slope.png
  types/index.esm.d.ts
  types/tests/controllers/line_segments.ts
Labels: type: enhancement

#8856 Update dependencies (excluding typescript)
  package-lock.json
  package.json
Labels: dependencies

#8863 Docs/broken link
  docs/configuration/interactions.md
  docs/configuration/tooltip.md
Labels: type: documentation

#8864 Filler: support segment backgroundColor
  docs/charts/line.md
  src/helpers/helpers.segment.js
  src/plugins/plugin.filler.js
  test/fixtures/plugin.filler/line/segments/gap.js
  test/fixtures/plugin.filler/line/segments/gap.png
  test/fixtures/plugin.filler/line/segments/slope.js
  test/fixtures/plugin.filler/line/segments/slope.png
  test/specs/helpers.segment.tests.js
  types/index.esm.d.ts
  types/tests/controllers/line_segments.ts
Labels: type: enhancement

#8868 Consider dynamically positioned scales for padding
  src/core/core.layouts.js
  test/fixtures/core.scale/x-axis-position-dynamic-margin.js
  test/fixtures/core.scale/x-axis-position-dynamic-margin.png
  test/fixtures/core.scale/x-axis-position-dynamic.png
Labels: type: bug

#8869 Document the no-parsing requirement of decimation
  docs/configuration/decimation.md
Labels: type: documentation

#8867 Support mirror option on x-axis
  src/core/core.scale.js
  test/fixtures/core.scale/ticks-mirror-x.js
  test/fixtures/core.scale/ticks-mirror-x.png
  test/fixtures/core.scale/ticks-mirror.png
Labels: type: bug, type: enhancement

#8872 Handle animating stacked bars from null values
  src/controllers/controller.bar.js
  src/controllers/controller.line.js
  test/specs/controller.bar.tests.js
  test/specs/controller.line.tests.js
Labels: type: bug

#8874 Tooltip colorbox supports configurable borderWidth, borderRadius, and dash effect
  docs/configuration/tooltip.md
  src/elements/element.bar.js
  src/helpers/helpers.canvas.js
  src/plugins/plugin.tooltip.js
  test/fixtures/plugin.tooltip/color-box-border-dash.js
  test/fixtures/plugin.tooltip/color-box-border-dash.png
  test/fixtures/plugin.tooltip/color-box-border-radius.js
  test/fixtures/plugin.tooltip/color-box-border-radius.png
  test/specs/plugin.tooltip.tests.js
  types/index.esm.d.ts
Labels: type: enhancement

#8875 Legend boxes support borderRadius
  docs/configuration/legend.md
  src/plugins/plugin.legend.js
  test/fixtures/plugin.legend/borderRadius/legend-border-radius.js
  test/fixtures/plugin.legend/borderRadius/legend-border-radius.png
  test/specs/plugin.legend.tests.js
  types/index.esm.d.ts
Labels: type: enhancement

#8876 Enable event filtering per plugin
  docs/configuration/interactions.md
  src/core/core.controller.js
  src/core/core.plugins.js
  test/specs/core.plugin.tests.js
  test/specs/plugin.tooltip.tests.js
Labels: type: enhancement

#8877 Font: validate style, move defaults to `weight`
  docs/configuration/title.md
  docs/configuration/tooltip.md
  docs/getting-started/v3-migration.md
  docs/samples/scale-options/titles.md
  docs/samples/scales/time-max-span.md
  src/helpers/helpers.options.js
  src/plugins/plugin.title.js
  src/plugins/plugin.tooltip.js
  test/fixtures/scale.timeseries/financial-daily.js
  test/specs/helpers.options.tests.js
  test/specs/plugin.title.tests.js
  test/specs/plugin.tooltip.tests.js
  types/index.esm.d.ts
Labels: type: bug

#8866 Add version menu in documentation
  docs/.vuepress/config.js
  package-lock.json
  package.json
Labels: type: documentation

#8794 Limit onHover to chartArea
  docs/configuration/interactions.md
  src/core/core.controller.js
Labels: type: bug

#8878 Bump to 3.1.0
  package-lock.json
  package.json
Labels: type: chore

#8882 Update @simonbrunel/vuepress-plugin-versions
  package-lock.json
  package.json
Labels: dependencies, type: bug, type: documentation

#8883 Setting correct decimated values when below threshold
  src/plugins/plugin.decimation.js
Labels: type: bug

#8887 Docs: Update version menu title
  docs/.vuepress/config.js
Labels: type: documentation

#8891 add number, null and undefined as valid return types
  types/index.esm.d.ts
Labels: type: types

#8904 Update v3-migration.md
  docs/getting-started/v3-migration.md
Labels: type: documentation

#8898 Do not redraw endlessly on mouse move
  src/plugins/plugin.tooltip.js
  types/index.esm.d.ts
Labels: type: bug, type: performance

#8907 Fix javascript syntax error in docs/general/padding.md
  docs/general/padding.md
Labels: type: documentation

#8909 Fix tooltip positioners and scriptable signature
  types/index.esm.d.ts
Labels: type: types

#8910 Fix minor issues in docs
  docs/.vuepress/config.js
  docs/axes/cartesian/_common_ticks.md
  docs/axes/cartesian/index.md
  docs/axes/index.md
  docs/configuration/elements.md
  docs/configuration/tooltip.md
  docs/general/padding.md
  docs/general/performance.md
  docs/getting-started/index.md
  docs/getting-started/v3-migration.md
Labels: type: documentation

#8911 Fix: don't draw segments out of bounds
  src/elements/element.line.js
  test/fixtures/controller.line/issue-8902.js
  test/fixtures/controller.line/issue-8902.png
Labels: type: bug

#8914 Skip ticks by callback value as documented
  src/core/core.scale.js
  test/fixtures/core.scale/ticks/skip-by-callback.js
  test/fixtures/core.scale/ticks/skip-by-callback.png
Labels: type: bug

#8918 Fix: Initialize data object when replaced
  src/core/core.config.js
  test/specs/core.controller.tests.js
Labels: type: bug

#8913 Scale: Make sure grace is applied only once
  src/core/core.scale.js
  src/scales/scale.linearbase.js
  test/fixtures/scale.linear/grace/grace-neg.js
  test/fixtures/scale.linear/grace/grace-neg.png
  test/fixtures/scale.linear/grace/grace-pos.js
  test/fixtures/scale.linear/grace/grace-pos.png
  test/fixtures/scale.linear/grace/grace.js
  test/fixtures/scale.linear/grace/grace.png
  test/fixtures/scale.linear/grace/issue-8912.js
  test/fixtures/scale.linear/grace/issue-8912.png
Labels: type: bug

#8919 Fix: Fill vertical lines
  src/plugins/plugin.filler.js
  test/fixtures/plugin.filler/line/vertical.js
  test/fixtures/plugin.filler/line/vertical.png
Labels: type: bug

#8927 Bump to 3.1.1
  package-lock.json
  package.json
Labels: type: chore

#8926 Add `initial` property to animation callbacks
  docs/configuration/animations.md
  docs/samples/.eslintrc.yml
  docs/samples/advanced/progress-bar.md
  src/core/core.animator.js
Labels: type: enhancement

#8928 Allow the events option to be changed at runtime
  src/core/core.controller.js
  src/helpers/helpers.core.js
  test/specs/core.controller.tests.js
  test/specs/helpers.core.tests.js
  types/helpers/helpers.core.d.ts
Labels: type: bug

#8931 Cartesian scale tick backdrop
  docs/axes/_common_ticks.md
  docs/axes/radial/linear.md
  src/core/core.scale.defaults.js
  src/core/core.scale.js
  src/scales/scale.radialLinear.js
  test/fixtures/core.scale/tick-backdrop.js
  test/fixtures/core.scale/tick-backdrop.png
  test/specs/scale.radialLinear.tests.js
  types/index.esm.d.ts
Labels: type: enhancement

#8934 Fix for allowing parsing:false with stacks
  src/core/core.datasetController.js
  test/specs/core.datasetController.tests.js
Labels: type: bug

#8933 Time: cache options needed by parse
  src/scales/scale.time.js
Labels: time scale, type: performance

#8936 Scale: draw border on separate layer after grid
  src/core/core.scale.js
  src/scales/scale.radialLinear.js
  test/fixtures/core.scale/grid/border-over-grid.js
  test/fixtures/core.scale/grid/border-over-grid.png
  test/fixtures/core.scale/grid/colors.js
  test/fixtures/core.scale/grid/colors.png
  test/fixtures/scale.category/ticks-from-data.png
  test/specs/core.scale.tests.js
Labels: type: enhancement

#8942 Add example plugins for border and quadrants
  docs/.vuepress/config.js
  docs/samples/plugins/chart-area-border.md
  docs/samples/plugins/quadrants.md
Labels: type: documentation

#8941 Only enable the bar borderRadius at the end of the stacks
  docs/charts/bar.md
  src/controllers/controller.bar.js
  src/core/core.datasetController.js
  src/elements/element.bar.js
  test/fixtures/controller.bar/borderRadius/border-radius-stacked-number-mixed-chart.js
  test/fixtures/controller.bar/borderRadius/border-radius-stacked-number-mixed-chart.png
  test/fixtures/controller.bar/borderRadius/border-radius-stacked-number-with-order.js
  test/fixtures/controller.bar/borderRadius/border-radius-stacked-number-with-order.png
  test/fixtures/controller.bar/borderRadius/border-radius-stacked-number.js
  test/fixtures/controller.bar/borderRadius/border-radius-stacked-number.png
  test/fixtures/controller.bar/borderRadius/border-radius.js
  test/fixtures/controller.bar/borderRadius/border-radius.png
  test/specs/core.datasetController.tests.js
Labels: type: enhancement

#8944 Update helpers types export
  helpers/helpers.esm.d.ts
Labels: type: types

#8971 In html tooltip sample padding is read from the options
  docs/samples/tooltip/html.md
Labels: type: documentation

#8972 Fix skipNull for subsequent datasets
  src/controllers/controller.bar.js
  test/fixtures/controller.bar/skipNull/bar-skip-null-object-data.js
  test/fixtures/controller.bar/skipNull/bar-skip-null-object-data.png
  test/fixtures/controller.bar/skipNull/bar-skip-null.js
  test/fixtures/controller.bar/skipNull/bar-skip-null.png
  test/fixtures/controller.bar/skipNull/combinations.js
  test/fixtures/controller.bar/skipNull/combinations.png
Labels: type: bug

#8973 Add drawTime: beforeDraw option to filler
  docs/charts/area.md
  docs/samples/area/line-drawtime.md
  src/plugins/plugin.filler.js
  test/fixtures/plugin.filler/radar/beforeDraw.js
  test/fixtures/plugin.filler/radar/beforeDraw.png
Labels: type: enhancement

#8974 Bump to version 3.2.0
  package-lock.json
  package.json
Labels: type: chore

#8983 Improve linear tick generators collision estimation
  src/core/core.scale.js
  src/scales/scale.linearbase.js
  test/fixtures/scale.linear/min-max-skip-edge-case-1.js
  test/fixtures/scale.linear/min-max-skip-edge-case-1.png
  test/fixtures/scale.linear/min-max-skip-edge-case-2.js
  test/fixtures/scale.linear/min-max-skip-edge-case-2.png
  test/fixtures/scale.linear/min-max-skip-edge-case-3.js
  test/fixtures/scale.linear/min-max-skip-edge-case-3.png
  test/fixtures/scale.linear/min-max-skip-edge-case-4.js
  test/fixtures/scale.linear/min-max-skip-edge-case-4.png
Labels: type: bug

#8995 Ignore truncated pixels in bar width calculation
  src/controllers/controller.bar.js
Labels: type: bug

#9008 Fix for enabling monotone cubicInterpolationMode when tension is 0
  src/elements/element.line.js
  test/fixtures/element.line/cubicInterpolationMode/monotone.js
  test/fixtures/element.line/cubicInterpolationMode/monotone.png
  test/fixtures/plugin.filler/line/before-dataset-draw.png
  test/fixtures/plugin.filler/line/before-datasets-draw.png
  test/fixtures/plugin.filler/line/boundary/origin-spline-above.png
  test/fixtures/plugin.filler/line/boundary/origin-spline-span.png
  test/fixtures/plugin.filler/line/boundary/origin-spline.png
  test/fixtures/plugin.filler/line/dataset/span-dual.png
  test/fixtures/plugin.filler/line/dataset/spline-span-above.png
  test/fixtures/plugin.filler/line/dataset/spline-span-below.png
  test/fixtures/plugin.filler/line/dataset/spline-span.png
  test/fixtures/plugin.filler/line/dataset/spline.png
Labels: type: bug
