Repository chartjs/Chart.js, pull requests merged in 2021-06, with the labels that each got.

#9199 Fix rtl legend text alignment
  src/helpers/helpers.extras.js
  src/plugins/plugin.legend.js
  test/fixtures/plugin.legend/label-textAlign/horizontal-left.js
  test/fixtures/plugin.legend/label-textAlign/horizontal-left.png
  test/fixtures/plugin.legend/label-textAlign/horizontal-right.js
  test/fixtures/plugin.legend/label-textAlign/horizontal-right.png
  test/fixtures/plugin.legend/label-textAlign/horizontal-rtl-left.js
  test/fixtures/plugin.legend/label-textAlign/horizontal-rtl-left.png
  test/fixtures/plugin.legend/label-textAlign/horizontal-rtl-right.js
  test/fixtures/plugin.legend/label-textAlign/horizontal-rtl-right.png
  test/fixtures/plugin.legend/label-textAlign/rtl-left.png
  test/fixtures/plugin.legend/label-textAlign/rtl-right.png
Labels: type: bug

#9207 Add explanation on how to run the samples locally
  docs/getting-started/index.md
Labels: type: documentation

#9219 Update custom legend onClick example
  docs/configuration/legend.md
Labels: type: documentation

#9208 Bar width and height are always defined regardless of orientation
  src/controllers/controller.bar.js
Labels: type: enhancement

#9226 Add missing types to legend
  types/index.esm.d.ts
Labels: type: types

#9228 Fix broken guidelines url in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: documentation

#9237 Docs: fix broken and inconsistent links
  docs/configuration/tooltip.md
  docs/general/padding.md
Labels: type: documentation

#9252 `null` or `undefined` should skip grid lines in the time scale
  src/core/core.scale.js
  test/fixtures/scale.time/skip-null-gridlines.js
  test/fixtures/scale.time/skip-null-gridlines.png
  test/fixtures/scale.time/skip-undefined-gridlines.js
  test/fixtures/scale.time/skip-undefined-gridlines.png
Labels: type: bug

#9260 Replace [...set] with Array.from(set)
  src/core/core.config.js
  src/helpers/helpers.collection.js
  src/helpers/helpers.config.js
Labels: type: bug

#9261 Fix updating of active elements
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.line.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  test/fixtures/controller.doughnut/doughnut-set-active-elements.js
  test/fixtures/controller.doughnut/doughnut-set-active-elements.png
Labels: type: bug

#9262 Docs: Add copy button to code blocks
  docs/.vuepress/config.js
  package-lock.json
  package.json
Labels: type: documentation, type: enhancement

#9263 Fix type definitions and docs for `getPixelForValue`
  docs/developers/axes.md
  docs/getting-started/v3-migration.md
  types/index.esm.d.ts
Labels: type: documentation, type: types

#9284 added fill type to line in options object and to radar dataset options
  types/index.esm.d.ts
Labels: type: types

#9286 Fix: Don't use clip/unclipArea when `clip: false`
  src/controllers/controller.bar.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  test/specs/controller.bar.tests.js
Labels: type: enhancement

#9277 Apply maxTicksLimit to grid when ticks are hidden
  src/core/core.scale.js
  test/fixtures/scale.category/max-ticks-limit-a.js
  test/fixtures/scale.category/max-ticks-limit-a.png
  test/fixtures/scale.category/max-ticks-limit-b.js
  test/fixtures/scale.category/max-ticks-limit-b.png
Labels: type: enhancement

#9276 Refactor radialLinear scale and renderText helper
  .codeclimate.yml
  src/helpers/helpers.canvas.js
  src/scales/scale.radialLinear.js
  test/specs/helpers.canvas.tests.js
  test/specs/plugin.title.tests.js
Labels: type: chore

#9287 Filler: skip NaN points from end of segment
  src/plugins/plugin.filler.js
Labels: type: bug

#9291 Bar: ignore not-grouped bars from group bar count
  src/controllers/controller.bar.js
  test/fixtures/controller.bar/not-grouped/mixed.js
  test/fixtures/controller.bar/not-grouped/mixed.png
Labels: type: bug

#9290 Fix legend coordinate handling
  src/core/core.layouts.js
  src/plugins/plugin.legend.js
  test/fixtures/plugin.legend/padding/2cols-with-padding.js
  test/fixtures/plugin.legend/padding/2cols-with-padding.png
  test/fixtures/plugin.legend/padding/add-column.js
  test/fixtures/plugin.legend/padding/add-column.png
Labels: type: bug

#9292 resolve auto register typescript failure
  auto/auto.esm.d.ts
Labels: type: types

#9294 New plugin: subtitle
  docs/.vuepress/config.js
  docs/configuration/subtitle.md
  docs/samples/subtitle/basic.md
  src/plugins/index.js
  src/plugins/plugin.subtitle.js
  test/fixtures/plugin.subtitle/basic.js
  test/fixtures/plugin.subtitle/basic.png
  test/specs/plugin.subtitle.tests.js
Labels: type: enhancement

#9296 Docs: describe catching events with plugin
  docs/configuration/interactions.md
Labels: type: documentation

#9317 Change callback name in typing and documentation
  docs/axes/index.md
  types/index.esm.d.ts
Labels: type: documentation, type: types

#9319 Clarify how to import and use the helper functions with bundlers
  docs/getting-started/integration.md
Labels: type: documentation

#9322 Bump to version 3.4.0
  package-lock.json
  package.json
Labels: type: chore

#9326 Fix comma causing Terser issue
  src/scales/scale.linearbase.js
Labels: type: bug
