Repository chartjs/Chart.js, pull requests merged in 2021-08, with the labels that each got.

#9503 fixing typo in docs on axes labelling
  docs/axes/labelling.md
Labels: type: documentation

#9524 Add more details on legend sort function
  docs/configuration/legend.md
Labels: type: documentation

#9516 fix 2 broken links, clarify order property
  docs/charts/bar.md
  docs/charts/bubble.md
  docs/charts/line.md
  docs/charts/mixed.md
  docs/charts/radar.md
Labels: type: documentation

#9534 Update eslint settings for readable errors
  .eslintrc.yml
Labels: type: infrastructure

#9546 Add number to the title scale padding as type
  types/index.esm.d.ts
Labels: type: types

#9525 Keep track of parsed array changes when parsing===false
  src/core/core.datasetController.js
  test/specs/core.datasetController.tests.js
Labels: type: bug

#9550 Grid line z property in TS types
  types/index.esm.d.ts
Labels: type: types

#9549 Ensure that docs have more width in the page
  docs/.vuepress/styles/index.styl
Labels: type: documentation

#9555 Fix broken link.
  docs/axes/labelling.md
Labels: type: documentation

#9556 Remove chart.scale property (always undefined)
  src/core/core.controller.js
Labels: type: chore

#9565 Update to 3.5.1 version number
  package-lock.json
  package.json
Labels: type: chore

#9557 Detect attach/detach from any level
  src/core/core.controller.js
  src/helpers/helpers.extras.js
  src/platform/platform.dom.js
  test/specs/core.controller.tests.js
Labels: type: enhancement
