Repository chartjs/Chart.js, pull requests merged in 2021-05, with the labels that each got.

#9011 Add documentation on tooltip xAlign and yAlign
  docs/configuration/tooltip.md
Labels: type: documentation

#9010 Add test for DecimationAlgorithm type
  types/index.esm.d.ts
  types/tests/plugins/plugin.decimation/decimation_algorithm.ts
Labels: type: types

#9012 Enable scriptable element chart options
  types/index.esm.d.ts
  types/tests/elements/scriptable_element_options.ts
Labels: type: bug, type: types

#9014 Bump version to 3.2.1
  package-lock.json
  package.json
Labels: type: chore

#9024 Docs update file location pointers
  docs/.vuepress/config.js
  docs/axes/radial/linear.md
Labels: type: documentation

#9030 fix typo on api.md
  docs/developers/api.md
Labels: type: documentation

#9027 Fix: Avoid negative layout dimensions
  src/core/core.layouts.js
  test/specs/scale.linear.tests.js
Labels: type: bug

#9042 Fix line segments with alignToPixel
  src/helpers/helpers.segment.js
  test/fixtures/plugin.filler/line/segments/alignToPixels.js
  test/fixtures/plugin.filler/line/segments/alignToPixels.png
  test/specs/helpers.segment.tests.js
Labels: type: bug

#9020 Add includeBounds option for cartesian ticks
  docs/axes/cartesian/_common_ticks.md
  src/scales/scale.linearbase.js
  test/fixtures/scale.linear/min-max-skip/edge-case-1.js
  test/fixtures/scale.linear/min-max-skip/edge-case-1.png
  test/fixtures/scale.linear/min-max-skip/edge-case-2.js
  test/fixtures/scale.linear/min-max-skip/edge-case-2.png
  test/fixtures/scale.linear/min-max-skip/edge-case-3.js
  test/fixtures/scale.linear/min-max-skip/edge-case-3.png
  test/fixtures/scale.linear/min-max-skip/edge-case-4.js
  test/fixtures/scale.linear/min-max-skip/edge-case-4.png
  test/fixtures/scale.linear/min-max-skip/includeBounds.js
  test/fixtures/scale.linear/min-max-skip/includeBounds.png
  test/fixtures/scale.linear/min-max-skip/min-max-skip.js
  test/fixtures/scale.linear/min-max-skip/min-max-skip.png
  test/fixtures/scale.linear/min-max-skip/no-collision.js
  test/fixtures/scale.linear/min-max-skip/no-collision.png
  test/fixtures/scale.linear/min-max-skip/rotated-case-1.js
  test/fixtures/scale.linear/min-max-skip/rotated-case-1.png
  test/fixtures/scale.linear/min-max-skip/rotated-case-2.js
  test/fixtures/scale.linear/min-max-skip/rotated-case-2.png
  test/fixtures/scale.linear/min-max-skip/rotated-case-3.js
  test/fixtures/scale.linear/min-max-skip/rotated-case-3.png
  test/fixtures/scale.linear/min-max-skip/rotated-case-4.js
  test/fixtures/scale.linear/min-max-skip/rotated-case-4.png
  types/index.esm.d.ts
Labels: type: enhancement

#9045 Allow scale to auto-adjust it's min when stacked
  src/scales/scale.linearbase.js
  test/specs/scale.linear.tests.js
Labels: type: bug

#9044 HTML legend handles doughnut/pie charts
  docs/samples/legend/html.md
Labels: type: documentation

#9060 add derived axis default values
  docs/scripts/log2.js
Labels: type: bug

#9067 Fix polar area tooltip item label
  src/controllers/controller.polarArea.js
Labels: type: bug

#9062 Fix setting options in array of objects
  src/helpers/helpers.config.js
  test/specs/helpers.config.tests.js
Labels: type: bug

#9088 Fix element reset animations in vertical line and bubble charts
  src/controllers/controller.bubble.js
  src/controllers/controller.line.js
Labels: type: enhancement

#9091 Add test for issue 9085
  types/tests/scales/chart_options.ts
Labels: type: chore

#9084 Support monotone cubic interpolation for vertical line charts
  src/controllers/controller.line.js
  src/elements/element.line.js
  src/helpers/helpers.curve.js
  src/plugins/plugin.filler.js
  test/fixtures/element.line/cubicInterpolationMode/monotone-horizontal.js
  test/fixtures/element.line/cubicInterpolationMode/monotone-horizontal.png
  test/fixtures/element.line/cubicInterpolationMode/monotone-vertical.js
  test/fixtures/element.line/cubicInterpolationMode/monotone-vertical.png
  types/helpers/helpers.curve.d.ts
  types/index.esm.d.ts
Labels: type: enhancement

#9101 Make sure context indices are up to date
  src/core/core.datasetController.js
  test/specs/core.datasetController.tests.js
Labels: type: bug

#9102 Upgrade dependencies
  package-lock.json
  package.json
Labels: type: chore

#9105 Delay data to elements synchronization to update
  src/core/core.datasetController.js
  test/specs/core.datasetController.tests.js
Labels: type: bug

#9111 remove double sentence and adjust scale to scales.r
  docs/charts/radar.md
Labels: type: documentation

#9115 Add documentation note about only styling the parent div
  docs/configuration/responsive.md
Labels: type: documentation

#9121 Fix doughnut rotation on float edge cases
  src/controllers/controller.doughnut.js
  src/helpers/helpers.math.js
  test/fixtures/controller.doughnut/doughnut-rotation-300.js
  test/fixtures/controller.doughnut/doughnut-rotation-300.png
Labels: type: bug

#9120 Fix animations when data is replaced
  src/core/core.datasetController.js
  test/specs/core.datasetController.tests.js
Labels: type: bug

#9118 Fix arc offset calculation
  src/elements/element.arc.js
  test/fixtures/controller.doughnut/doughnut-offset.js
  test/fixtures/controller.doughnut/doughnut-offset.png
  test/fixtures/controller.doughnut/pie-offset.js
  test/fixtures/controller.doughnut/pie-offset.png
Labels: type: bug

#9123 Add missing props to ChartArea type
  types/geometric.d.ts
Labels: type: types

#9124 Correctly extend ExtendedPlugin interface
  types/index.esm.d.ts
Labels: type: types

#9126 Add attribute to custom legend onclick sample
  docs/configuration/legend.md
Labels: type: documentation

#9122 Show correct decimal places when using count but `min` is not an integer
  src/core/core.ticks.js
  src/scales/scale.linearbase.js
  test/fixtures/scale.linear/tick-count-min-max-not-int.js
  test/fixtures/scale.linear/tick-count-min-max-not-int.png
Labels: type: bug

#9135 Update chartjs-test-utils and mis-sized fixtures
  package-lock.json
  package.json
  test/fixtures/controller.doughnut/single-slice-opacity.png
  test/fixtures/core.scale/autoSkip/no-offset.png
  test/fixtures/core.scale/autoSkip/offset.png
  test/fixtures/plugin.title/scriptable-options.png
  test/fixtures/plugin.tooltip/positioning.png
  test/fixtures/scale.linear/min-max-skip/edge-case-1.png
  test/fixtures/scale.linear/rotated-45.png
Labels: type: infrastructure

#9146 Fix scales option in example
  docs/axes/cartesian/index.md
Labels: type: documentation

#9147 Improved error message when no date adapter provided
  src/core/core.adapters.js
Labels: type: documentation

#9149 Bump version to 3.3, update dependencies
  package-lock.json
  package.json
Labels: dependencies, type: chore

#9152 Fix: Arc getCenterPoint when full circle
  src/elements/element.arc.js
  test/specs/element.arc.tests.js
Labels: type: bug

#9153 Stop mutating arc state while drawing
  src/elements/element.arc.js
  test/specs/element.arc.tests.js
Labels: type: bug

#9160 show the utils file in the samples page to clarify what the functions do
  docs/.vuepress/config.js
  docs/samples/utils.md
Labels: type: documentation

#9168 Update pointstyle type and default value
  docs/charts/bubble.md
  docs/configuration/legend.md
Labels: type: documentation

#9171 Ignore items outside chart area for interaction
  src/core/core.interaction.js
Labels: type: bug

#9170 Fix clearStacks with custom scaleId
  src/core/core.datasetController.js
  test/fixtures/controller.bar/stacking/issue-9105.js
  test/fixtures/controller.bar/stacking/issue-9105.png
Labels: type: bug

#9172 Add declaration for Decimation plugin
  types/index.esm.d.ts
  types/tests/register.ts
Labels: type: bug, type: types

#9173 Add documentation about default scales
  docs/axes/index.md
Labels: type: documentation

#9181 Linear: Respect bounds option in tick generation
  src/scales/scale.linearbase.js
  test/fixtures/controller.line/stacking/bounds-data.js
  test/fixtures/controller.line/stacking/bounds-data.png
Labels: type: bug

#9182 Version bump to 3.3.1
  package-lock.json
  package.json
Labels: type: chore

#9180 Allow setting a constance spacing between arc elements
  docs/charts/doughnut.md
  src/controllers/controller.doughnut.js
  src/elements/element.arc.js
  test/fixtures/controller.doughnut/doughnut-spacing-and-offset.js
  test/fixtures/controller.doughnut/doughnut-spacing-and-offset.png
  test/fixtures/controller.doughnut/doughnut-spacing.js
  test/fixtures/controller.doughnut/doughnut-spacing.png
  test/specs/element.arc.tests.js
  types/index.esm.d.ts
Labels: type: enhancement

#9183 Fix error when swapping dataset locations
  src/core/core.controller.js
  test/specs/core.controller.tests.js
Labels: type: bug

#9187 Make sure data is parsed before updateElements
  src/core/core.datasetController.js
  test/specs/core.datasetController.tests.js
Labels: type: bug

#9190 Bump version to 3.3.2
  package-lock.json
  package.json
Labels: type: chore

#9191 Tick backdrop padding is not scriptable
  docs/axes/_common_ticks.md
  src/core/core.scale.defaults.js
Labels: type: bug
