Repository chartjs/Chart.js, pull requests merged in 2021-07, with the labels that each got.

#9330 Fix typing of the isoWeekday field
  types/index.esm.d.ts
Labels: type: types

#9336 Update types with more possible events
  types/index.esm.d.ts
Labels: type: types

#9338 Fixes spacing options in the documentation for doughnuts charts
  docs/charts/doughnut.md
Labels: type: documentation

#9340 Ensure correct item is clicked when a horizontal legend is in RTL mode
  src/plugins/plugin.legend.js
  test/specs/plugin.legend.tests.js
Labels: type: bug

#9341 Enable pointStyle for doughnut, pie, and polar area charts
  src/controllers/controller.doughnut.js
  src/controllers/controller.polarArea.js
  test/fixtures/plugin.legend/legend-doughnut-point-style.json
  test/fixtures/plugin.legend/legend-doughnut-point-style.png
  test/specs/global.defaults.tests.js
Labels: type: bug

#9343 Account for floating point error in niceNum helper
  src/helpers/helpers.math.js
  src/scales/scale.linearbase.js
  test/fixtures/scale.linear/tick-step-min-max-step-fp.js
  test/fixtures/scale.linear/tick-step-min-max-step-fp.png
Labels: type: bug

#9345 Timeseries: support panning
  src/scales/scale.timeseries.js
  test/fixtures/scale.timeseries/source-data-offset-min-max.png
  test/fixtures/scale.timeseries/source-labels-offset-min-max.png
  test/fixtures/scale.timeseries/ticks-reverse-max.png
  test/fixtures/scale.timeseries/ticks-reverse-min-max.png
  test/fixtures/scale.timeseries/ticks-reverse-min.png
  test/specs/scale.time.tests.js
Labels: type: bug

#9348 Add type tests for float bar / object data arrays
  types/tests/data_types.ts
Labels: type: types

#9349 Update deps
  docs/.vuepress/config.js
  package-lock.json
  package.json
Labels: dependencies

#9350 Bump version to 3.4.1
  package-lock.json
  package.json
Labels: type: chore

#9327 Adding threshold option to decimation plugin
  docs/configuration/decimation.md
  src/plugins/plugin.decimation.js
  test/specs/plugin.decimation.tests.js
  types/index.esm.d.ts
Labels: type: enhancement

#9360 Add 'shape' mode for filler-plugin
  docs/charts/area.md
  src/plugins/plugin.filler.js
  test/fixtures/plugin.filler/line/shape.js
  test/fixtures/plugin.filler/line/shape.png
  types/index.esm.d.ts
Labels: type: enhancement

#9367 Decimation: Prevent buffer overflow
  src/plugins/plugin.decimation.js
  test/specs/plugin.decimation.tests.js
Labels: type: bug

#9376 Improve LegendElement and TooltipItem type definitions
  types/index.esm.d.ts
  types/tests/plugins/plugin.tooltip/tooltip_dataset_type.ts
Labels: type: types

#9373 Point label specific scriptable context
  docs/general/options.md
  src/scales/scale.radialLinear.js
  test/fixtures/scale.radialLinear/pointLabels/scriptable-color-small.js
  test/fixtures/scale.radialLinear/pointLabels/scriptable-color-small.png
  types/index.esm.d.ts
Labels: type: bug

#9363 Resolve warnings from typings
  types/adapters.d.ts
  types/element.d.ts
  types/helpers/helpers.color.d.ts
  types/helpers/helpers.extras.d.ts
  types/helpers/helpers.math.d.ts
  types/index.esm.d.ts
  types/utils.d.ts
Labels: type: chore, type: types

#9385 Fix type linting for merge between two PRs
  types/index.esm.d.ts
Labels: type: types

#9384 Add SubTitle to the list of all esm imports
  docs/getting-started/integration.md
Labels: type: documentation

#9386 Indicate that `SubTitle` is a plugin in TS types
  types/index.esm.d.ts
Labels: type: types

#9353 Adjust legend hitboxes when RTL and each item has a different size
  src/plugins/plugin.legend.js
  test/fixtures/plugin.legend/horizontal-rtl-hitbox.js
  test/fixtures/plugin.legend/horizontal-rtl-hitbox.png
Labels: type: bug

#9364 Layout: support box stacking
  docs/.vuepress/config.js
  docs/axes/cartesian/_common.md
  docs/samples/scales/stacked.md
  src/core/core.layouts.js
  test/fixtures/core.layouts/stacked-boxes.js
  test/fixtures/core.layouts/stacked-boxes.png
  types/index.esm.d.ts
Labels: type: enhancement

#9394 Fix stacked box dimension calculation with weights
  src/core/core.layouts.js
  test/fixtures/core.layouts/stacked-boxes-with-weight.js
  test/fixtures/core.layouts/stacked-boxes-with-weight.png
Labels: type: bug

#9400 Fix bar direction when minBarLength is applied
  src/controllers/controller.bar.js
  test/fixtures/controller.bar/minBarLength/horizontal-neg.js
  test/fixtures/controller.bar/minBarLength/horizontal-neg.png
  test/fixtures/controller.bar/minBarLength/horizontal-pos.js
  test/fixtures/controller.bar/minBarLength/horizontal-pos.png
  test/fixtures/controller.bar/minBarLength/horizontal.js
  test/fixtures/controller.bar/minBarLength/horizontal.png
  test/fixtures/controller.bar/minBarLength/vertical-neg.js
  test/fixtures/controller.bar/minBarLength/vertical-neg.png
  test/fixtures/controller.bar/minBarLength/vertical-pos.js
  test/fixtures/controller.bar/minBarLength/vertical-pos.png
  test/fixtures/controller.bar/minBarLength/vertical.js
  test/fixtures/controller.bar/minBarLength/vertical.png
Labels: type: bug

#9403 Add missing resizeDelay option to types
  types/index.esm.d.ts
Labels: type: types

#9399 Bar: inflate rects by 0.33px to avoid artifacts
  src/elements/element.bar.js
  test/fixtures/controller.bar/bar-base-value.png
  test/fixtures/controller.bar/baseLine/bottom.png
  test/fixtures/controller.bar/baseLine/left.png
  test/fixtures/controller.bar/baseLine/mid-x.png
  test/fixtures/controller.bar/baseLine/mid-y.png
  test/fixtures/controller.bar/baseLine/right.png
  test/fixtures/controller.bar/baseLine/top.png
  test/fixtures/controller.bar/baseLine/value-x.png
  test/fixtures/controller.bar/baseLine/value-y.png
  test/fixtures/controller.bar/borderColor/border+dpr.js
  test/fixtures/controller.bar/borderColor/border+dpr.png
  test/fixtures/controller.bar/borderRadius/border-radius-stacked-number-mixed-chart.png
  test/fixtures/controller.bar/borderRadius/border-radius-stacked-number-with-order.png
  test/fixtures/controller.bar/borderRadius/border-radius-stacked-number.png
  test/fixtures/controller.bar/borderRadius/border-radius.png
  test/fixtures/controller.bar/borderRadius/no-spacing.js
  test/fixtures/controller.bar/borderRadius/no-spacing.png
  test/fixtures/controller.bar/borderWidth/indexable.png
  test/fixtures/controller.bar/borderWidth/object.png
  test/fixtures/controller.bar/borderWidth/value.png
  test/fixtures/controller.bar/horizontal-borders.png
  test/fixtures/scale.category/ticks-from-data.js
  test/fixtures/scale.category/ticks-from-data.png
Labels: type: bug

#9410 Limit Math.asin inputs to the range [-1, 1]
  src/core/core.scale.js
Labels: type: bug

#9414 Update a failing fixture
  test/fixtures/controller.bar/minBarLength/vertical.png
Labels: type: chore

#9413 Fix center axis title positions
  src/core/core.scale.js
  test/fixtures/core.scale/title/horizontal-center.js
  test/fixtures/core.scale/title/horizontal-center.png
  test/fixtures/core.scale/title/horizontal-value.js
  test/fixtures/core.scale/title/horizontal-value.png
  test/fixtures/core.scale/title/vertical-center.js
  test/fixtures/core.scale/title/vertical-center.png
  test/fixtures/core.scale/title/vertical-value.js
  test/fixtures/core.scale/title/vertical-value.png
Labels: type: bug

#9425 Properly update stacks when datasets index changes
  src/core/core.datasetController.js
  test/fixtures/controller.line/stacking/updates.js
  test/fixtures/controller.line/stacking/updates.png
Labels: type: bug

#9433 Linear scale handle min === max when abs(max) > Number.MAX_SAFE_INTEGER
  src/scales/scale.linearbase.js
  test/specs/scale.linear.tests.js
Labels: type: bug

#9438 Define bounds as a field common to all cartesian axes options
  types/index.esm.d.ts
Labels: type: types

#9432 Allow dataset specific ChartMeta type extensions
  types/index.esm.d.ts
  types/tests/controllers/doughnut_meta_total.ts
Labels: type: types

#9442 Fix: config.platform was ignored
  src/core/core.config.js
  src/core/core.controller.js
  src/helpers/helpers.dom.js
  src/platform/index.js
  test/specs/core.controller.tests.js
Labels: type: bug

#9443 Don't draw points outside chartArea
  src/elements/element.point.js
  src/helpers/helpers.canvas.js
  test/fixtures/controller.line/clip/false.js
  test/fixtures/controller.line/clip/false.png
Labels: type: bug

#9444 Typescript 4.2+ compatibility
  package-lock.json
  package.json
  types/index.esm.d.ts
  types/utils.d.ts
Labels: type: bug, type: types

#9446 Fix interaction on partially visible bar
  src/core/core.interaction.js
  test/fixtures/core.interaction/nearest-partial-bar.js
  test/fixtures/core.interaction/nearest-partial-bar.png
  test/fixtures/core.interaction/nearest-point-behind-scale.js
  test/fixtures/core.interaction/nearest-point-behind-scale.png
  test/specs/core.interaction.tests.js
Labels: type: bug

#9447 Apply segment styles with only single segment
  src/helpers/helpers.segment.js
  test/fixtures/controller.line/segments/single.js
  test/fixtures/controller.line/segments/single.png
Labels: type: bug

#9451 Add data/dataset indices to line segment context
  docs/charts/line.md
  src/controllers/controller.line.js
  src/elements/element.line.js
  src/helpers/helpers.segment.js
  types/index.esm.d.ts
Labels: type: enhancement

#9450 Add ability to hide specific data element
  docs/developers/api.md
  docs/samples/other-charts/doughnut.md
  src/controllers/controller.doughnut.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  test/fixtures/controller.doughnut/doughnut-hidden-single.js
  test/fixtures/controller.doughnut/doughnut-hidden-single.png
  types/index.esm.d.ts
Labels: type: enhancement

#9452 Bar: add 'middle' option for borderSkipped
  docs/charts/bar.md
  docs/configuration/elements.md
  src/controllers/controller.bar.js
  src/elements/element.bar.js
  test/fixtures/controller.bar/borderSkipped/middle.js
  test/fixtures/controller.bar/borderSkipped/middle.png
Labels: type: enhancement

#9458 Adds HTMLCanvasElement as possible value for pointStyle option in the documentation
  docs/charts/bar.md
  docs/charts/bubble.md
  docs/charts/line.md
  docs/charts/radar.md
  docs/configuration/elements.md
  docs/configuration/legend.md
Labels: type: documentation

#9448 Fix DomPlatform.isAttached
  src/platform/platform.dom.js
  test/specs/platform.dom.tests.js
Labels: type: bug

#9431 Ensure getPrototypeOf will not crash on plugin options with no scopes
  src/core/core.config.js
  test/specs/core.controller.tests.js
Labels: type: bug

#9462 Update radar dataset option typings
  types/index.esm.d.ts
  types/tests/controllers/radar_dataset_indexable_options.ts
Labels: type: types

#9464 Bump version to 3.5.0, update deps
  package-lock.json
  package.json
Labels: type: chore

#9472 Update charts.md
  docs/developers/charts.md
Labels: type: documentation

#9475 Adjust text to code example
  docs/general/fonts.md
Labels: type: documentation

#9469 Remove index interaction override barChart
  src/controllers/controller.bar.js
Labels: type: bug

#9477 Types: Change `context.chart` to plain `Chart`
  types/index.esm.d.ts
  types/tests/scriptable.ts
  types/utils.d.ts
Labels: type: types

#9465 Shorthand labels key in getting started
  docs/getting-started/index.md
Labels: type: documentation

#9489 Fix _isPointInArea helper when no area is provided
  src/helpers/helpers.canvas.js
  test/specs/helpers.canvas.tests.js
  types/index.esm.d.ts
Labels: type: bug

#9490 Types: Add `tooltip` to chart instance
  types/index.esm.d.ts
  types/tests/plugins/plugin.tooltip/chart.tooltip.ts
Labels: type: types

#9479 Move pointStyle types and update plugin link&render chart
  docs/charts/bar.md
  docs/charts/bubble.md
  docs/charts/line.md
  docs/charts/radar.md
  docs/configuration/elements.md
  docs/configuration/legend.md
  docs/developers/plugins.md
  docs/developers/render_flowchart.png
Labels: type: documentation
