Repository chartjs/Chart.js, pull requests merged in 2021-01, with the labels that each got.

#8263 Standardize type declaration indentation with tabs
  types/geometric.d.ts
  types/helpers/helpers.canvas.d.ts
  types/helpers/helpers.collection.d.ts
  types/helpers/helpers.color.d.ts
  types/helpers/helpers.core.d.ts
  types/helpers/helpers.curve.d.ts
  types/helpers/helpers.dom.d.ts
  types/helpers/helpers.math.d.ts
  types/helpers/helpers.options.d.ts
  types/helpers/helpers.rtl.d.ts
  types/index.esm.d.ts
  types/layout.d.ts
Labels: type: chore, type: types

#8262 Upgrade Docusaurus
  docs/docs/developers/updates.md
  docs/docs/index.md
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
Labels: type: chore, type: documentation

#8267 Upgrade TypeDoc
  package-lock.json
  package.json
  tsconfig.json
Labels: type: chore, type: documentation

#8270 Update link to latest version of V2 Docs
  docs/docusaurus.config.js
Labels: type: documentation

#8264 Add type linting
  package-lock.json
  package.json
  types/.eslintrc.yml
  types/index.esm.d.ts
Labels: type: infrastructure

#8266 Fix resize bug of line / radar charts
  src/controllers/controller.radar.js
  src/elements/element.line.js
Labels: type: bug

#8271 Fix incorrect defaults location for Bubble
  docs/docs/charts/bubble.mdx
  test/specs/global.defaults.tests.js
Labels: type: documentation

#8279 Update quotationmark for link
  docs/docs/charts/doughnut.mdx
Labels: type: documentation

#8274 Remove empty line from the options table
  docs/docs/axes/styling.mdx
Labels: type: documentation

#8283 Add note about v3 dev code in readme
  README.md
Labels: type: documentation

#8288 Update TypeScript ESLint configuration
  types/.eslintrc.yml
  types/index.esm.d.ts
Labels: type: infrastructure

#8291 Skip delete undefined stack
  src/core/core.datasetController.js
  test/specs/core.datasetController.tests.js
Labels: type: bug

#8289 clarification that strikethrough uses same color as the label color
  docs/docs/configuration/legend.md
Labels: type: documentation

#8302 Only draw points when radius >= 0.1
  src/elements/element.point.js
Labels: type: bug

#8300 Bump version to beta.8
  package-lock.json
  package.json
Labels: type: chore

#8305 fixes #8304 (Missing type) beta 8 broken typescript
  types/layout.d.ts
Labels: type: types

#8319 Disable Path2D caching when chart is animated
  docs/docs/general/performance.md
  src/controllers/controller.line.js
  src/elements/element.line.js
  src/helpers/helpers.extras.js
  test/specs/element.line.tests.js
Labels: type: bug

#8316 Fix broken links in tooltip docs
  docs/docs/configuration/tooltip.md
Labels: type: documentation

#8312 Revert "Update spelling of cancellable (#8236)"
  src/core/core.controller.js
  src/core/core.plugins.js
  test/specs/core.plugin.tests.js
Labels: type: chore

#8320 Bump v3.0.0-beta.9
  package-lock.json
  package.json
Labels: type: chore

#8321 Doughnut: complete radians to degrees conversion
  docs/docs/charts/doughnut.mdx
  docs/docs/getting-started/v3-migration.md
  samples/charts/doughnut.html
  types/index.esm.d.ts
Labels: type: documentation, type: types

#8323 Fix custom pie chart HTML tooltip sample not showing
  samples/tooltips/custom-pie.html
Labels: type: documentation

#8325 Update to test utils 0.1.2 to track font setting
  package-lock.json
  package.json
  test/specs/helpers.canvas.tests.js
  test/specs/plugin.title.tests.js
  test/specs/plugin.tooltip.tests.js
Labels: type: chore

#8328 fix canvas clearRect size calculation
  src/helpers/helpers.canvas.js
Labels: type: bug

#8327 add documentation for vertical line charts
  docs/docs/charts/bar.mdx
  docs/docs/charts/line.mdx
  docs/docs/getting-started/v3-migration.md
Labels: type: documentation

#8336 `getRelativePosition takes` two arguments. Update sample docs
  docs/docs/general/interactions/events.md
Labels: type: documentation

#8341 feature: choose custom point style for bar legend display
  docs/docs/charts/bar.mdx
  src/controllers/controller.bar.js
  test/specs/plugin.legend.tests.js
  types/index.esm.d.ts
Labels: type: enhancement

#8290 Give elements their own interface definition
  types/index.esm.d.ts
Labels: type: types

#8354 Fix/scatter tooltip mode
  docs/docs/charts/line.mdx
  docs/docs/charts/scatter.mdx
  src/controllers/controller.scatter.js
  test/specs/controller.scatter.tests.js
Labels: type: enhancement

#8358 Rename LayoutItem.fullWidth to fullSize
  docs/docs/configuration/legend.md
  docs/docs/getting-started/v3-migration.md
  src/core/core.controller.js
  src/core/core.layouts.js
  src/core/core.scale.js
  src/plugins/plugin.legend.js
  src/plugins/plugin.title.js
  test/specs/core.layouts.tests.js
  test/specs/plugin.legend.tests.js
  test/specs/plugin.title.tests.js
  types/index.esm.d.ts
  types/layout.d.ts
Labels: breaking change

#8359 align text inside chart for far-aligned labels passing test
  src/core/core.scale.js
  test/fixtures/core.scale/crossAlignment/cross-align-left-far-clipped.js
  test/fixtures/core.scale/crossAlignment/cross-align-left-far-clipped.png
  test/fixtures/core.scale/crossAlignment/cross-align-right-far-clipped.js
  test/fixtures/core.scale/crossAlignment/cross-align-right-far-clipped.png
Labels: type: enhancement
