Repository chartjs/Chart.js, pull requests merged in 2022-10, with the labels that each got.

#10691 Use the correct area to clip for dataset drawing when stacked scales are used
  .size-limit.cjs
  src/core/core.controller.js
  test/fixtures/core.layouts/stacked-boxes-max-index.js
  test/fixtures/core.layouts/stacked-boxes-max-index.png
  test/fixtures/core.layouts/stacked-boxes-max.js
  test/fixtures/core.layouts/stacked-boxes-max.png
Labels: type: bug

#10748 Updated dead sample link
  docs/developers/updates.md
Labels: type: documentation

#10728 Convert helpers.extra to TS
  src/helpers/helpers.extras.ts
  src/helpers/types.ts
  src/platform/platform.dom.js
  types/helpers/helpers.extras.d.ts
  types/helpers/index.d.ts
Labels: breaking change, type: types

#10739 Allow to configure X and Y axis ID in TS for bubble charts
  types/index.d.ts
Labels: type: types

#10760 Types: Change grid option of CartesianScaleOptions and RadialLinearScaleOptions to Partial of GridLineOptions
  types/index.d.ts
Labels: type: types

#10730 Convert the PointElement to TS
  src/core/core.element.ts
  src/elements/element.arc.js
  src/elements/element.point.ts
  types/index.d.ts
Labels: type: types

#10733 Convert the curve helpers to TS
  src/helpers/helpers.curve.ts
  src/helpers/helpers.interpolation.ts
  src/helpers/types.ts
  types/helpers/helpers.curve.d.ts
  types/helpers/index.d.ts
Labels: breaking change, type: types

#10763 docs: fix typos
  docs/configuration/interactions.md
  docs/migration/v4-migration.md
Labels: type: documentation

#10772 Convert the Arc element to TS
  .eslintrc.yml
  .size-limit.cjs
  src/elements/element.arc.ts
  types/index.d.ts
Labels: type: types

#10787 Bump alpha v4
  package.json
Labels: type: chore

#10789 Remove setting of version in package-lock
  .github/workflows/release.yml
Labels: type: bug, type: infrastructure

#10790 Bump alpha 2
  package.json
Labels: type: chore

#10773 fix: label text not centered when applied rotation
  src/core/core.scale.js
  test/fixtures/core.layouts/refit-vertical-boxes.png
  test/fixtures/core.scale/autoSkip/fit-after.png
  test/fixtures/core.scale/label-align-inner-rotate.png
  test/fixtures/core.scale/ticks/rotated-long.png
  test/fixtures/core.scale/ticks/rotated-multi-line.png
  test/fixtures/scale.linear/min-max-skip/no-collision.png
  test/fixtures/scale.linear/min-max-skip/rotated-case-1.png
  test/fixtures/scale.linear/min-max-skip/rotated-case-2.png
  test/fixtures/scale.linear/min-max-skip/rotated-case-3.png
  test/fixtures/scale.linear/min-max-skip/rotated-case-4.png
  test/fixtures/scale.linear/rotated-45.png
  test/fixtures/scale.linear/rotated-5.png
  test/fixtures/scale.linear/rotated-85.png
  test/fixtures/scale.time/labels-date.png
  test/fixtures/scale.time/labels-strings.png
  test/fixtures/scale.time/offset-auto-skip-ticks.png
  test/fixtures/scale.time/ticks-round.png
  test/specs/core.scale.tests.js
Labels: type: bug

#10804 rename jasmine failFast -> stopOnSpecFailure
  karma.conf.cjs
Labels: type: infrastructure

#10809 docs: Fix typos
  docs/configuration/legend.md
  docs/samples/line/point-styling.md
  docs/samples/scale-options/grid.md
Labels: type: documentation

#10820 Small grammar fixes in docs
  docs/developers/plugins.md
  docs/developers/publishing.md
  docs/general/padding.md
Labels: type: documentation

#10822 Bump alpha 3
  package.json
Labels: type: chore

#10831 Update example chart config type, remove whitespace
  .size-limit.cjs
  docs/general/data-structures.md
Labels: type: documentation

#10826 Fix month
  docs/axes/cartesian/time.md
Labels: type: documentation
