Repository chartjs/Chart.js, pull requests merged in 2022-12, with the labels that each got.

#10942 Ensure that args are saved inside of the throttled helper
  src/helpers/helpers.extras.ts
Labels: type: bug

#10955 Update auto import in usage docs
  docs/getting-started/usage.md
Labels: type: documentation

#10965 Broken link is fixed.
  docs/general/colors.md
Labels: type: documentation

#10964 Allow dynamic datasets to be colored
  docs/general/colors.md
  src/plugins/plugin.colors.ts
  test/fixtures/plugin.colors/dynamic-datasets-default.js
  test/fixtures/plugin.colors/dynamic-datasets-default.png
  test/fixtures/plugin.colors/dynamic-datasets-force-override.js
  test/fixtures/plugin.colors/dynamic-datasets-force-override.png
Labels: type: enhancement

#10974 chore: add lint cache
  .gitignore
  package.json
Labels: type: chore

#10976 docs: Update Slack link
  README.md
  docs/.vuepress/config.ts
  docs/developers/contributing.md
  docs/getting-started/usage.md
  docs/index.md
  docs/migration/v3-migration.md
Labels: type: documentation

#10983 bunp version to 4.1.0
  package.json
Labels: type: chore

#10962 test: turn on types linting
  src/helpers/helpers.options.ts
  types/tests/autogen.js
  types/tests/dataset_null_data.ts
  types/tests/extensions/scale.ts
  types/tests/interaction.ts
  types/tests/layout/position.ts
  types/tests/parsed.data.type.ts
  types/tests/plugins/plugin.filler/fill_target_true.ts
  types/tests/register.ts
  types/tests/scales/chart_options.ts
  types/tests/scales/options.ts
  types/tests/scriptable.ts
  types/tests/scriptable_core_chart_options.ts
  types/tests/tsconfig.json
Labels: type: chore

#10963 fix: unbind instance config from chart type
  types/index.d.ts
  types/tests/config_types.ts
Labels: type: types

#10966 add getLabelItems public method
  src/core/core.scale.js
  test/specs/core.scale.tests.js
  types/helpers/helpers.canvas.d.ts
  types/index.d.ts
Labels: type: enhancement

#10990 chore: Fix build badge in README
  README.md
Labels: type: infrastructure

#10992 fix: hotfix chart.js/auto for commonjs
  auto/auto.cjs
  package.json
  test/integration/node-commonjs/package.json
  test/integration/node-commonjs/test-auto.js
Labels: type: bug

#10971 fix: avoid resize loop when browser zoom is set to 90%
  src/helpers/helpers.dom.ts
  test/specs/helpers.dom.tests.js
Labels: type: bug

#10997 Bump to 4.1.1
  package.json
Labels: type: chore

#11000 chore: replace cp with js code
  package.json
Labels: type: chore

#11006 Fixes missing markdown links in docs
  docs/charts/bar.md
Labels: type: documentation

#11004 Update link to UMD bundle for master
  .github/ISSUE_TEMPLATE/bug.yml
Labels: type: chore

#11008 Add Z index to border options
  src/types/index.d.ts
Labels: type: types

#11016 fix: fix Plugin interface
  src/types/basic.d.ts
  test/types/register.ts
Labels: type: types
