Repository chartjs/Chart.js, pull requests merged in 2022-01, with the labels that each got.

#10024 Fix using above/below filling option with discontinuous lines
  src/plugins/plugin.filler.js
  test/fixtures/plugin.filler/line/boundary/above-below-line-null-start.json
  test/fixtures/plugin.filler/line/boundary/above-below-line-null-start.png
  test/fixtures/plugin.filler/line/boundary/above-below-line-null.json
  test/fixtures/plugin.filler/line/boundary/above-below-line-null.png
Labels: type: bug

#10038 Improve issue templates
  .github/ISSUE_TEMPLATE/BUG.md
  .github/ISSUE_TEMPLATE/DOCS.md
  .github/ISSUE_TEMPLATE/FEATURE.md
  .github/ISSUE_TEMPLATE/SUPPORT.md
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: type: chore

#10045 typo Cofiguration
  docs/configuration/index.md
Labels: type: documentation

#10057 add typing and docs for maxTicksLimit all scales
  docs/axes/cartesian/_common_ticks.md
  docs/axes/cartesian/linear.md
  types/index.esm.d.ts
Labels: type: documentation, type: types

#10078 Move scriptable and array to helper function in types
  types/index.esm.d.ts
Labels: type: chore, type: types

#10103 Fix typos found by codespell
  docs/charts/doughnut.md
  docs/charts/polar.md
  docs/configuration/animations.md
  docs/configuration/subtitle.md
  docs/getting-started/v3-migration.md
  docs/samples/information.md
  src/helpers/helpers.config.js
  src/helpers/helpers.extras.js
  src/plugins/plugin.tooltip.js
  test/specs/controller.line.tests.js
  test/specs/core.animations.tests.js
  test/specs/core.controller.tests.js
  test/specs/helpers.interpolation.tests.js
  test/specs/scale.time.tests.js
  types/helpers/helpers.extras.d.ts
  types/index.esm.d.ts
Labels: type: documentation

#10111 Change repeating alingment string to single type
  types/index.esm.d.ts
Labels: type: types

#10117 add SubTitle to TS register test
  types/tests/register.ts
Labels: type: chore
