Repository chartjs/Chart.js, pull requests merged in 2022-07, with the labels that each got.

#10446 Add a stale version warning + a link to the latest version of docs
  docs/.vuepress/config.js
Labels: type: documentation

#10412 Add pointStyleWidth option for legend
  docs/configuration/legend.md
  src/helpers/helpers.canvas.js
  src/plugins/plugin.legend.js
  types/helpers/helpers.canvas.d.ts
Labels: type: enhancement

#10494 Allow clip to be configurable in options object typescript
  docs/charts/bar.md
  docs/charts/bubble.md
  docs/charts/doughnut.md
  docs/charts/line.md
  docs/charts/polar.md
  docs/charts/radar.md
  types/index.esm.d.ts
Labels: type: types

#10495 Improve error message with id of the canvas
  src/core/core.controller.js
  test/specs/core.controller.tests.js
Labels: type: enhancement

#10497 Update link to be able to use within github
  docs/getting-started/index.md
Labels: type: documentation

#10490 document defaults for plugins
  docs/configuration/canvas-background.md
  docs/developers/plugins.md
Labels: type: documentation

#10489 draw tooltip with object borderwidth
  src/plugins/plugin.tooltip.js
Labels: type: bug

#10484 Resolve plugin defaults for local plugins
  src/core/core.plugins.js
  test/specs/core.plugin.tests.js
Labels: type: bug

#10509 Bump to 3.8.1
  package-lock.json
  package.json
Labels: type: chore

#10513 Explicitly include package.json files for subpackages
  .github/workflows/release.yml
  package-lock.json
  package.json
Labels: type: bug, type: chore

#10516 Clarifying threshold requirement in the docs for decimation
  docs/configuration/decimation.md
Labels: type: documentation

#10515 Fix dead link on reload or open in new tab
  docs/axes/labelling.md
Labels: type: documentation

#10519 Enable borderDash option in the grid as scriptable
  docs/axes/styling.md
  src/core/core.scale.js
  test/fixtures/core.scale/grid/scriptable-borderDash.js
  test/fixtures/core.scale/grid/scriptable-borderDash.png
  types/index.esm.d.ts
Labels: type: enhancement

#10517 parsing: support dot(s) in object keys
  docs/general/data-structures.md
  src/helpers/helpers.core.js
  test/specs/helpers.core.tests.js
Labels: type: enhancement, type: performance

#10520 Fix Stack Overflow tag: chart.js
  README.md
Labels: type: documentation

#10522 Fix Stack Overflow tag: chart.js
  docs/developers/contributing.md
  docs/index.md
Labels: type: documentation

#10518 Improve docs radial linear grid
  docs/axes/radial/linear.md
  docs/axes/styling.md
Labels: type: documentation

#10523 fix: calc visible points on update #10467
  src/controllers/controller.line.js
  src/helpers/helpers.collection.js
  test/specs/controller.line.tests.js
Labels: type: bug

#10524 pass boxWidth only if pointStyleWidth presents
  src/plugins/plugin.legend.js
Labels: type: bug

#10530 Skip all borders if borderSkipped === true
  docs/charts/bar.md
  src/controllers/controller.bar.js
  types/index.esm.d.ts
Labels: type: enhancement

#10405 Add circular prop to arc element
  docs/charts/polar.md
  docs/configuration/elements.md
  src/elements/element.arc.js
  test/specs/element.arc.tests.js
  types/index.esm.d.ts
Labels: type: enhancement

#10527 Add docs for changing from time scale to logarithmic/linear scale
  docs/axes/cartesian/time.md
Labels: type: documentation

#10528 feat: pass some chart options to DateAdapter
  src/core/core.adapters.js
  src/scales/scale.time.js
  test/specs/scale.time.tests.js
  types/adapters.d.ts
Labels: type: enhancement

#10479 Allow ESM files to be used in Node.js
  auto/auto.esm.js
  auto/auto.mjs
  auto/auto.mts
  auto/package.json
  docs/.vuepress/config.js
  docs/scripts/components.js
  docs/scripts/helpers.js
  docs/scripts/register.js
  docs/scripts/utils.js
  helpers/helpers.mjs
  helpers/helpers.mts
  helpers/package.json
  package.json
  rollup.config.js
Labels: type: enhancement, type: infrastructure
