Repository chartjs/Chart.js, pull requests merged in 2022-09, with the labels that each got.

#10643 feat: remove default axis override when custom id is given
  docs/migration/v4-migration.md
  src/core/core.config.js
  test/fixtures/controller.bar/stacking/issue-9105.js
  test/fixtures/core.scale/ticks/rotated-long.js
  test/fixtures/core.scale/ticks/rotated-multi-line.js
  test/fixtures/mixed/bar+line.js
  test/specs/core.controller.tests.js
  test/specs/core.scale.tests.js
  types/index.d.ts
Labels: type: enhancement, breaking change

#10646 fix: respect aspect ratio with container height
  docs/migration/v4-migration.md
  src/helpers/helpers.dom.js
  test/specs/core.controller.tests.js
  test/specs/helpers.dom.tests.js
  test/specs/platform.dom.tests.js
Labels: breaking change

#10652 Update bar data type to comply with floating bar charts data
  types/index.d.ts
  types/tests/controllers/bar_floating_data.ts
Labels: type: types

#10660 fix: types and tests
  src/core/core.element.ts
  src/core/core.scale.js
  src/scales/scale.time.js
  tsconfig.json
  types/helpers/index.d.ts
  types/tests/tsconfig.json
Labels: type: types

#10653 Use ticks.steSize instead of time.stepSize on time and timeseries scales
  docs/axes/cartesian/time.md
  docs/migration/v4-migration.md
  src/scales/scale.time.js
  test/fixtures/scale.time/ticks-stepsize.js
  types/index.d.ts
Labels: type: enhancement, breaking change

#10666 Fixed broken link in docs
  docs/samples/area/line-boundaries.md
Labels: type: documentation

#10663 Fix autoskip logic
  docs/migration/v4-migration.md
  src/core/core.scale.autoskip.js
  test/specs/core.scale.tests.js
Labels: type: bug, breaking change

#10641 FIX: render multiline legend items without overlapping (#10532)
  .size-limit.cjs
  src/plugins/plugin.legend.js
  test/fixtures/plugin.legend/legend-doughnut-right-center-mulitiline-labels.json
  test/fixtures/plugin.legend/legend-doughnut-right-center-mulitiline-labels.png
  test/specs/plugin.legend.tests.js
Labels: type: bug

#10701 Exclude dist folder form linting
  tsconfig.json
Labels: type: infrastructure, type: types

#10702 Add warning if filler plugin is used but not registered
  .size-limit.cjs
  docs/developers/api.md
  src/core/core.controller.js
  src/core/core.datasetController.js
  test/specs/plugin.filler.tests.js
  types/index.d.ts
Labels: type: enhancement, type: documentation

#10683 Use guard clause typings
  src/helpers/helpers.core.ts
  types/helpers/helpers.color.d.ts
  types/helpers/helpers.math.d.ts
Labels: type: enhancement, type: types

#10708 Unify data structure snipets and add ts explanation
  docs/general/data-structures.md
Labels: type: documentation

#10712 Add defaults to plugin interface
  types/index.d.ts
Labels: type: types

#10719 Update namespace of logarithmic ticks section
  docs/axes/cartesian/logarithmic.md
Labels: type: documentation

#10693 fix: aspect ratio calc
  src/helpers/helpers.dom.js
  test/specs/helpers.dom.tests.js
  test/specs/platform.dom.tests.js
Labels: type: bug

#10722 refactor: move batch of helpers to ts
  src/core/core.animation.js
  src/core/core.datasetController.js
  src/elements/element.arc.js
  src/helpers/helpers.collection.ts
  src/helpers/helpers.color.js
  src/helpers/helpers.color.ts
  src/helpers/helpers.interpolation.js
  src/helpers/helpers.interpolation.ts
  src/helpers/helpers.intl.ts
  src/helpers/helpers.math.ts
  src/helpers/helpers.rtl.ts
  src/helpers/types.ts
  types/helpers/helpers.collection.d.ts
  types/helpers/helpers.color.d.ts
  types/helpers/helpers.interpolation.d.ts
  types/helpers/helpers.intl.d.ts
  types/helpers/helpers.math.d.ts
  types/helpers/helpers.rtl.d.ts
  types/helpers/index.d.ts
Labels: type: types

#10726 Types: Export UpdateModeEnum as const
  types/index.d.ts
Labels: type: types

#10729 Export declare const enums
  types/index.d.ts
Labels: type: types
