Repository chartjs/Chart.js, pull requests merged in 2022-05, with the labels that each got.

#10328 Resolve canvasGradient is undefined in node
  src/helpers/helpers.color.js
  types/helpers/helpers.color.d.ts
Labels: type: bug, type: enhancement

#10289 display tooltips only at points in chart area
  src/core/core.interaction.js
  test/specs/core.interaction.tests.js
Labels: type: bug

#10345 Remove test job from windows runner
  .github/workflows/ci.yml
Labels: type: infrastructure

#10340 Update scale polarArea correctly on data hide
  src/controllers/controller.polarArea.js
  test/specs/controller.polarArea.tests.js
Labels: type: bug

#10367 Coveralls no longer runs on Windows CI
  .github/workflows/ci.yml
Labels: type: infrastructure

#10371 Update to v0.2.1 color dependency to fix bug with invalid colours
  package-lock.json
  package.json
Labels: type: bug

#10362 Add option to include invisible points
  docs/configuration/interactions.md
  src/core/core.defaults.js
  src/core/core.interaction.js
  src/platform/platform.dom.js
  test/specs/core.interaction.tests.js
  types/index.esm.d.ts
Labels: type: enhancement

#10364 Types: Allow font to be partial scriptable and individually scriptable
  types/index.esm.d.ts
Labels: type: types

#10377 Bump to 3.8.0
  package-lock.json
  package.json
Labels: type: chore

#10387 Allow for each dataset to be individually typed without a main type
  types/index.esm.d.ts
  types/tests/chart_types.ts
Labels: type: types
