Repository chartjs/Chart.js, pull requests merged in 2022-03, with the labels that each got.

#10243 Replace deprecated String.prototype.substr()
  src/helpers/helpers.core.js
Labels: type: chore

#10247 Resolve circulair import filler plugin
  src/plugins/plugin.filler/filler.helper.js
  src/plugins/plugin.filler/filler.target.js
  src/plugins/plugin.filler/filler.target.stack.js
Labels: type: chore

#10250 Update link to filler plugin
  docs/charts/area.md
Labels: type: documentation

#10254 Add missing fields to the ScriptableContext type
  types/index.esm.d.ts
Labels: type: types

#10046 Interaction functions
  docs/configuration/interactions.md
  package-lock.json
  package.json
  src/core/core.controller.js
  src/core/core.interaction.js
  src/helpers/helpers.canvas.js
  src/helpers/helpers.dom.js
  test/specs/helpers.dom.tests.js
  types/index.esm.d.ts
Labels: type: enhancement

#10266 Correct chart initialization flow
  docs/developers/init_flowchart.png
  docs/developers/plugin_flowcharts.drawio
Labels: type: documentation

#10269 add startAngle to radial scale options typings
  types/index.esm.d.ts
Labels: type: types

#10259 Fix a typo in data-structures.md
  docs/general/data-structures.md
Labels: type: documentation
