Repository chartjs/Chart.js, pull requests merged in 2022-06, with the labels that each got.

#10392 Clarify api docs
  docs/developers/api.md
  docs/developers/updates.md
Labels: type: documentation

#10400 Fix default value of 'includeInvisible' option in the documentation
  docs/configuration/interactions.md
Labels: type: documentation

#10404 Add padding to pointLabels type, add type to scriptable context
  types/index.esm.d.ts
Labels: type: types

#10410 Typo fix
  docs/samples/area/line-datasets.md
Labels: type: documentation

#10399 chore: Set permissions for GitHub actions
  .github/workflows/ci.yml
  .github/workflows/compressed-size.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
Labels: type: infrastructure

#10423 chore: Included githubactions in the dependabot config
  .github/dependabot.yml
Labels: type: infrastructure

#10434 Clarify helpers need to be imported when using bundlers
  docs/configuration/interactions.md
Labels: type: documentation

#10414 Respect `fill: false` with custom draw times
  src/plugins/plugin.filler/filler.helper.js
  src/plugins/plugin.filler/index.js
  test/fixtures/plugin.filler/line/drawTimeFillFalse/beforeDatasetDraw.js
  test/fixtures/plugin.filler/line/drawTimeFillFalse/beforeDatasetDraw.png
  test/fixtures/plugin.filler/line/drawTimeFillFalse/beforeDatasetsDraw.js
  test/fixtures/plugin.filler/line/drawTimeFillFalse/beforeDatasetsDraw.png
  test/fixtures/plugin.filler/line/drawTimeFillFalse/beforeDraw.js
  test/fixtures/plugin.filler/line/drawTimeFillFalse/beforeDraw.png
Labels: type: bug

#10415 Update responsive.md
  docs/configuration/responsive.md
Labels: type: documentation

#10436 Add index to legendItem interface
  types/index.esm.d.ts
  types/tests/plugins/defaults.ts
Labels: type: types

#10456 Update aspectRatio documentation
  docs/configuration/responsive.md
Labels: type: documentation

#10454 Fix crash with skipNull and uneven datasets
  src/controllers/controller.bar.js
  test/specs/controller.bar.tests.js
Labels: type: bug

#10447 Enforce maximum width on chart editor blocks in the docs
  docs/.vuepress/styles/index.styl
Labels: type: documentation

#10445 Add dependency updates under the development in release drafter
  .github/release-drafter.yml
Labels: type: infrastructure
