Repository chartjs/Chart.js, pull requests merged in 2022-11, with the labels that each got.

#10844 Alternative remove docs from publish
  package.json
Labels: type: infrastructure

#10753 refactor: migrate helpers.options to typescript
  src/helpers/helpers.options.ts
  src/helpers/types.ts
  types/helpers/helpers.canvas.d.ts
  types/helpers/helpers.options.d.ts
  types/helpers/index.d.ts
  types/tests/helpers/options.ts
Labels: type: types

#10851 Enable colors plugin for pie charts
  src/plugins/plugin.colors.ts
  test/fixtures/plugin.colors/pie.js
  test/fixtures/plugin.colors/pie.png
Labels: type: bug

#10855 Fix the missing apply for the color on the legend labels
  src/controllers/controller.doughnut.js
  src/controllers/controller.polarArea.js
  test/specs/global.defaults.tests.js
Labels: type: bug

#10857 docs: notes about html legend, tooltip and title
  docs/configuration/legend.md
  docs/configuration/title.md
  docs/configuration/tooltip.md
Labels: type: documentation

#10816 Updated docs (why Chart.js + getting started + step-by-step guide)
  docs/developers/index.md
  docs/getting-started/index.md
  docs/getting-started/installation.md
  docs/getting-started/integration.md
  docs/getting-started/preview.png
  docs/getting-started/usage-1.png
  docs/getting-started/usage-2.png
  docs/getting-started/usage-3.png
  docs/getting-started/usage-4.png
  docs/getting-started/usage-5.png
  docs/getting-started/usage-6.png
  docs/getting-started/usage-7.png
  docs/getting-started/usage-8.png
  docs/getting-started/usage.md
  docs/index.md
  docs/samples/information.md
Labels: type: documentation

#10806 fix: Always draw full arcs and borders for doughnut slices
  src/elements/element.arc.ts
  test/fixtures/controller.doughnut/single-slice-circumference-405.png
  test/fixtures/controller.doughnut/single-slice-offset.js
  test/fixtures/controller.doughnut/single-slice-offset.png
Labels: type: bug

#10867 check the data set type in DoughnutController
  src/controllers/controller.doughnut.js
  test/specs/mixed.tests.js
Labels: type: bug

#10869 Remove type attribute from dataset specific type specification
  src/plugins/plugin.colors.ts
  types/index.d.ts
Labels: type: bug, type: types

#10868 v4.0.0 bump
  package.json
Labels: type: chore

#10871 Fix release
  .github/workflows/release.yml
  package.json
Labels: type: bug, type: infrastructure

#10872 Remove V3 support, update readme
  .github/ISSUE_TEMPLATE/bug.yml
  .github/release-drafter.yml
  README.md
Labels: type: documentation

#10884 Move border opts to correct location for samples
  docs/axes/cartesian/index.md
  docs/samples/scales/stacked.md
Labels: type: documentation

#10886 Pointstyle false
  docs/configuration/elements.md
  docs/samples/line/point-styling.md
  src/helpers/helpers.canvas.js
  test/fixtures/controller.line/pointStyle/indexable.js
  test/fixtures/controller.line/pointStyle/indexable.png
  test/fixtures/controller.radar/pointStyle/indexable.js
  test/fixtures/controller.radar/pointStyle/indexable.png
  test/fixtures/element.point/rotation.js
  test/fixtures/element.point/rotation.png
  test/fixtures/plugin.tooltip/point-style.js
  test/fixtures/plugin.tooltip/point-style.png
  types/index.d.ts
Labels: type: enhancement

#10870 feat: colors for mixed charts
  src/plugins/plugin.colors.ts
  test/fixtures/plugin.colors/mixed.js
  test/fixtures/plugin.colors/mixed.png
Labels: type: enhancement

#10766 fix: stacked bar chart minBarLength causes overlapping
  src/controllers/controller.bar.js
  src/core/core.datasetController.js
  test/fixtures/controller.bar/minBarLength/horizontal-stacked-no-overlap.js
  test/fixtures/controller.bar/minBarLength/horizontal-stacked-no-overlap.png
  test/fixtures/controller.bar/minBarLength/vertical-stacked-no-overlap.js
  test/fixtures/controller.bar/minBarLength/vertical-stacked-no-overlap.png
  test/specs/core.datasetController.tests.js
Labels: type: bug

#10910 Add stepSize option to time scale options types
  types/index.d.ts
  types/tests/scales/options.ts
Labels: type: types

#10903 docs: add info about ESM into migration guide.
  docs/migration/v4-migration.md
Labels: type: documentation

#10919 Use UDM build for reproducible sample
  .github/ISSUE_TEMPLATE/bug.yml
Labels: type: chore

#10904 Allow color plugin to work with custom dataset controllers
  src/plugins/plugin.colors.ts
Labels: type: enhancement
