Repository chartjs/Chart.js, pull requests merged in 2022-08, with the labels that each got.

#10439 feat: remove line element from scatter controller
  src/controllers/controller.line.js
  src/controllers/controller.scatter.js
  src/helpers/helpers.extras.js
  test/specs/controller.scatter.tests.js
Labels: type: enhancement

#10541 Bump to 3.9.0
  package-lock.json
  package.json
Labels: type: chore

#10010 Bug/Radial linear scale grid get correct options at index
  docs/.vuepress/config.js
  docs/migration/v3-migration.md
  docs/migration/v4-migration.md
  src/scales/scale.radialLinear.js
  test/fixtures/scale.radialLinear/gridlines-scriptable.png
  test/fixtures/scale.radialLinear/indexable-gridlines.png
Labels: type: bug, breaking change

#10555 Bump to 3.9.1
  package-lock.json
  package.json
Labels: type: chore

#10554 Add integration test(s) for Node
  package-lock.json
  package.json
  test/integration/integration-test.js
  test/integration/node/package-lock.json
  test/integration/node/package.json
  test/integration/node/test.cjs
  test/integration/node/test.mjs
Labels: type: infrastructure

#10469 Fix offset on doughnut charts
  src/elements/element.arc.js
  test/fixtures/controller.doughnut/doughnut-offset.png
  test/fixtures/controller.doughnut/doughnut-spacing-and-offset.png
  test/fixtures/controller.doughnut/pie-offset.png
Labels: type: bug, breaking change

#10550 Move parameter of TType in ChartMeta to first option
  docs/migration/v4-migration.md
  types/index.esm.d.ts
  types/tests/controllers/doughnut_meta_total.ts
Labels: breaking change, type: types

#10504 fix: treeshaking
  .eslintrc.yml
  .github/workflows/compressed-size.yml
  .size-limit.js
  docs/.vuepress/config.js
  package-lock.json
  package.json
  rollup.config.js
  src/controllers/controller.bar.js
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.line.js
  src/controllers/controller.pie.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.radar.js
  src/controllers/controller.scatter.js
  src/core/core.adapters.js
  src/core/core.animator.js
  src/core/core.controller.js
  src/core/core.datasetController.js
  src/core/core.defaults.js
  src/core/core.element.js
  src/core/core.registry.js
  src/elements/element.arc.js
  src/elements/element.bar.js
  src/elements/element.line.js
  src/elements/element.point.js
  src/plugins/plugin.tooltip.js
  src/scales/scale.category.js
  src/scales/scale.linear.js
  src/scales/scale.logarithmic.js
  src/scales/scale.radialLinear.js
  src/scales/scale.time.js
  src/scales/scale.timeseries.js
  test/specs/scale.category.tests.js
Labels: type: enhancement, breaking change

#10540 fix: pass timestamp to ticks callback
  docs/axes/labelling.md
  docs/migration/v4-migration.md
  src/scales/scale.time.js
  test/specs/scale.time.tests.js
Labels: type: bug, breaking change

#10564 Use ESM config file for Rollup
  rollup.config.js
Labels: type: infrastructure

#10566 Fix docs build
  docs/.vuepress/config.ts
  package-lock.json
  package.json
  scripts/docs-config.sh
  types/index.d.ts
Labels: type: infrastructure, type: documentation

#10549 Remove destroy hook
  docs/developers/destroy_flowchart.png
  docs/developers/plugin_flowcharts.drawio
  docs/migration/v4-migration.md
  karma.conf.cjs
  rollup.config.js
  src/core/core.controller.js
  test/specs/core.controller.tests.js
  types/index.d.ts
Labels: breaking change

#10572 remove double space, eslint allow dynamic import
  .eslintrc.yml
  karma.conf.cjs
Labels: type: infrastructure

#10526 feat: sideEffects false
  package.json
  src/core/core.animations.defaults.js
  src/core/core.animations.js
  src/core/core.defaults.js
  src/core/core.layouts.defaults.js
  src/core/core.layouts.js
  src/core/core.scale.defaults.js
  src/core/core.scale.js
  src/scales/scale.time.js
Labels: type: enhancement, breaking change

#10568 build: emit sourcemaps
  rollup.config.js
Labels: type: enhancement

#10563 Add integration test(s) for Web
  .eslintignore
  test/integration/integration-test.cjs
  test/integration/react-browser/package.json
  test/integration/react-browser/public/index.html
  test/integration/react-browser/src/App.js
  test/integration/react-browser/src/index.js
Labels: type: infrastructure

#10589 Downgrade karma preprocessor
  package-lock.json
  package.json
Labels: type: chore, dependencies

#10579 fix: allow nulls in barchart data type
  types/index.d.ts
Labels: type: types

#10567 feat: tooltip callbacks fallback
  .size-limit.cjs
  docs/configuration/tooltip.md
  docs/migration/v4-migration.md
  src/plugins/plugin.tooltip.js
  test/specs/plugin.tooltip.tests.js
  types/index.d.ts
Labels: type: enhancement

#10573 chore: upgrade dependencies
  package-lock.json
  package.json
Labels: dependencies

#10585 add correct padding object to type
  types/geometric.d.ts
  types/index.d.ts
Labels: type: types

#10590 Add `grouped` option to the typings for barchart
  types/index.d.ts
Labels: type: types

#10591 Change way that linear scales calculate min and max
  docs/migration/v4-migration.md
  src/scales/scale.linearbase.js
Labels: breaking change, type: chore

#10582 Allow animations to be set to false for the tooltip typings
  types/index.d.ts
Labels: type: types

#10551 Use borderRadius for legend and remove fallbacks
  docs/configuration/legend.md
  docs/migration/v4-migration.md
  src/plugins/plugin.legend.js
  test/specs/plugin.legend.tests.js
  types/index.d.ts
Labels: type: enhancement, breaking change

#10548 fix: same-looking tooltips on charts
  docs/migration/v4-migration.md
  docs/samples/other-charts/bubble.md
  docs/samples/other-charts/scatter-multi-axis.md
  docs/samples/other-charts/scatter.md
  src/controllers/controller.bubble.js
  src/controllers/controller.doughnut.js
  src/controllers/controller.polarArea.js
  src/controllers/controller.scatter.js
  test/specs/controller.bar.tests.js
  test/specs/controller.bubble.tests.js
  test/specs/controller.doughnut.tests.js
  test/specs/controller.line.tests.js
  test/specs/controller.polarArea.tests.js
  test/specs/controller.radar.tests.js
  test/specs/controller.scatter.tests.js
  test/specs/global.defaults.tests.js
Labels: type: enhancement, breaking change

#10605 Change react integration test to TS
  test/integration/node/package-lock.json
  test/integration/react-browser/package.json
  test/integration/react-browser/src/App.tsx
  test/integration/react-browser/src/AppAuto.tsx
  test/integration/react-browser/src/index.js
  test/integration/react-browser/src/index.tsx
  test/integration/react-browser/tsconfig.json
Labels: type: enhancement

#10571 Put the border opts in own object
  docs/axes/_common.md
  docs/axes/styling.md
  docs/migration/v4-migration.md
  docs/samples/scale-options/grid.md
  src/core/core.scale.defaults.js
  src/core/core.scale.js
  src/scales/scale.radialLinear.js
  test/fixtures/core.layouts/stacked-boxes-with-weight.js
  test/fixtures/core.layouts/stacked-boxes.js
  test/fixtures/core.scale/border-behind-elements.js
  test/fixtures/core.scale/cartesian-axis-border-settings.json
  test/fixtures/core.scale/grid/border-over-grid.js
  test/fixtures/core.scale/grid/colors.js
  test/fixtures/core.scale/grid/scriptable-borderDash.js
  test/fixtures/core.scale/label-offset-vertical-axes.json
  test/fixtures/core.scale/tick-drawing.json
  test/fixtures/core.scale/tick-override-styles.json
  test/fixtures/core.scale/x-axis-position-center.json
  test/fixtures/core.scale/x-axis-position-dynamic.json
  test/fixtures/core.scale/y-axis-position-center.json
  test/fixtures/core.scale/y-axis-position-dynamic.json
  test/fixtures/scale.radialLinear/border-dash.json
  test/fixtures/scale.radialLinear/circular-border-dash.json
  test/fixtures/scale.timeseries/financial-daily.js
  test/specs/scale.linear.tests.js
  test/specs/scale.time.tests.js
  types/index.d.ts
Labels: type: enhancement, breaking change

#10608 Use the element's window in getComputedStyle
  src/helpers/helpers.dom.js
Labels: type: enhancement

#10598 fix: allow beforeTooltipDraw to be cancelable
  src/plugins/plugin.tooltip.js
  types/index.d.ts
Labels: type: bug

#9166 Refine logarithmic scaling / tick generation
  src/core/core.ticks.js
  src/scales/scale.logarithmic.js
  test/fixtures/scale.logarithmic/large-range.js
  test/fixtures/scale.logarithmic/large-range.png
  test/fixtures/scale.logarithmic/large-values-small-range.js
  test/fixtures/scale.logarithmic/large-values-small-range.png
  test/fixtures/scale.logarithmic/med-range.js
  test/fixtures/scale.logarithmic/med-range.png
  test/fixtures/scale.logarithmic/min-max.js
  test/fixtures/scale.logarithmic/min-max.png
  test/fixtures/scale.logarithmic/small-range.js
  test/fixtures/scale.logarithmic/small-range.png
  test/specs/core.ticks.tests.js
  test/specs/scale.logarithmic.tests.js
Labels: type: bug, breaking change

#10607 Documentation: how to add static typing to plugins
  docs/configuration/canvas-background.md
  docs/developers/charts.md
  docs/developers/plugins.md
Labels: type: documentation

#10576 Switch to pnpm
  .github/workflows/ci.yml
  .github/workflows/compressed-size.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/release.yml
  docs/.vuepress/config.ts
  docs/developers/contributing.md
  docs/package.json
  docs/samples/advanced/derived-axis-type.md
  docs/samples/advanced/derived-chart-type.md
  docs/samples/utils.md
  karma.conf.cjs
  package-lock.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test/integration/integration-test.cjs
  test/integration/node/package.json
  test/integration/react-browser/package.json
  test/integration/react-browser/src/App.tsx
  test/integration/react-browser/src/AppAuto.tsx
Labels: type: infrastructure

#10612 Remove tooltip constructor fallbacks, `this.chart` and `this._chart`
  .size-limit.cjs
  docs/migration/v4-migration.md
  src/plugins/plugin.tooltip.js
Labels: breaking change

#10614 Fix filter paramater in package.json
  package.json
Labels: type: bug, type: infrastructure

#10613 move option to correct namespace
  docs/configuration/canvas-background.md
  docs/developers/plugins.md
Labels: type: documentation

#10569 Document components for bundle optimization
  docs/getting-started/integration.md
Labels: type: documentation

#10621 docs: fix images loading
  docs/.vuepress/config.ts
  docs/package.json
  pnpm-lock.yaml
Labels: type: documentation

#10640 Fix broken link
  docs/configuration/index.md
Labels: type: documentation

#10645 Update link to master umd build
  docs/developers/contributing.md
Labels: type: documentation

#10632 Bump `markdown-it` in docs
  docs/package.json
  pnpm-lock.yaml
Labels: dependencies

#10627 Convert the easing helpers to typescript
  src/helpers/helpers.easing.js
  src/helpers/helpers.easing.ts
  src/helpers/types.ts
  types/helpers/helpers.easing.d.ts
  types/index.d.ts
Labels: type: types

#10642 Fix permissions
  .github/workflows/release.yml
Labels: type: infrastructure
