Repository chartjs/Chart.js, pull requests merged in 2023-08, with the labels that each got.

#11433 chore: bump to v4.3.3
  package.json
Labels: type: chore

#11404 Add clip option to scale configuration to allow unclipped scales
  docs/axes/cartesian/_common.md
  src/core/core.controller.js
  src/core/core.scale.defaults.js
  src/types/index.d.ts
  test/fixtures/core.layouts/stacked-boxes-max-index-without-clip.js
  test/fixtures/core.layouts/stacked-boxes-max-index-without-clip.png
  test/fixtures/core.layouts/stacked-boxes-max-without-clip.js
  test/fixtures/core.layouts/stacked-boxes-max-without-clip.png
Labels: type: enhancement

#11435 BorderRadius of Bar Chart issue on Firefox 116
  src/helpers/helpers.canvas.ts
Labels: type: bug

#11348 fix: Add backgroundColor type on CoreScaleOptions
  src/types/index.d.ts
Labels: type: types

#11461 Bump 4.4.0
  package.json
Labels: type: chore
