Repository chartjs/Chart.js, pull requests merged in 2023-06, with the labels that each got.

#11324 Refined grammar and updated overall .md documentation files
  docs/axes/cartesian/linear.md
  docs/axes/index.md
  docs/axes/radial/linear.md
  docs/charts/bar.md
  docs/charts/doughnut.md
  docs/charts/line.md
  docs/charts/scatter.md
  docs/configuration/animations.md
  docs/configuration/device-pixel-ratio.md
  docs/configuration/elements.md
  docs/configuration/index.md
  docs/configuration/legend.md
  docs/configuration/locale.md
  docs/configuration/responsive.md
  docs/configuration/tooltip.md
  docs/developers/api.md
  docs/developers/charts.md
  docs/developers/contributing.md
  docs/developers/index.md
  docs/developers/updates.md
  docs/general/colors.md
  docs/general/data-structures.md
  docs/general/fonts.md
  docs/general/options.md
  docs/general/padding.md
  docs/index.md
  src/core/core.datasetController.js
Labels: type: documentation

#11345 Clarify update docs
  docs/developers/updates.md
Labels: type: documentation

#11346 Add text stoke radial linear scale
  src/scales/scale.radialLinear.js
Labels: type: bug

#11350 Add events property to Plugin defined type
  src/types/index.d.ts
Labels: type: types

#11358 Add `beforeDraw` to drawtime type
  src/types/index.d.ts
Labels: type: types
