Repository chartjs/Chart.js, pull requests merged in 2023-01, with the labels that each got.

#11034 chore: version bump
  package.json
Labels: type: chore

#11037 Specify `module` for Webpack 4
  auto/package.json
  helpers/package.json
  package.json
Labels: type: infrastructure

#11051 fix: updated type for doughnut offset
  docs/charts/doughnut.md
  src/types/index.d.ts
  test/types/controllers/doughnut_spacing_offset.ts
Labels: type: types

#11056 Remove console.warn from a test case where not needed
  test/specs/helpers.config.tests.js
Labels: type: chore

#11057 Update banner
  README.md
Labels: type: documentation

#11058 Add banner to docs
  docs/index.md
Labels: type: documentation

#11003 Check colors definition in the chart options
  src/plugins/plugin.colors.ts
  test/fixtures/plugin.colors/chart-options-colors.js
  test/fixtures/plugin.colors/chart-options-colors.png
Labels: type: bug

#11017 Change 'normal' update mode to 'default' as documented
  src/types/index.d.ts
Labels: type: types

#11063 Add format method to time scale to format timestamp using scale options
  src/scales/scale.time.js
  src/types/index.d.ts
  test/specs/scale.time.tests.js
Labels: type: enhancement

#11093 Remove meetup banner
  README.md
  docs/index.md
Labels: type: documentation

#11095 🐛 fixes compilation error when option --isolatedModules is set
  src/types/index.d.ts
Labels: type: types

#11081 fix: add bgColor type in RadialLinearScaleOptions
  src/types/index.d.ts
Labels: type: types
