Repository chartjs/Chart.js, pull requests merged in 2023-02, with the labels that each got.

#11110 Remove override warning tooltips
  docs/configuration/tooltip.md
Labels: type: documentation

#11113 Update link to new template
  .github/ISSUE_TEMPLATE/bug.yml
Labels: type: chore

#11115 Add colors plugin TS options to be configured
  src/types/index.d.ts
  test/types/plugins/plugin.colors/colors.ts
Labels: type: types

#11102 chore: #10963 revert
  src/types/index.d.ts
  test/types/config_types.ts
Labels: type: types

#11124 Remove circumference property retrieving from arc element for center calculation because not used
  src/elements/element.arc.ts
Labels: type: chore

#11069 Use maxTicksLimit option to calculate the labels size on ticks
  src/core/core.scale.js
  test/fixtures/scale.category/max-ticks-limit-norotation.js
  test/fixtures/scale.category/max-ticks-limit-norotation.png
Labels: type: bug

#11130 Bump to 4.2.1
  package.json
Labels: type: chore

#11116 Fix: don't generate ticks > max if max is specified
  src/scales/scale.linearbase.js
  test/specs/scale.linear.tests.js
Labels: type: bug

#11135 Change labelColors to labelColor in tooltip drawColorBox method.
  src/plugins/plugin.tooltip.js
Labels: type: chore

#11127 Add borderDash options to arc element
  docs/charts/doughnut.md
  docs/charts/polar.md
  docs/configuration/elements.md
  src/controllers/controller.doughnut.js
  src/elements/element.arc.ts
  src/types/index.d.ts
  test/fixtures/controller.doughnut/borderDash/scriptable.js
  test/fixtures/controller.doughnut/borderDash/scriptable.png
  test/fixtures/controller.doughnut/borderDash/value.js
  test/fixtures/controller.doughnut/borderDash/value.png
  test/fixtures/controller.polarArea/borderDash/scriptable.js
  test/fixtures/controller.polarArea/borderDash/scriptable.png
  test/fixtures/controller.polarArea/borderDash/value.js
  test/fixtures/controller.polarArea/borderDash/value.png
Labels: type: enhancement

#11143 Docs: fix tooltip model doc.
  docs/configuration/tooltip.md
Labels: type: types

#11145 Simplify _arrayUnique
  src/helpers/helpers.collection.ts
Labels: type: chore

#11160 Specify node version for CI
  .github/workflows/ci.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/release.yml
Labels: type: infrastructure

#11154 Update tooltip.md
  docs/configuration/tooltip.md
Labels: type: documentation
