Repository chartjs/Chart.js, pull requests merged in 2023-11, with the labels that each got.

#11569 fix: pass Plugin TType down to hooks chart arg
  src/types/index.d.ts
Labels: type: types

#11570 Replace deprecated command with environment file
  .github/workflows/release.yml
Labels: type: chore

#11577 Fix backdrop padding
  src/core/core.scale.js
  test/fixtures/core.scale/tick-backdrop-alignment-inner.js
  test/fixtures/core.scale/tick-backdrop-alignment-inner.png
Labels: type: bug

#11588 fix: Guard access to window in helpers.dom.ts for browserless rendering
  src/helpers/helpers.dom.ts
Labels: type: bug

#11599 Remove size limit from CI
  .github/workflows/compressed-size.yml
  .size-limit.cjs
  package.json
  pnpm-lock.yaml
Labels: type: chore
