Repository chartjs/Chart.js, pull requests merged in 2024-08, with the labels that each got.

#11844 fix issue #11717
  src/controllers/controller.bar.js
  test/specs/controller.bar.tests.js
Labels: type: bug

#11858 Bugfix/issue 11804 tooltip show for all invisible
  src/elements/element.arc.ts
  test/specs/element.arc.tests.js
Labels: type: bug

#11862 fix(types): add xCenter and yCenter properties to RadialLinearScale interface
  src/types/index.d.ts
Labels: type: types

#11867 fix(types): exclude DeepPartial<unknown[]> from ChartOptions interface
  src/types/index.d.ts
Labels: type: types

#11863 Return false from the average tooltip positioner on no valid data
  src/core/core.scale.js
  src/plugins/plugin.tooltip.js
  test/specs/plugin.tooltip.tests.js
Labels: type: bug

#11871 Add radial linear scale to docs section of samples
  docs/samples/other-charts/polar-area.md
  docs/samples/other-charts/radar-skip-points.md
  docs/samples/other-charts/radar.md
Labels: type: documentation

#11873 Check if range method exists on element before executing it
  src/core/core.interaction.js
Labels: type: bug

#11874 Bump package version to 4.4.4
  package.json
Labels: type: chore

#11882 Fix initial dataset stacks
  src/core/core.datasetController.js
  test/fixtures/core.datasetController/stacked-initial-render.js
  test/fixtures/core.datasetController/stacked-initial-render.png
  test/specs/core.datasetController.tests.js
Labels: type: bug
