Repository chartjs/Chart.js, pull requests merged in 2024-02, with the labels that each got.

#11674 docs(types): fix description in index.d.ts
  src/types/index.d.ts
Labels: type: documentation

#11685 addListener and removeListener should be only invoked on truthy values
  src/platform/platform.dom.js
Labels: type: bug

#11689 Bump to 4.4.2
  package.json
Labels: type: chore
