Repository chartjs/Chart.js, pull requests merged in 2024-05, with the labels that each got.

#11762 Update license year
  LICENSE.md
Labels: type: documentation

#11764 do not attempt to clear canvas if one does not exist
  src/helpers/helpers.canvas.ts
  test/specs/helpers.canvas.tests.js
Labels: type: bug

#11776 Bump to 4.4.3
  package.json
Labels: type: chore

#11781 Fix some typos
  docs/migration/v4-migration.md
  src/core/core.controller.js
  test/specs/helpers.config.tests.js
Labels: type: documentation

#11780 types: Allow passing undefined for chart options
  src/types/index.d.ts
Labels: type: types

#11788 Fix drawing angle lines on reversed radial scale
  src/scales/scale.radialLinear.js
  test/fixtures/scale.radialLinear/anglelines-reverse-scale.js
  test/fixtures/scale.radialLinear/anglelines-reverse-scale.png
Labels: type: bug

#11796 Add fit method to LegendElement interface
  src/types/index.d.ts
Labels: type: types
