Repository chartjs/Chart.js, pull requests merged in 2024-10, with the labels that each got.

#11907 Avoid error if borderOpts.dash is undefined
  src/scales/scale.radialLinear.js
Labels: type: bug

#11927 Don't apply default colors in the colors plugin when defaults are used
  src/plugins/plugin.colors.ts
  test/specs/plugin.colors.tests.js
Labels: type: bug

#11931 Allow array's in backgroundColor defaults and add hover background and border color to defaults
  src/types/index.d.ts
  test/types/defaults.ts
Labels: type: types

#11932 Bump package version to 4.4.5
  package.json
Labels: type: chore

#11933 Fix 404 to samples in release drafter
  .github/release-drafter.yml
Labels: type: chore

#11943 chore: version bump for 4.4.6 release
  package.json
Labels: type: chore
