Repository chartjs/Chart.js, pull requests merged in 2025-01, with the labels that each got.

#11984 Bugfix: span gaps over null values beyond scale limits
  src/helpers/helpers.extras.ts
  test/specs/controller.line.tests.js
Labels: type: bug

#11986 Bugfix: return nearest non-null point on interaction when spanGaps=true
  src/core/core.interaction.js
  src/helpers/helpers.extras.ts
  test/specs/core.interaction.tests.js
Labels: type: bug

#11991 Bugfix: TypeError in Interaction due to out-of-bounds index
  src/core/core.interaction.js
  test/specs/core.interaction.tests.js
Labels: type: bug

#11997 Update linear-step-size.md
  docs/samples/scales/linear-step-size.md
Labels: type: documentation

#12005 Correct broken link in animations.md
  docs/configuration/animations.md
Labels: type: documentation

#12010 Type fixes for time adapters
  src/core/core.adapters.ts
  src/scales/scale.time.js
Labels: type: types

#12012 Fix helpers `Chart` type
  src/helpers/helpers.dom.ts
  test/types/helpers/dom.ts
Labels: type: bug, type: types
