Repository chartjs/Chart.js, pull requests merged in 2025-02, with the labels that each got.

#12035 Export ...ParsedData interfaces
  src/types/index.d.ts
Labels: type: bug, type: types

#12036 chore: bump to v4.4.8
  package.json
Labels: type: chore

#12039 Add docs on using from Node.js
  docs/.vuepress/config.ts
  docs/getting-started/index.md
  docs/getting-started/using-from-node-js.md
Labels: type: documentation
