Repository chartjs/Chart.js, pull requests merged in 2025-04, with the labels that each got.

#12057 fix: respect dataset clipping area when filling line charts
  src/core/core.controller.js
  src/helpers/helpers.dataset.ts
  src/helpers/index.ts
  src/plugins/plugin.filler/filler.drawing.js
  src/types/index.d.ts
  test/fixtures/plugin.filler/line/dataset/clip-bounds-x-off.js
  test/fixtures/plugin.filler/line/dataset/clip-bounds-x-off.png
  test/fixtures/plugin.filler/line/dataset/clip-bounds-x.js
  test/fixtures/plugin.filler/line/dataset/clip-bounds-x.png
  test/fixtures/plugin.filler/line/dataset/clip-bounds-y-off.js
  test/fixtures/plugin.filler/line/dataset/clip-bounds-y-off.png
  test/fixtures/plugin.filler/line/dataset/clip-bounds-y.js
  test/fixtures/plugin.filler/line/dataset/clip-bounds-y.png
Labels: type: bug

#12062 Bump version to 4.4.9
  package.json
Labels: type: chore

#12058 feature: make above/below colors in filler plugin work with pivoted line charts
  src/plugins/plugin.filler/filler.drawing.js
  test/fixtures/plugin.filler/line/above-below-vertical-linechart.js
  test/fixtures/plugin.filler/line/above-below-vertical-linechart.png
Labels: type: enhancement

#12054 [fix] #12048 - Add selfJoin option for doughnut graphs
  src/elements/element.arc.ts
  src/types/index.d.ts
  test/fixtures/controller.doughnut/selfJoin/doughnut.js
  test/fixtures/controller.doughnut/selfJoin/doughnut.png
  test/fixtures/controller.doughnut/selfJoin/pie.js
  test/fixtures/controller.doughnut/selfJoin/pie.png
Labels: type: enhancement

#12063 Add type definition for beforeEvent changed
  src/types/index.d.ts
Labels: type: types

#12064 Document requirement of 'this' when calling tick formatters
  src/types/index.d.ts
  test/types/ticks/ticks.ts
Labels: type: types

#12068 Fix minor typo, missing period
  docs/axes/cartesian/linear.md
Labels: type: documentation
